// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Pallet.DatabaseGenerated
{
    public partial class NailerDef
    {
        public int Id { get; set; }
        public int NailerId { get; set; }
        public string NailerName { get; set; }
        public string Desc1 { get; set; }
        public string Desc2 { get; set; }
        public string Desc3 { get; set; }
        public int Dock { get; set; }
        public int Nlength { get; set; }
        public int Nwidth { get; set; }
        public int Ncap { get; set; }
        public int Nwrn { get; set; }
        public int Msize { get; set; }
        public long Mcolor { get; set; }
    }
}