// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Pallet.DatabaseGenerated
{
    public partial class ProgTxt
    {
        public int Id { get; set; }
        public string Type { get; set; }
        public string Obj { get; set; }
        public string Txt { get; set; }
        public string Lng1 { get; set; }
        public string Lng2 { get; set; }
        public string Lng3 { get; set; }
        public bool Defined { get; set; }
    }
}