// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Pallet.DatabaseGenerated
{
    public partial class WtableDef
    {
        public int Id { get; set; }
        public int WtableId { get; set; }
        public string WtableName { get; set; }
        public string A1Conf { get; set; }
        public string A2Conf { get; set; }
        public string B1Conf { get; set; }
        public string B2Conf { get; set; }
        public bool BEna { get; set; }
        public int A1OffsX { get; set; }
        public int A1OffsY { get; set; }
        public int A2OffsX { get; set; }
        public int A2OffsY { get; set; }
        public int B1OffsX { get; set; }
        public int B1OffsY { get; set; }
        public int B2OffsX { get; set; }
        public int B2OffsY { get; set; }
        public int ASizeX { get; set; }
        public int ASizeY { get; set; }
        public int BSizeX { get; set; }
        public int BSizeY { get; set; }
        public int AWaSizeX { get; set; }
        public int AWaSizeY { get; set; }
        public int BWaSizeX { get; set; }
        public int BWaSizeY { get; set; }
        public int AWaOffsX { get; set; }
        public int AWaOffsY { get; set; }
        public int BWaOffsX { get; set; }
        public int BWaOffsY { get; set; }
    }
}