// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Pallet.ExternalDatabase.Models;

namespace Pallet.ExternalDatabase.Context
{
    public interface IExternalDbContext
    {
        DbSet<T3dVerpackungDetail> T3dVerpackungDetails { get; set; }
        DbSet<T3dVerpackung> T3dVerpackungs { get; set; }
        DbSet<Auftrag> TAuftrags { get; set; }
        DbSet<Firma> TFirmas { get; set; }
        DbSet<NailingData> TRoboPackageItemNailingData { get; set; }
        DbSet<PackageItemOrder> TRoboPackageItemProcessOrders { get; set; }
        DbSet<PackageItem> TRoboPackageItems { get; set; }
        DbSet<Robo> TRobos { get; set; }
        DbSet<RobotTaskItem> TRoboTaskItems { get; set; }
        DbSet<Verpackung> TVerpackungs { get; set; }
    }
}