// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Pallet.BaseDatabase.Base;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Anfragen und Aufträge eines Kunden
    /// Inquiries and orders from a customer
    /// </summary>
    [Table("t_auftrag")]
    //[Index("NId", "CNr", "CNrAnfrage", "NKundeId", "DAuftragErstellt", "NNiederlassungId", Name = "IDX_AUFTRAG_ERSTELLT")]
    //[Index("NKundeId", "DGeloescht", "NNiederlassungId", Name = "IDX_KUNDE")]
    //[Index("NProjektId", Name = "IDX_PROJEKT")]
    //[Index("NRahmenvertragId", Name = "IDX_RAHMENAUFTRAG")]
    //[Index("NYear", "NNiederlassungId", Name = "IDX_YEAR")]
    public partial class Auftrag
    {
        [Key]
        [Column("n_id")]
        public int NId { get; set; }
        [Column("c_nr")]
        [StringLength(15)]
        public string CNr { get; set; }
        [Column("c_nr_anfrage")]
        [StringLength(15)]
        public string CNrAnfrage { get; set; }
        /// <summary>
        /// kat_grp=7
        /// </summary>
        [Column("n_land_id")]
        public int? NLandId { get; set; }
        [Column("n_kunde_id")]
        public int NKundeId { get; set; }
        [Column("n_niederlassung_id")]
        public int? NNiederlassungId { get; set; }
        [Column("n_year")]
        public int NYear { get; set; }
        [Column("n_year_anfrage")]
        public int? NYearAnfrage { get; set; }
        [Column("n_year_nr_anfrage")]
        public int NYearNrAnfrage { get; set; }
        [Column("c_status")]
        [StringLength(15)]
        public string CStatus { get; set; }
        [Column("c_kunde_auftrags_nr")]
        [StringLength(50)]
        public string CKundeAuftragsNr { get; set; }
        [Column("c_type")]
        [StringLength(25)]
        public string CType { get; set; }
        /// <summary>
        /// eindeutige Nr. für die Auftrags-Nr. innerhalb eines Jahres
        /// unique no. for the order no. within a year
        /// </summary>
        [Column("n_year_nr")]
        public int NYearNr { get; set; }
        [Column("d_created", TypeName = "datetime")]
        public DateTime DCreated { get; set; }
        /// <summary>
        /// t_projekt.prj_id
        /// </summary>
        [Column("n_projekt_id")]
        public int? NProjektId { get; set; }
        [Column("d_geloescht", TypeName = "datetime")]
        public DateTime? DGeloescht { get; set; }
        /// <summary>
        /// 1=aktiv, 0=deaktiviert
        /// </summary>
        [Column("n_active")]
        public bool? NActive { get; set; }
        [Column("c_kunde_bestellnr")]
        [StringLength(35)]
        public string CKundeBestellnr { get; set; }
        [Column("d_kunde_bestelldatum")]
        public DateOnly? DKundeBestelldatum { get; set; }
        /// <summary>
        /// Prozentualer Rabatt für Verpackungen
        /// Percentage discount for packaging
        /// </summary>
        [Column("n_rabatt_verp")]
        public float? NRabattVerp { get; set; }
        /// <summary>
        /// Lieferdatum welches der Kunde vorgibt und beim Lieferschein und bei Posten vorbesetzt wird
        /// Delivery date which the customer specifies and is pre-assigned to the delivery note and items
        /// </summary>
        [Column("d_kunde_lieferdatum", TypeName = "datetime")]
        public DateTime? DKundeLieferdatum { get; set; }
        [Column("c_kunde_anfragenr")]
        [StringLength(25)]
        public string CKundeAnfragenr { get; set; }
        [Column("c_kunde_lieferscheinnr")]
        [StringLength(45)]
        public string CKundeLieferscheinnr { get; set; }
        [Column("d_kunde_anfragedatum")]
        public DateOnly? DKundeAnfragedatum { get; set; }
        /// <summary>
        /// Gesetzt wenn der Datensatz ein Auftrag ist
        /// Set if the record is an order
        /// </summary>
        [Column("d_auftrag_erstellt", TypeName = "datetime")]
        public DateTime? DAuftragErstellt { get; set; }
        [Column("c_liefer_termin")]
        [StringLength(45)]
        public string CLieferTermin { get; set; }
        [Column("c_besteller")]
        [StringLength(45)]
        public string CBesteller { get; set; }
        [Column("n_sachbearbeiter_id")]
        public int? NSachbearbeiterId { get; set; }
        [Column("c_anfrager")]
        [StringLength(45)]
        public string CAnfrager { get; set; }
        /// <summary>
        /// t_user.n_id Benutzer der den Datensatz erstellt hat
        /// t_user.n_id User who created the record
        /// </summary>
        [Column("n_user_id")]
        public int NUserId { get; set; }
        [Column("m_bemerkung", TypeName = "mediumtext")]
        public string MBemerkung { get; set; }
        [Column("m_bemerkung_intern", TypeName = "mediumtext")]
        public string MBemerkungIntern { get; set; }
        [Column("c_ref_nr_1")]
        [StringLength(25)]
        public string CRefNr1 { get; set; }
        [Column("c_ref_nr_2")]
        [StringLength(25)]
        public string CRefNr2 { get; set; }
        [Column("c_ref_nr_3")]
        [StringLength(25)]
        public string CRefNr3 { get; set; }
        [Column("c_ref_nr_4")]
        [StringLength(25)]
        public string CRefNr4 { get; set; }
        [Column("m_endempfaenger_adr", TypeName = "mediumtext")]
        public string MEndempfaengerAdr { get; set; }
        /// <summary>
        /// Datum, wann der Auftrag abgeschlossen wurde. Wird für externe ERP System benötigt
        /// Date when the order was completed. Required for external ERP system
        /// </summary>
        [Column("d_abgeschlossen", TypeName = "datetime")]
        public DateTime? DAbgeschlossen { get; set; }
        /// <summary>
        /// Benutzer, wer den Auftrag abgeschlossen. Wird für externe ERP System benötigt
        /// User who completed the job. Required for external ERP system
        /// </summary>
        [Column("n_abgeschlossen_durch")]
        public int? NAbgeschlossenDurch { get; set; }
        /// <summary>
        /// Kennzeichen für eine Exportsendung. Wird für externe ERP System benötigt
        /// License plate for an export shipment. Required for external ERP system
        /// </summary>
        [Column("n_extsys_export")]
        public bool? NExtsysExport { get; set; }
        [Column("c_extsys_sendungsnr")]
        [StringLength(20)]
        public string CExtsysSendungsnr { get; set; }
        /// <summary>
        /// Nr von externen ERP System
        /// No of external ERP system
        /// </summary>
        [Column("c_extsys_erp_nr")]
        [StringLength(45)]
        public string CExtsysErpNr { get; set; }
        /// <summary>
        /// 1= Kennzeichen, dass der Auftrag der Rahmenvertrag ist
        /// 1= Indicator that the order is the framework agreement
        /// </summary>
        [Column("n_is_rahmenvertrag")]
        public bool? NIsRahmenvertrag { get; set; }
        /// <summary>
        /// Referenz zum Rahmenauftrag t_auftrag.n_id. Gesetzt wenn das ein Abrufauftrag zum Rahmenauftrag ist. 
        /// Reference to blanket order t_auftrag.n_id. Set if this is a call order for a blanket order.
        /// </summary>
        [Column("n_rahmenvertrag_id")]
        public int? NRahmenvertragId { get; set; }
        /// <summary>
        /// Referenz auf t_firma_mailgruppe.n_id. Wenn ein Lieferschein eingescannt wird, wird dieser an diese Mailgruppe geschickt.
        /// Reference to t_firma_mailgruppe.n_id. When a delivery note is scanned, it is sent to this mail group.
        /// </summary>
        [Column("n_mailgruppe_versandbestaet_id")]
        public int? NMailgruppeVersandbestaetId { get; set; }
        /// <summary>
        /// A   Anfrage, AV  Anfrage Verpackung, VI  Verpackung intern, VE  Verpackung extern, S   Bestellung schriftlich, B   Bestellung mündlich, SH  Bestellung schriftlich Handelsware, BH  Bestellung mündlich Handelsware, ABR Abrufbestellung, LA  Fertigung auf Lager, EL  Einlagerung
        /// A request, AV request packaging, VI internal packaging, VE external packaging, S written order, B verbal order, SH written order for merchandise, BH verbal order for merchandise, ABR release order, LA production in stock, EL storage
        /// </summary>
        [Column("c_extsys_auftrags_art")]
        [StringLength(3)]
        [MySqlCharSet("utf8mb3")]
        [MySqlCollation("utf8_general_ci")]
        public string CExtsysAuftragsArt { get; set; }
        /// <summary>
        /// Vorbesetzung für neue Verpackungen
        /// Default for new packaging
        /// </summary>
        [Column("n_verp_verpackung_verschrauben")]
        public bool? NVerpVerpackungVerschrauben { get; set; }
        /// <summary>
        /// Ort der Verpackung
        /// place of packaging
        /// </summary>
        [Column("n_verp_baufeld_id")]
        public int? NVerpBaufeldId { get; set; }
        /// <summary>
        /// kat_grp=150
        /// </summary>
        [Column("n_kuerzel_id")]
        public int? NKuerzelId { get; set; }
    }
}