// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Pallet.BaseDatabase.Base;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// coordinates for robot
    /// </summary>
    [Table("t_robo_package_item_nailing_data")]
    public partial class NailingData
    {
        [Key]
        [Column("c_process_id")]
        [StringLength(45)]
        public  string CProcessId { get; set; }
        [Key]
        [Column("n_id")]
        public int NId { get; set; }
        [Column("n_x")]
        public int NX { get; set; }
        [Column("n_y")]
        public int NY { get; set; }
        [Column("n_z")]
        public int NZ { get; set; }
        /// <summary>
        /// order of nails
        /// </summary>
        [Column("n_order")]
        public int NOrder { get; set; }
        /// <summary>
        /// 0=shot without contact to wood, 1=contact with wood
        /// </summary>
        [Column("n_save_shot")]
        public bool NSaveShot { get; set; }
        /// <summary>
        /// define e.g. length of nail
        /// </summary>
        [Column("n_nail_type_id")]
        public int NNailTypeId { get; set; }
    }
}