// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Pallet.BaseDatabase.Base;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// The tasks which the robot has to process
    /// </summary>
    [Table("t_robo_task_item")]
    //[Index("CVerpId", Name = "IDX_VERP_ID")]
    public partial class RobotTaskItem
    {
        [Key]
        [Column("n_robo_id")]
        public int NRoboId { get; set; }
        /// <summary>
        /// t_verpackung.c_id
        /// </summary>
        [Key]
        [Column("c_verp_id")]
        [StringLength(45)]
        public string CVerpId { get; set; }
        [Key]
        [Column("n_id")]
        public  int NId { get; set; }
        [Column("c_layer_id")]
        [StringLength(15)]
        public string CLayerId { get; set; }
        /// <summary>
        /// 1=side/Seite, 2=lid/Deckel, 3=end/Kopf, 4=bottom/Boden
        /// </summary>
        [Column("n_part_id")]
        public int NPartId { get; set; }
        /// <summary>
        /// 1=created, 2=progress, 3=finished
        /// </summary>
        [Column("n_status")]
        public int? Status { get; set; }
        [Column("n_count")]
        public int Count { get; set; }
        [Column("n_count_done")]
        public int DoneCount { get; set; }
        [Column("d_build_planned", TypeName = "datetime")]
        public DateTime? PlannedDateTime { get; set; }
        [Column("d_build_done", TypeName = "datetime")]
        public DateTime? DoneDateTime { get; set; }
    }
}