// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Speichert die einzelnen Details der Kantholz, Brett, Plattenwerkstoff im 3D Raum
    /// </summary>
    [Table("t_3d_verpackung_details")]
    [Index("CId", Name = "IDX_3D_DETAILS_C_ID")]
    public partial class T3dVerpackungDetail
    {
        [Key]
        [Column("c_id")]
        [StringLength(45)]
        public string CId { get; set; }
        [Column("c_item_id")]
        [StringLength(45)]
        public string CItemId { get; set; }
        [Column("c_item_parent_id")]
        [StringLength(45)]
        public string CItemParentId { get; set; }
        [Key]
        [Column("n_id")]
        public long NId { get; set; }
        [Column("c_bez")]
        [StringLength(30)]
        public string CBez { get; set; }
        [Column("c_bez2")]
        [StringLength(30)]
        public string CBez2 { get; set; }
        /// <summary>
        /// Length
        /// </summary>
        [Column("n_laenge")]
        public int NLaenge { get; set; }
        /// <summary>
        /// Width
        /// </summary>
        [Column("n_breite")]
        public int NBreite { get; set; }
        [Column("n_breite_org")]
        public int? NBreiteOrg { get; set; }
        /// <summary>
        /// Height
        /// </summary>
        [Column("n_hoehe")]
        public int NHoehe { get; set; }
        /// <summary>
        /// kat_grp=6
        /// </summary>
        [Column("n_material_id")]
        public int NMaterialId { get; set; }
        /// <summary>
        /// for texture 1=Kantholz, Brett, Plattenwerkstoff, Diele, NutUndFeder, FallendeBreiten, Kloetze
        /// </summary>
        [Column("n_holz_typ")]
        public int NHolzTyp { get; set; }
        /// <summary>
        /// for texture
        /// </summary>
        [Column("n_holz_detail_typ")]
        public int NHolzDetailTyp { get; set; }
        [Column("n_keil_laenge")]
        public int? NKeilLaenge { get; set; }
        [Column("n_keil_rechts")]
        public bool? NKeilRechts { get; set; }
        [Column("n_visible")]
        public bool NVisible { get; set; }
        [Column("n_ende_angeschraegt")]
        public bool? NEndeAngeschraegt { get; set; }
        [Column("n_x")]
        public int NX { get; set; }
        [Column("n_y")]
        public int NY { get; set; }
        [Column("n_z")]
        public int NZ { get; set; }
        [Column("n_rotate_x")]
        public int NRotateX { get; set; }
        [Column("n_rotate_y")]
        public int NRotateY { get; set; }
        [Column("n_rotate_z")]
        public int NRotateZ { get; set; }
        [Column("n_texture_senkrecht")]
        public bool NTextureSenkrecht { get; set; }
        [Column("c_layer_id")]
        [StringLength(15)]
        public string CLayerId { get; set; }
        /// <summary>
        /// 1=side/Seite, 2=lid/Deckel, 3=end/Kopf, 4=bottom/Boden
        /// </summary>
        [Column("n_part_id_robo")]
        public int? NPartIdRobo { get; set; }
        [Column("c_layer_parent_id")]
        [StringLength(15)]
        public string CLayerParentId { get; set; }
    }
}