// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Hauptdatensatz für die 3D Darstellung der Verpackung
    /// </summary>
    [Table("t_3d_verpackung")]
    [Index("NVerpTypId", "NVerpId", Name = "IDX_3DV")]
    public partial class T3dVerpackung
    {
        [Key]
        [Column("c_id")]
        [StringLength(45)]
        public string CId { get; set; }
        [Column("c_verp_id")]
        [StringLength(45)]
        public string CVerpId { get; set; }
        /// <summary>
        /// t_katalog, kat_grp = 23, Teil des PK von t_verpackung, t_palette
        /// </summary>
        [Column("n_verp_typ_id")]
        public int NVerpTypId { get; set; }
        /// <summary>
        /// Teil des PK von t_verpackung, t_palette
        /// </summary>
        [Column("n_verp_id")]
        public long NVerpId { get; set; }
        [Column("n_parent_verp_typ_id")]
        public int NParentVerpTypId { get; set; }
        [Column("n_parent_verp_id")]
        public long NParentVerpId { get; set; }
        [Column("n_laenge")]
        /// <summary>
        /// Lenght
        /// </summary>
        public int NLaenge { get; set; }
        /// <summary>
        /// Width
        /// </summary>
        [Column("n_breite")]
        public int NBreite { get; set; }
        /// <summary>
        /// Height
        /// </summary>
        [Column("n_hoehe")]
        public int NHoehe { get; set; }
        [Column("n_x_pos")]
        public int NXPos { get; set; }
        [Column("n_y_pos")]
        public int NYPos { get; set; }
        [Column("n_z_pos")]
        public int NZPos { get; set; }
        [Column("n_laenge_gerundet")]
        public int NLaengeGerundet { get; set; }
        [Column("n_breite_gerundet")]
        public int NBreiteGerundet { get; set; }
        [Column("n_hoehe_gerundet")]
        public int NHoeheGerundet { get; set; }
        [Column("n_boden_hoehe")]
        public int NBodenHoehe { get; set; }
        /// <summary>
        /// bei LA Verp. &lt;&gt; 0
        /// </summary>
        [Column("n_seite1_offset")]
        public int? NSeite1Offset { get; set; }
        /// <summary>
        /// bei LA Verp. &lt;&gt; 0
        /// </summary>
        [Column("n_seite2_offset")]
        public int? NSeite2Offset { get; set; }
        /// <summary>
        /// Krananschlag links
        /// </summary>
        [Column("n_kran_anschlag_l")]
        public int? NKranAnschlagL { get; set; }
        /// <summary>
        /// Krananschlag rechts
        /// </summary>
        [Column("n_kran_anschlag_r")]
        public int? NKranAnschlagR { get; set; }
    }
}