// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Speichert die 3D Daten der Markierung oder Sonderzeichen einer Verpackung
    /// </summary>
    [Table("t_3d_verpackung_mark")]
    public partial class T3dVerpackungMark
    {
        [Key]
        [Column("c_id")]
        [StringLength(45)]
        public string CId { get; set; }
        [Key]
        [Column("n_id")]
        public long NId { get; set; }
        /// <summary>
        /// Verweis auf t_katalog.kat_grp=3, 1=Freitext, 3012=Schirm, 3001=Glas, 3000=Pfeile
        /// </summary>
        [Column("n_typ_id")]
        public int NTypId { get; set; }
        [Column("c_bez")]
        [StringLength(30)]
        public string CBez { get; set; }
        [Column("m_text", TypeName = "mediumtext")]
        public string MText { get; set; }
        [Column("n_visible")]
        public bool NVisible { get; set; }
        [Column("n_laenge")]
        public int NLaenge { get; set; }
        [Column("n_breite")]
        public int NBreite { get; set; }
        [Column("n_hoehe")]
        public int NHoehe { get; set; }
        [Column("n_x")]
        public int NX { get; set; }
        [Column("n_y")]
        public int NY { get; set; }
        [Column("n_z")]
        public int NZ { get; set; }
        [Column("n_rotate_x")]
        public int NRotateX { get; set; }
        [Column("n_rotate_y")]
        public int NRotateY { get; set; }
        [Column("n_rotate_z")]
        public int NRotateZ { get; set; }
        [Column("n_allign_horz")]
        public int? NAllignHorz { get; set; }
        [Column("n_allign_vert")]
        public int? NAllignVert { get; set; }
        [Column("c_layer_id")]
        [StringLength(15)]
        public string CLayerId { get; set; }
        [Column("c_layer_parent_id")]
        [StringLength(15)]
        public string CLayerParentId { get; set; }
    }
}