// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Tabelle wird für Worker und Statistik genutzt. Die interne Abteilung (Fertigung 1, Verpackung 5,...) wo sich die MA anmelden für die Zeiterfassung an-/abmelden und Pause.
    /// </summary>
    [Table("t_abteilung")]
    public partial class TAbteilung
    {
        [Key]
        [Column("n_id")]
        public int NId { get; set; }
        [Column("c_name")]
        [StringLength(45)]
        public string CName { get; set; }
        [Column("c_name_kurz")]
        [StringLength(15)]
        public string CNameKurz { get; set; }
    }
}