// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Die Liste der anzufragenden Lieferanten für die Anfrage
    /// </summary>
    [Table("t_anfrage_lieferanten")]
    public partial class TAnfrageLieferanten
    {
        /// <summary>
        /// Anfrage Id
        /// </summary>
        [Key]
        [Column("n_anfrage_id")]
        public int NAnfrageId { get; set; }
        [Key]
        [Column("n_lieferant_id")]
        public int NLieferantId { get; set; }
        [Column("c_mail_adressen")]
        [StringLength(255)]
        public string CMailAdressen { get; set; }
        [Column("c_mail_betreff")]
        [StringLength(45)]
        public string CMailBetreff { get; set; }
        [Column("m_mail_nachricht", TypeName = "mediumtext")]
        public string MMailNachricht { get; set; }
        [Column("d_gesendet", TypeName = "datetime")]
        public DateTime? DGesendet { get; set; }
    }
}