// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Mit Hilfe der Nr. wird die Anfrage-Nr. generiert und gespeichert
    /// </summary>
    [Table("t_anfrage_nr")]
    [Index("CAnfrageNr", Name = "IDX_U_ANFRAGE_NR", IsUnique = true)]
    public partial class TAnfrageNr
    {
        [Key]
        [Column("n_id")]
        public int NId { get; set; }
        [Column("n_year")]
        public int NYear { get; set; }
        [Column("n_year_nr")]
        public int NYearNr { get; set; }
        [Column("d_created", TypeName = "datetime")]
        public DateTime DCreated { get; set; }
        [Column("c_anfrage_nr")]
        [StringLength(20)]
        public string CAnfrageNr { get; set; }
    }
}