// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Sammelanfrage an Lieferanten. Z.B. Bestimmte Holzdimensionen bei x Lieferanten anfragen.
    /// </summary>
    [Table("t_anfrage")]
    public partial class TAnfrage
    {
        [Key]
        [Column("n_id")]
        public int NId { get; set; }
        [Column("c_anfrage_nr")]
        [StringLength(25)]
        public string CAnfrageNr { get; set; }
        [Column("d_anfrage_datum")]
        public DateOnly? DAnfrageDatum { get; set; }
        [Column("n_anfrage_user_id")]
        public int? NAnfrageUserId { get; set; }
        [Column("m_bem_intern", TypeName = "mediumtext")]
        public string MBemIntern { get; set; }
        [Column("m_bem", TypeName = "mediumtext")]
        public string MBem { get; set; }
        [Column("c_adr_firma")]
        [StringLength(50)]
        public string CAdrFirma { get; set; }
        [Column("c_adr_feld_1")]
        [StringLength(45)]
        public string CAdrFeld1 { get; set; }
        [Column("c_adr_feld_2")]
        [StringLength(45)]
        public string CAdrFeld2 { get; set; }
        [Column("c_adr_plz_ort")]
        [StringLength(45)]
        public string CAdrPlzOrt { get; set; }
        [Column("c_adr_lief_firma")]
        [StringLength(50)]
        public string CAdrLiefFirma { get; set; }
        [Column("c_adr_lief_feld_1")]
        [StringLength(45)]
        public string CAdrLiefFeld1 { get; set; }
        [Column("c_adr_lief_feld_2")]
        [StringLength(45)]
        public string CAdrLiefFeld2 { get; set; }
        [Column("c_adr_lief_plz_ort")]
        [StringLength(45)]
        public string CAdrLiefPlzOrt { get; set; }
        [Column("n_andere_lief_anschrift")]
        public sbyte? NAndereLiefAnschrift { get; set; }
        [Column("d_geloescht", TypeName = "datetime")]
        public DateTime? DGeloescht { get; set; }
        [Column("n_zahlungsziel_id")]
        public int? NZahlungszielId { get; set; }
        [Column("n_skonto")]
        [Precision(5, 2)]
        public decimal? NSkonto { get; set; }
        [Column("n_skonto_zahlbar_tage")]
        public int? NSkontoZahlbarTage { get; set; }
        [Column("n_netto_zahlbar_tage")]
        public int? NNettoZahlbarTage { get; set; }
        [Column("n_versandbedingungen_id")]
        public int? NVersandbedingungenId { get; set; }
        [Column("n_versandart_id")]
        public int? NVersandartId { get; set; }
        [Column("d_created", TypeName = "datetime")]
        public DateTime DCreated { get; set; }
        [Column("d_lastmodified", TypeName = "timestamp")]
        public DateTime DLastmodified { get; set; }
    }
}