// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Listenkonfiguration der Ansprechpartner in Abhängigkeit des Cratemaker-Benutzers
    /// </summary>
    [Table("t_ansprechpartner_listen")]
    [Index("NUserId", Name = "IDX_ANP_USER")]
    public partial class TAnsprechpartnerListen
    {
        [Key]
        [Column("n_id")]
        public int NId { get; set; }
        /// <summary>
        /// Wenn NULL ist es eine öffentliche Liste, sonst t_user.n_id
        /// </summary>
        [Column("n_user_id")]
        public int? NUserId { get; set; }
        [Column("c_name")]
        [StringLength(45)]
        public string CName { get; set; }
        [Column("m_bemerkung", TypeName = "mediumtext")]
        public string MBemerkung { get; set; }
        [Column("d_created", TypeName = "datetime")]
        public DateTime DCreated { get; set; }
        [Column("d_deleted", TypeName = "datetime")]
        public DateTime? DDeleted { get; set; }
    }
}