// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// logging when the user interact with the app. we have to known who, when made what
    /// </summary>
    [Table("t_app_process_check_log")]
    public partial class TAppProcessCheckLog
    {
        [Key]
        [Column("c_id")]
        [StringLength(45)]
        public string CId { get; set; }
        [Required]
        [Column("c_process_id")]
        [StringLength(45)]
        public string CProcessId { get; set; }
        [Column("c_process_item_id")]
        [StringLength(45)]
        public string CProcessItemId { get; set; }
        /// <summary>
        /// running, pause, finish
        /// </summary>
        [Required]
        [Column("c_process_state")]
        [StringLength(15)]
        public string CProcessState { get; set; }
        [Required]
        [Column("c_device_id")]
        [StringLength(50)]
        public string CDeviceId { get; set; }
        [Column("d_created", TypeName = "datetime")]
        public DateTime DCreated { get; set; }
    }
}