// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Dient zur Kommunikation zwischen den Anwendungen mit Parametern.
    /// </summary>
    [Table("t_app_comm")]
    public partial class TAppComm
    {
        [Key]
        [Column("n_user_id")]
        public int NUserId { get; set; }
        [Key]
        [Column("c_app")]
        [StringLength(25)]
        public string CApp { get; set; }
        [Column("d_created", TypeName = "timestamp")]
        public DateTime DCreated { get; set; }
        [Column("c_id_1")]
        [StringLength(45)]
        public string CId1 { get; set; }
        [Column("c_id_2")]
        [StringLength(45)]
        public string CId2 { get; set; }
        [Column("c_id_3")]
        [StringLength(45)]
        public string CId3 { get; set; }
        /// <summary>
        /// message id der aufrufenden Anwendung
        /// </summary>
        [Column("n_msg_id")]
        public int? NMsgId { get; set; }
        [Column("m_text_1", TypeName = "mediumtext")]
        public string MText1 { get; set; }
    }
}