// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    [Table("t_app_aufmass_main")]
    public partial class TAppAufmassMain
    {
        [Key]
        [Column("n_id")]
        public long NId { get; set; }
        [Column("n_auftrag_id")]
        public long? NAuftragId { get; set; }
        [Column("c_company")]
        [StringLength(45)]
        public string CCompany { get; set; }
        [Column("c_contact")]
        [StringLength(45)]
        public string CContact { get; set; }
        [Column("c_phone")]
        [StringLength(45)]
        public string CPhone { get; set; }
        [Column("c_country")]
        [StringLength(45)]
        public string CCountry { get; set; }
        [Column("c_commission")]
        [StringLength(30)]
        public string CCommission { get; set; }
        [Column("d_start", TypeName = "datetime")]
        public DateTime? DStart { get; set; }
        [Column("d_end", TypeName = "datetime")]
        public DateTime? DEnd { get; set; }
        /// <summary>
        /// 0=none, pallet, box, crate, carriage, kako
        /// </summary>
        [Column("n_package_type")]
        public int? NPackageType { get; set; }
        /// <summary>
        /// 0=none, air, sea, rail, road
        /// </summary>
        [Column("n_delivery_type")]
        public int? NDeliveryType { get; set; }
        /// <summary>
        /// 0=none, pe, al, sf, vci
        /// </summary>
        [Column("n_corrosion_type")]
        public int? NCorrosionType { get; set; }
        [Column("n_corrosion_days")]
        public int? NCorrosionDays { get; set; }
        [Column("n_corrosion_indicator")]
        public bool? NCorrosionIndicator { get; set; }
        [Column("m_comment", TypeName = "mediumtext")]
        public string MComment { get; set; }
        [Column("d_created", TypeName = "datetime")]
        public DateTime? DCreated { get; set; }
        [Column("d_imported", TypeName = "datetime")]
        public DateTime DImported { get; set; }
    }
}