// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Speicehrt alle  Artikel die eingekauft und verkauft werden.
    /// </summary>
    [Table("t_artikel")]
    [Index("NBeipack", Name = "IDX_ARTIKEL_BEIPACK")]
    [Index("NKalkTypId", Name = "IDX_ARTIKEL_KALK_TYP")]
    [Index("CName", Name = "idx_c_name")]
    public partial class TArtikel
    {
        [Key]
        [Column("n_id")]
        public int NId { get; set; }
        /// <summary>
        /// 1=Artikel 2=Holz 3=Nagel
        /// </summary>
        [Column("n_typ_id")]
        public int? NTypId { get; set; }
        [Column("c_name")]
        [StringLength(150)]
        public string CName { get; set; }
        [Column("c_name_verkauf")]
        [StringLength(150)]
        public string CNameVerkauf { get; set; }
        [Column("m_bemerkung", TypeName = "mediumtext")]
        public string MBemerkung { get; set; }
        [Column("m_bemerkung_intern", TypeName = "mediumtext")]
        public string MBemerkungIntern { get; set; }
        /// <summary>
        /// Länge des Artikels
        /// </summary>
        [Column("n_laenge")]
        public float? NLaenge { get; set; }
        /// <summary>
        /// Länge des Artikel, wenn dieser nicht zusammen gebaut ist
        /// </summary>
        [Column("n_laenge_bausatz")]
        public ushort? NLaengeBausatz { get; set; }
        [Column("n_breite")]
        public float? NBreite { get; set; }
        /// <summary>
        /// Breite des Artikel, wenn dieser nicht zusammen gebaut ist
        /// </summary>
        [Column("n_breite_bausatz")]
        public ushort? NBreiteBausatz { get; set; }
        [Column("n_hoehe")]
        public float? NHoehe { get; set; }
        /// <summary>
        /// Höhe des Artikel, wenn dieser nicht zusammen gebaut ist
        /// </summary>
        [Column("n_hoehe_bausatz")]
        public ushort? NHoeheBausatz { get; set; }
        /// <summary>
        /// zusammen genagelt
        /// </summary>
        [Column("n_zn")]
        public bool? NZn { get; set; }
        /// <summary>
        /// kat_grp=10
        /// </summary>
        [Column("n_holz_typ_id")]
        public ushort? NHolzTypId { get; set; }
        [Column("n_gewicht_tara")]
        public uint? NGewichtTara { get; set; }
        [Column("n_gewicht")]
        public float? NGewicht { get; set; }
        [Column("n_durchmesser")]
        public float? NDurchmesser { get; set; }
        [Column("c_zolltarif_nr")]
        [StringLength(100)]
        public string CZolltarifNr { get; set; }
        /// <summary>
        /// kat_grp=27
        /// </summary>
        [Column("n_holztyp_id")]
        public int? NHolztypId1 { get; set; }
        /// <summary>
        /// kat_grp=6
        /// </summary>
        [Column("n_holzmaterial_id")]
        public int? NHolzmaterialId { get; set; }
        /// <summary>
        /// kat_grp=5
        /// </summary>
        [Column("n_behandlungsart_id")]
        public int NBehandlungsartId { get; set; }
        /// <summary>
        /// kat_grp=26
        /// </summary>
        [Column("n_nagelsorte_id")]
        public int? NNagelsorteId { get; set; }
        [Column("d_geloescht", TypeName = "datetime")]
        public DateTime? DGeloescht { get; set; }
        [Column("d_lastmodified", TypeName = "timestamp")]
        public DateTime DLastmodified { get; set; }
        [Column("c_artikel_nr")]
        [StringLength(50)]
        public string CArtikelNr { get; set; }
        /// <summary>
        /// 1=steht in der Artikelauswahl in der Auftragsverwaltung zur Verfügung
        /// </summary>
        [Column("n_intern")]
        public bool? NIntern { get; set; }
        /// <summary>
        /// 1=Wird im Beiblatt der Verpackung zur Auswahl zur Verfügung gestellt
        /// </summary>
        [Column("n_beipack")]
        public bool? NBeipack { get; set; }
        /// <summary>
        /// Handelsware wird im WE in Lager gebucht
        /// </summary>
        [Column("n_handelsware")]
        public bool? NHandelsware { get; set; }
        /// <summary>
        /// kat_grp=11
        /// </summary>
        [Column("n_einheit_id")]
        public int? NEinheitId { get; set; }
        /// <summary>
        /// kat_grp=71
        /// </summary>
        [Column("n_kalk_typ_id")]
        public int? NKalkTypId { get; set; }
        /// <summary>
        /// Verakufspreis
        /// </summary>
        [Column("n_preis")]
        public float? NPreis { get; set; }
        /// <summary>
        /// Zuschlag bei der Kalkulation, wenn der Artikel im Beibaltt ausgewählt wurde
        /// </summary>
        [Column("n_schnellkal_einmal_zuschlag")]
        public float? NSchnellkalEinmalZuschlag { get; set; }
        /// <summary>
        /// Artikel Kategorie t_artikel_kategorie, dient als Filter
        /// </summary>
        [Column("n_kategorie_id")]
        public int? NKategorieId { get; set; }
        /// <summary>
        /// Unterkategorie t_artikel_kategorie, dient als Filter
        /// </summary>
        [Column("n_kategorie_sub_id")]
        public int? NKategorieSubId { get; set; }
        /// <summary>
        /// kat_grp=61
        /// </summary>
        [Column("n_sub_typ_id")]
        public int? NSubTypId { get; set; }
        [Column("c_chargen_prefix")]
        [StringLength(2)]
        public string CChargenPrefix { get; set; }
        /// <summary>
        /// Wenn der gesetzt ist, wird dieser Preis bei der Feinkalkulation genutzt und nicht der Lieferantenpreis.
        /// </summary>
        [Column("n_ek_calc_preis")]
        public float? NEkCalcPreis { get; set; }
        /// <summary>
        /// t_kostenstelle
        /// </summary>
        [Column("n_kostenstelle_id")]
        public int? NKostenstelleId { get; set; }
    }
}