// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Verküpfung einer Artikels mit einem Lieferanten.
    /// </summary>
    [Table("t_artikellieferant")]
    [Index("NArtikelId", Name = "idx_n_artikel_id")]
    [Index("NLieferantenId", Name = "idx_n_lieferanten_id")]
    public partial class TArtikellieferant
    {
        [Key]
        [Column("n_id")]
        public int NId { get; set; }
        /// <summary>
        /// t_artikel.n_id
        /// </summary>
        [Column("n_artikel_id")]
        public int? NArtikelId { get; set; }
        /// <summary>
        /// t_firma.firmakey
        /// </summary>
        [Column("n_lieferanten_id")]
        public int? NLieferantenId { get; set; }
        [Column("c_lieferanten_best_nr")]
        [StringLength(100)]
        public string CLieferantenBestNr { get; set; }
        [Column("c_l_artikel_name")]
        [StringLength(150)]
        public string CLArtikelName { get; set; }
        /// <summary>
        /// Einkaufspreis bzw. Verkaufspreis vom Lieferanten
        /// </summary>
        [Column("n_preis")]
        public float? NPreis { get; set; }
        /// <summary>
        /// kat_grp = 25
        /// </summary>
        [Column("n_waehrung_id")]
        public int? NWaehrungId { get; set; }
        /// <summary>
        /// kat_grp=11
        /// </summary>
        [Column("n_einheit")]
        public int? NEinheit { get; set; }
        [Column("n_netto_gewicht")]
        public float? NNettoGewicht { get; set; }
        [Column("n_lieferzeit")]
        public int? NLieferzeit { get; set; }
        [Column("n_lieferzeit_einheit")]
        public int? NLieferzeitEinheit { get; set; }
        [Column("c_bem_intern", TypeName = "mediumtext")]
        public string CBemIntern { get; set; }
        [Column("c_bem_extern", TypeName = "mediumtext")]
        public string CBemExtern { get; set; }
        [Column("d_gueltig_von")]
        public DateOnly? DGueltigVon { get; set; }
        [Column("d_geloescht", TypeName = "datetime")]
        public DateTime? DGeloescht { get; set; }
        /// <summary>
        /// obsolete
        /// </summary>
        [Column("n_verkaufs_preis")]
        public float? NVerkaufsPreis { get; set; }
        /// <summary>
        /// Umrechnung von Lierfereinheit auf Lagereinheit
        /// </summary>
        [Column("n_lager_liefer_faktor")]
        [Precision(10, 3)]
        public decimal? NLagerLieferFaktor { get; set; }
        [Column("n_liefermenge_unbekannt")]
        public bool? NLiefermengeUnbekannt { get; set; }
        [Column("n_deaktiviert")]
        public bool? NDeaktiviert { get; set; }
    }
}