// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Kategorie und Unterkategorie um Artikel zu filtern
    /// </summary>
    [Table("t_artikel_kategorie")]
    [Index("NParentId", "DDeleted", Name = "IDX_KAT_PARENT")]
    public partial class TArtikelKategorie
    {
        [Key]
        [Column("n_id")]
        public int NId { get; set; }
        [Column("c_name")]
        [StringLength(45)]
        public string CName { get; set; }
        /// <summary>
        /// Gesetzt mit der t_artikel_kategorie.n_id und kennzeichnet somit eine Unterkategorie
        /// </summary>
        [Column("n_parent_id")]
        public int? NParentId { get; set; }
        [Column("d_deleted", TypeName = "datetime")]
        public DateTime? DDeleted { get; set; }
    }
}