// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Prtokoll wann der Status durch welchen Benutzer wann gesetzt wird. Alles Sonstigen Posten außer Holzprodukt.
    /// </summary>
    [Table("t_auftrag_posten_zeiten")]
    public partial class TAuftragPostenZeiten
    {
        /// <summary>
        /// kat_grp=61
        /// </summary>
        [Key]
        [Column("n_typ_id")]
        public uint NTypId { get; set; }
        /// <summary>
        /// AuftragId, VerpTypId
        /// </summary>
        [Key]
        [Column("n_main_id")]
        public uint NMainId { get; set; }
        /// <summary>
        /// PostenId, VerpId
        /// </summary>
        [Key]
        [Column("n_id")]
        public uint NId { get; set; }
        /// <summary>
        /// kat_grp=81
        /// </summary>
        [Key]
        [Column("n_status")]
        public int NStatus { get; set; }
        [Column("d_datetime", TypeName = "datetime")]
        public DateTime DDatetime { get; set; }
        [Column("n_user_id")]
        public int NUserId { get; set; }
    }
}