// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Termine eines Auftragsposten t_auftrag_posten_sonstige
    /// </summary>
    [Table("t_auftrag_posten_sonstige_termine")]
    public partial class TAuftragPostenSonstigeTermine
    {
        [Key]
        [Column("c_event_id")]
        [StringLength(45)]
        public string CEventId { get; set; }
        [Column("n_auftrag_id")]
        public int NAuftragId { get; set; }
        [Column("n_id")]
        public int NId { get; set; }
    }
}