// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// App schreibt Anzahl auszulagernde Artikel
    /// </summary>
    [Table("t_auslagerung_kunde_artikel_p_app_interface")]
    [Index("NWepArtikelId", Name = "IDX_WARENEINGANG_VERP_ID")]
    [Index("NWepId", Name = "IDX_WEP_ID")]
    public partial class TAuslagerungKundeArtikelPAppInterface
    {
        [Key]
        [Column("n_id")]
        public long NId { get; set; }
        [Column("c_process_id")]
        [StringLength(45)]
        public string CProcessId { get; set; }
        /// <summary>
        /// t_wareneingangpackstueck.n_id
        /// </summary>
        [Column("n_wep_id")]
        public int NWepId { get; set; }
        /// <summary>
        /// t_wareneingangartikel.n_id
        /// </summary>
        [Column("n_wep_artikel_id")]
        public int NWepArtikelId { get; set; }
        [Column("n_anzahl")]
        public float NAnzahl { get; set; }
    }
}