// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Ausgelagerte Positionen zur t_auslagerung_kunde_artikel, wenn Packstück ausgelagert wird
    /// </summary>
    [Table("t_auslagerung_kunde_artikel_p_durch_packstueck")]
    [Index("NMainAuslPackstueckId", Name = "IDX_MAIN_ID")]
    [Index("NWepArtikelId", Name = "IDX_WARENEINGANG_VERP_ID")]
    public partial class TAuslagerungKundeArtikelPDurchPackstueck
    {
        /// <summary>
        ///  t_auslagerungartikel.n_id
        /// </summary>
        [Key]
        [Column("n_main_ausl_packstueck_id")]
        public int NMainAuslPackstueckId { get; set; }
        /// <summary>
        /// t_wareneingangpackstueck.n_id
        /// </summary>
        [Column("n_wep_id")]
        public int NWepId { get; set; }
        /// <summary>
        /// t_wareneingangartikel.n_id
        /// </summary>
        [Key]
        [Column("n_wep_artikel_id")]
        public int NWepArtikelId { get; set; }
        [Column("n_anzahl")]
        public float NAnzahl { get; set; }
        [Column("n_lager_id")]
        public int NLagerId { get; set; }
        [Column("n_lagerort_id")]
        public int NLagerortId { get; set; }
    }
}