// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Exportierte Datei der Rechnung
    /// </summary>
    [Table("t_ausgang_rechausgang_file")]
    public partial class TAusgangRechausgangFile
    {
        [Key]
        [Column("n_id")]
        public long NId { get; set; }
        [Column("b_data")]
        public byte[] BData { get; set; }
    }
}