// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Protokoll welche Gutschrfiten wann exportiert bzw. übermittelt wurde
    /// </summary>
    [Table("t_ausgang_gutschriftausgang")]
    public partial class TAusgangGutschriftausgang
    {
        [Key]
        [Column("n_id")]
        public long NId { get; set; }
        /// <summary>
        /// t_gutschrift.n_id
        /// </summary>
        [Column("n_ref_id")]
        public long NRefId { get; set; }
        [Column("d_erstellt", TypeName = "datetime")]
        public DateTime DErstellt { get; set; }
        /// <summary>
        /// Datum wann die Gutschrift exportiert wurde
        /// </summary>
        [Column("d_gesendet", TypeName = "datetime")]
        public DateTime? DGesendet { get; set; }
        [Column("c_filename")]
        [StringLength(50)]
        public string CFilename { get; set; }
    }
}