// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    [Table("t_auslagerung_kunde_artikel_nr")]
    public partial class TAuslagerungKundeArtikelNr
    {
        [Key]
        [Column("n_year")]
        public int NYear { get; set; }
        [Key]
        [Column("n_id")]
        public int NId { get; set; }
        [Column("d_created", TypeName = "datetime")]
        public DateTime DCreated { get; set; }
        [Column("c_nr")]
        [StringLength(20)]
        public string CNr { get; set; }
    }
}