// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Beipackholz zum Artikel
    /// </summary>
    [Table("t_beipack_holz_artikel")]
    public partial class TBeipackHolzArtikel
    {
        [Key]
        [Column("n_artikel_id")]
        public int NArtikelId { get; set; }
        [Key]
        [Column("n_id")]
        public int NId { get; set; }
        [Column("n_pos")]
        public ushort? NPos { get; set; }
        [Column("n_anzahl")]
        public ushort NAnzahl { get; set; }
        [Column("n_laenge")]
        public ushort NLaenge { get; set; }
        [Column("n_breite")]
        public ushort NBreite { get; set; }
        [Column("n_hoehe")]
        public ushort NHoehe { get; set; }
        [Column("c_dim")]
        [StringLength(10)]
        public string CDim { get; set; }
        [Column("n_gewicht")]
        public float NGewicht { get; set; }
        [Column("c_material")]
        [StringLength(25)]
        public string CMaterial { get; set; }
        /// <summary>
        /// kat_grp=1
        /// </summary>
        [Column("n_material_id")]
        public int NMaterialId { get; set; }
        [Column("c_bezeichnung")]
        [StringLength(50)]
        public string CBezeichnung { get; set; }
        /// <summary>
        /// Konstruktionshoelzer wird anders bewertet
        /// </summary>
        [Column("n_konstruktionsholz")]
        public bool NKonstruktionsholz { get; set; }
        [Column("c_montage_anweisung")]
        [StringLength(150)]
        public string CMontageAnweisung { get; set; }
    }
}