// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Kopfdaten einer Bestellung von Artikeln wie Kanthölzer, Nägel, etc.
    /// </summary>
    [Table("t_bestellung")]
    public partial class TBestellung
    {
        [Key]
        [Column("n_id")]
        public int NId { get; set; }
        [Column("n_lieferant_id")]
        public int NLieferantId { get; set; }
        [Column("c_bestell_nr")]
        [StringLength(25)]
        public string CBestellNr { get; set; }
        [Column("c_anfrage_nr")]
        [StringLength(25)]
        public string CAnfrageNr { get; set; }
        [Column("d_bestell_datum")]
        public DateOnly DBestellDatum { get; set; }
        [Column("d_anfrage_datum")]
        public DateOnly? DAnfrageDatum { get; set; }
        [Column("m_bem_intern", TypeName = "mediumtext")]
        public string MBemIntern { get; set; }
        [Column("m_bem_bestell", TypeName = "mediumtext")]
        public string MBemBestell { get; set; }
        [Column("c_angebot_nr")]
        [StringLength(100)]
        public string CAngebotNr { get; set; }
        [Column("d_angebot_vom")]
        public DateOnly? DAngebotVom { get; set; }
        /// <summary>
        /// kat_grp=15
        /// </summary>
        [Column("n_status_id")]
        public int NStatusId { get; set; }
        [Column("c_adr_firma")]
        [StringLength(50)]
        public string CAdrFirma { get; set; }
        [Column("c_adr_feld_1")]
        [StringLength(45)]
        public string CAdrFeld1 { get; set; }
        [Column("c_adr_feld_2")]
        [StringLength(45)]
        public string CAdrFeld2 { get; set; }
        [Column("c_adr_plz_ort")]
        [StringLength(45)]
        public string CAdrPlzOrt { get; set; }
        [Column("c_adr_lief_firma")]
        [StringLength(50)]
        public string CAdrLiefFirma { get; set; }
        [Column("c_adr_lief_feld_1")]
        [StringLength(45)]
        public string CAdrLiefFeld1 { get; set; }
        [Column("c_adr_lief_feld_2")]
        [StringLength(45)]
        public string CAdrLiefFeld2 { get; set; }
        [Column("c_adr_lief_plz_ort")]
        [StringLength(45)]
        public string CAdrLiefPlzOrt { get; set; }
        [Column("d_geloescht", TypeName = "datetime")]
        public DateTime? DGeloescht { get; set; }
        [Column("n_user_id")]
        public int? NUserId { get; set; }
        [Column("n_anfrage_user_id")]
        public int? NAnfrageUserId { get; set; }
        /// <summary>
        /// kat_grp=16
        /// </summary>
        [Column("n_zahlungsziel_id")]
        public int? NZahlungszielId { get; set; }
        [Column("n_skonto")]
        [Precision(5, 2)]
        public decimal? NSkonto { get; set; }
        [Column("n_skonto_zahlbar_tage")]
        public int? NSkontoZahlbarTage { get; set; }
        [Column("n_netto_zahlbar_tage")]
        public int? NNettoZahlbarTage { get; set; }
        [Column("m_zahlungs_bemerkung", TypeName = "mediumtext")]
        public string MZahlungsBemerkung { get; set; }
        [Column("n_versandbedingungen_id")]
        public int? NVersandbedingungenId { get; set; }
        /// <summary>
        /// kat_grp=18
        /// </summary>
        [Column("n_versandart_id")]
        public int? NVersandartId { get; set; }
        [Column("c_ansprechpartner")]
        [StringLength(40)]
        public string CAnsprechpartner { get; set; }
        [Column("c_referenznr")]
        [StringLength(40)]
        public string CReferenznr { get; set; }
        [Column("d_created", TypeName = "datetime")]
        public DateTime DCreated { get; set; }
        [Column("n_kunde_id")]
        public int NKundeId { get; set; }
        [Column("d_lastmodified", TypeName = "timestamp")]
        public DateTime DLastmodified { get; set; }
        [Column("n_andere_lief_anschrift")]
        public bool NAndereLiefAnschrift { get; set; }
        [Column("n_auftrag_id_ref")]
        public int? NAuftragIdRef { get; set; }
        [Column("n_kunde_id_ref")]
        public int? NKundeIdRef { get; set; }
        [Column("n_gesamt_betrag_verhandelt")]
        [Precision(15, 4)]
        public decimal? NGesamtBetragVerhandelt { get; set; }
        [Column("n_mit_gesamtsumme")]
        public bool? NMitGesamtsumme { get; set; }
        [Column("n_nur_gesamtsumme")]
        public bool? NNurGesamtsumme { get; set; }
    }
}