// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    [Table("t_bestellungartikel")]
    [Index("NArtikelId", Name = "idx_n_artikel_lieferant_id")]
    [Index("NBestellungId", Name = "idx_n_bestellung_id")]
    public partial class TBestellungartikel
    {
        [Key]
        [Column("n_id")]
        public int NId { get; set; }
        [Key]
        [Column("n_bestellung_id")]
        public int NBestellungId { get; set; }
        [Column("n_artikel_id")]
        public int? NArtikelId { get; set; }
        [Column("c_artikel_name")]
        [StringLength(150)]
        public string CArtikelName { get; set; }
        [Column("c_artikel_nr")]
        [StringLength(100)]
        public string CArtikelNr { get; set; }
        [Column("n_anzahl")]
        [Precision(15, 4)]
        public decimal? NAnzahl { get; set; }
        [Column("n_liefermenge_unbekannt")]
        public bool? NLiefermengeUnbekannt { get; set; }
        [Column("n_einheit_id")]
        public int? NEinheitId { get; set; }
        [Column("n_preis")]
        [Precision(15, 4)]
        public decimal NPreis { get; set; }
        [Column("n_waehrung_id")]
        public int? NWaehrungId { get; set; }
        [Column("n_preis_einheit_id")]
        public int NPreisEinheitId { get; set; }
        [Column("c_liefertermin_prefix")]
        [StringLength(10)]
        public string CLieferterminPrefix { get; set; }
        [Column("d_liefertermin")]
        public DateOnly? DLiefertermin { get; set; }
        [Column("n_liefereinheit_id")]
        public int? NLiefereinheitId { get; set; }
        [Column("n_liefereinheit_anzahl")]
        [Precision(15, 4)]
        public decimal? NLiefereinheitAnzahl { get; set; }
        [Column("m_bem_intern", TypeName = "mediumtext")]
        public string MBemIntern { get; set; }
        [Column("m_bem_bestell", TypeName = "mediumtext")]
        public string MBemBestell { get; set; }
        [Column("c_kommissions_nr")]
        [StringLength(100)]
        public string CKommissionsNr { get; set; }
        [Column("n_label_druck")]
        public sbyte? NLabelDruck { get; set; }
        [Column("n_label_anzahl")]
        public sbyte? NLabelAnzahl { get; set; }
        [Column("c_barcode")]
        [StringLength(25)]
        public string CBarcode { get; set; }
        [Column("d_created", TypeName = "datetime")]
        public DateTime DCreated { get; set; }
    }
}