// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    [Table("t_capi_fuel_event")]
    [Index("Uuid", Name = "uuid", IsUnique = true)]
    public partial class TCapiFuelEvent
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [Column("uuid")]
        public string Uuid { get; set; }
        [Required]
        [Column("device_id")]
        [StringLength(50)]
        public string DeviceId { get; set; }
        [Column("pump_id")]
        public int PumpId { get; set; }
        [Column("vehicle_id")]
        public int VehicleId { get; set; }
        [Column("amount")]
        public int Amount { get; set; }
        [Column("created", TypeName = "timestamp")]
        public DateTime Created { get; set; }
    }
}