// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    [Table("t_chargen_nr")]
    public partial class TChargenNr
    {
        [Key]
        [Column("c_chargen_prefix")]
        [StringLength(2)]
        public string CChargenPrefix { get; set; }
        [Key]
        [Column("n_id")]
        public int NId { get; set; }
        [Column("d_created", TypeName = "datetime")]
        public DateTime? DCreated { get; set; }
    }
}