// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Kopfdaten der Colliliste
    /// </summary>
    [Table("t_colliliste")]
    public partial class TColliliste
    {
        [Key]
        [Column("n_id")]
        public int NId { get; set; }
        [Column("n_kunde_id")]
        public int NKundeId { get; set; }
        [Column("c_nr")]
        [StringLength(20)]
        public string CNr { get; set; }
        [Column("c_adr_firma")]
        [StringLength(50)]
        public string CAdrFirma { get; set; }
        [Column("c_adr_feld_1")]
        [StringLength(45)]
        public string CAdrFeld1 { get; set; }
        [Column("c_adr_feld_2")]
        [StringLength(45)]
        public string CAdrFeld2 { get; set; }
        [Column("c_adr_plz_ort")]
        [StringLength(45)]
        public string CAdrPlzOrt { get; set; }
        [Column("c_adr_zu_haenden")]
        [StringLength(40)]
        public string CAdrZuHaenden { get; set; }
        [Column("d_datum")]
        public DateOnly? DDatum { get; set; }
        [Column("c_adr_lief_firma")]
        [StringLength(45)]
        public string CAdrLiefFirma { get; set; }
        [Column("c_adr_lief_feld_1")]
        [StringLength(45)]
        public string CAdrLiefFeld1 { get; set; }
        [Column("c_adr_lief_feld_2")]
        [StringLength(45)]
        public string CAdrLiefFeld2 { get; set; }
        [Column("n_andere_lief_anschrift")]
        public bool NAndereLiefAnschrift { get; set; }
        [Column("c_adr_lief_plz_ort")]
        [StringLength(45)]
        public string CAdrLiefPlzOrt { get; set; }
        [Column("m_bemerkung", TypeName = "mediumtext")]
        public string MBemerkung { get; set; }
        /// <summary>
        /// Zeit wann Dokument gedruckt wurde
        /// </summary>
        [Column("d_gedruckt", TypeName = "datetime")]
        public DateTime? DGedruckt { get; set; }
        [Column("c_ref_container_nr")]
        [StringLength(25)]
        public string CRefContainerNr { get; set; }
        [Column("c_ref_container_typ")]
        [StringLength(25)]
        public string CRefContainerTyp { get; set; }
        [Column("c_ref_container_tuersiegel")]
        [StringLength(25)]
        public string CRefContainerTuersiegel { get; set; }
        [Column("c_ref_container_dachsiegel")]
        [StringLength(25)]
        public string CRefContainerDachsiegel { get; set; }
        [Column("n_ref_container_tara")]
        public int? NRefContainerTara { get; set; }
        [Column("n_ref_container_stauholz")]
        public int? NRefContainerStauholz { get; set; }
        [Column("n_ref_container_zurrgewicht")]
        public int? NRefContainerZurrgewicht { get; set; }
        [Column("n_ref_auftrag_id")]
        public int? NRefAuftragId { get; set; }
        [Column("n_ref_auftrag_freie_eingabe")]
        public bool? NRefAuftragFreieEingabe { get; set; }
        [Column("c_ref_auftrag_nr")]
        [StringLength(45)]
        public string CRefAuftragNr { get; set; }
        [Column("c_ref_auftrag_k_auftrag_nr")]
        [StringLength(45)]
        public string CRefAuftragKAuftragNr { get; set; }
        [Column("c_ref_auftrag_k_bestell_nr")]
        [StringLength(45)]
        public string CRefAuftragKBestellNr { get; set; }
        /// <summary>
        /// 1=IPPC, 2=NONWOOD, 3=kein IPPC
        /// </summary>
        [Column("n_ref_auftrag_holzart")]
        public int? NRefAuftragHolzart { get; set; }
        [Column("d_created", TypeName = "datetime")]
        public DateTime? DCreated { get; set; }
        [Column("n_user_id")]
        public int? NUserId { get; set; }
        /// <summary>
        /// ID des Benutzers der den Datensatz erstellt hat.
        /// </summary>
        [Column("n_user_id_erstellt")]
        public int? NUserIdErstellt { get; set; }
        /// <summary>
        /// ID des Benutzers der den Datensatz geändert hat.
        /// </summary>
        [Column("n_user_id_geaendert")]
        public int? NUserIdGeaendert { get; set; }
        /// <summary>
        /// Datum wann der Datensatz geändert wurde
        /// </summary>
        [Column("d_geaendert_am", TypeName = "datetime")]
        public DateTime? DGeaendertAm { get; set; }
    }
}