// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Enthält die möglichen Containertypen, welche im Menü beim Containerstau ausgewählt werden können.
    /// </summary>
    [Table("t_container_typen")]
    public partial class TContainerTypen
    {
        [Key]
        [Column("n_id")]
        public int NId { get; set; }
        [Column("c_name")]
        [StringLength(45)]
        public string CName { get; set; }
        [Column("n_siegel_tuer")]
        public bool NSiegelTuer { get; set; }
        [Column("n_siegel_dach")]
        public bool NSiegelDach { get; set; }
        [Column("c_kurzname")]
        [StringLength(15)]
        public string CKurzname { get; set; }
        [Column("c_name_englisch")]
        [StringLength(45)]
        public string CNameEnglisch { get; set; }
        [Column("c_kurzname_englisch")]
        [StringLength(15)]
        public string CKurznameEnglisch { get; set; }
        [Column("d_geloescht", TypeName = "datetime")]
        public DateTime? DGeloescht { get; set; }
        [Column("n_laenge_a")]
        public int NLaengeA { get; set; }
        [Column("n_laenge_i")]
        public int NLaengeI { get; set; }
        [Column("n_breite_a")]
        public int NBreiteA { get; set; }
        [Column("n_breite_i")]
        public int NBreiteI { get; set; }
        [Column("n_hoehe_a")]
        public int NHoeheA { get; set; }
        [Column("n_hoehe_i")]
        public int NHoeheI { get; set; }
        [Column("n_tuer_oeffnung_hoehe")]
        public int NTuerOeffnungHoehe { get; set; }
        [Column("n_tuer_oeffnung_breite")]
        public int NTuerOeffnungBreite { get; set; }
        [Column("n_dach_oeffnung_breite")]
        public int NDachOeffnungBreite { get; set; }
        [Column("n_dach_oeffnung_laenge")]
        public int NDachOeffnungLaenge { get; set; }
        [Column("n_max_gesamtgewicht")]
        public int NMaxGesamtgewicht { get; set; }
        [Column("n_leer_gewicht")]
        public int NLeerGewicht { get; set; }
        [Column("n_nutzlast")]
        public int NNutzlast { get; set; }
        [Column("m_bemerkung", TypeName = "mediumtext")]
        public string MBemerkung { get; set; }
        /// <summary>
        /// 1=Container, 2=LKW, 3=Anhaenger kat_grp=31
        /// </summary>
        [Column("n_typ_id")]
        public sbyte NTypId { get; set; }
        /// <summary>
        /// Position der 1.Achse zur Berechnung der Achslast
        /// </summary>
        [Column("n_achslast_pos_1")]
        public int? NAchslastPos1 { get; set; }
        /// <summary>
        /// Position der 2.Achse zur Berechnung der Achslast
        /// </summary>
        [Column("n_achslast_pos_2")]
        public int? NAchslastPos2 { get; set; }
        /// <summary>
        /// Max. Last für Achse 1
        /// </summary>
        [Column("n_achslast_max_1")]
        public int? NAchslastMax1 { get; set; }
        /// <summary>
        /// Max. Last für Achse 2
        /// </summary>
        [Column("n_achslast_max_2")]
        public int? NAchslastMax2 { get; set; }
    }
}