// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Speichert die eingegeben Daten zum Deckel
    /// </summary>
    [Table("t_deckel")]
    public partial class TDeckel
    {
        [Key]
        [Column("dl_id")]
        public int DlId { get; set; }
        [Column("dl_auftrag_id")]
        public int? DlAuftragId { get; set; }
        [Column("dl_kunde_id")]
        public int DlKundeId { get; set; }
        [Column("dl_ref_verp_auftrag_id")]
        public int? DlRefVerpAuftragId { get; set; }
        [Column("dl_ref_verp_typ_id")]
        public int? DlRefVerpTypId { get; set; }
        [Column("dl_ref_verp_id")]
        public int? DlRefVerpId { get; set; }
        [Column("dl_name")]
        [StringLength(25)]
        public string DlName { get; set; }
        [Column("dl_created", TypeName = "datetime")]
        public DateTime DlCreated { get; set; }
        [Column("dl_datum", TypeName = "datetime")]
        public DateTime? DlDatum { get; set; }
        [Column("dl_prj_id")]
        public int? DlPrjId { get; set; }
        /// <summary>
        /// ist NULL wenn template
        /// </summary>
        [Column("dl_nr")]
        [StringLength(50)]
        public string DlNr { get; set; }
        [Column("dl_deleted", TypeName = "datetime")]
        public DateTime? DlDeleted { get; set; }
        [Required]
        [Column("dl_aktiv")]
        public bool? DlAktiv { get; set; }
        [Column("dl_mattyp_id")]
        public int? DlMattypId { get; set; }
        [Column("dl_typ")]
        public int DlTyp { get; set; }
        [Column("dl_land_id")]
        public int? DlLandId { get; set; }
        [Column("dl_kunden_auftragsnr")]
        [StringLength(25)]
        public string DlKundenAuftragsnr { get; set; }
        [Column("dl_gedruckt")]
        public short DlGedruckt { get; set; }
        [Column("dl_anfrage_preis")]
        [Precision(19, 4)]
        public decimal? DlAnfragePreis { get; set; }
        [Column("c_id")]
        [StringLength(45)]
        public string CId { get; set; }
        [Column("c_rahmen_id")]
        [StringLength(45)]
        public string CRahmenId { get; set; }
        [Column("n_waehrung_id")]
        public int? NWaehrungId { get; set; }
        [Column("c_artikel_nr")]
        [StringLength(25)]
        public string CArtikelNr { get; set; }
        [Column("c_artikel_name")]
        [StringLength(25)]
        public string CArtikelName { get; set; }
        [Column("n_rabatt")]
        public float? NRabatt { get; set; }
        /// <summary>
        /// Qubikmeter aller Schnitthoelzer
        /// </summary>
        [Column("dl_schnittholz_m3")]
        [Precision(19, 4)]
        public decimal DlSchnittholzM3 { get; set; }
        /// <summary>
        /// Qubikmeter aller Plattenwerkstoffe
        /// </summary>
        [Column("dl_platten_m3")]
        [Precision(19, 4)]
        public decimal DlPlattenM3 { get; set; }
        /// <summary>
        /// Quadratmeter aller Plattenwerkstoffe
        /// </summary>
        [Column("dl_platten_m2")]
        [Precision(19, 4)]
        public decimal DlPlattenM2 { get; set; }
        [Column("dl_baufeld")]
        [StringLength(50)]
        public string DlBaufeld { get; set; }
        [Column("dl_baufeld_id")]
        public int? DlBaufeldId { get; set; }
        [Column("dl_baufeld_fert_id")]
        public int? DlBaufeldFertId { get; set; }
        [Column("dl_position")]
        [StringLength(25)]
        public string DlPosition { get; set; }
        [Column("dl_laenge")]
        public int DlLaenge { get; set; }
        [Column("dl_breite")]
        public int DlBreite { get; set; }
        /// <summary>
        /// Aussenmasshoehe
        /// </summary>
        [Column("dl_hoehe")]
        public int DlHoehe { get; set; }
        /// <summary>
        /// Anzahl der Deckel
        /// </summary>
        [Column("dl_anzahl")]
        public int DlAnzahl { get; set; }
        [Column("dl_holzbehandlung_id")]
        public int DlHolzbehandlungId { get; set; }
        /// <summary>
        /// Decklagen Brettstaerke
        /// </summary>
        [Column("dl_d_brett_st")]
        public int DlDBrettSt { get; set; }
        [Column("dl_d_lage_drehen")]
        public bool DlDLageDrehen { get; set; }
        [Column("dl_d_material_id")]
        public int DlDMaterialId { get; set; }
        [Column("dl_d_fall_cb")]
        public bool DlDFallCb { get; set; }
        [Column("dl_d_prismiert")]
        public bool DlDPrismiert { get; set; }
        [Column("dl_d_brett_b")]
        public int DlDBrettB { get; set; }
        [Column("dl_d_lueck_cb")]
        public bool DlDLueckCb { get; set; }
        [Column("dl_d_brett_cb")]
        public bool DlDBrettCb { get; set; }
        [Column("dl_d_lueck_st")]
        public int DlDLueckSt { get; set; }
        [Column("dl_d_fall_st")]
        public int DlDFallSt { get; set; }
        [Column("dl_d_brett_anzahl")]
        public int DlDBrettAnzahl { get; set; }
        /// <summary>
        /// Einruecken der Beleistung in Laenge
        /// </summary>
        [Column("dl_b_einrueck_laenge")]
        public int DlBEinrueckLaenge { get; set; }
        /// <summary>
        /// Einruecken der Beleistung in Breite
        /// </summary>
        [Column("dl_b_einrueck_breite")]
        public int DlBEinrueckBreite { get; set; }
        /// <summary>
        /// Brettstärker der Beleistung
        /// </summary>
        [Column("dl_b_brett_staerke")]
        public int DlBBrettStaerke { get; set; }
        /// <summary>
        /// Materialtyp der Beleistung kat_grp=1
        /// </summary>
        [Column("dl_b_material_id")]
        public int DlBMaterialId { get; set; }
        /// <summary>
        /// Typ der Beleistung kat_grp = 97
        /// </summary>
        [Column("dl_b_typ_id")]
        public int DlBTypId { get; set; }
        /// <summary>
        /// Beleistung Rahmen Laengsbrettbreite
        /// </summary>
        [Column("dl_b_r_lbrett_breite")]
        public int DlBRLbrettBreite { get; set; }
        /// <summary>
        /// Beleistung Rahmen Querbrettbreite
        /// </summary>
        [Column("dl_b_r_qbrett_breite")]
        public int DlBRQbrettBreite { get; set; }
        /// <summary>
        /// Bemerkung zum Deckel
        /// </summary>
        [Column("dl_info")]
        public string DlInfo { get; set; }
        /// <summary>
        /// Wenn Verpackung von anderer Firma gerfertigt wird
        /// </summary>
        [Column("dl_lieferant_id")]
        public int? DlLieferantId { get; set; }
        [Column("dl_kunden_artikel_nr")]
        [StringLength(30)]
        public string DlKundenArtikelNr { get; set; }
        [Column("n_verp_preiskat_id")]
        public int? NVerpPreiskatId { get; set; }
        [Column("n_fremd_verpfirma_id")]
        public int? NFremdVerpfirmaId { get; set; }
        [Column("d_ausgelagert")]
        public DateOnly? DAusgelagert { get; set; }
        /// <summary>
        /// Bruttogewicht Einbauten
        /// </summary>
        [Column("n_tara_einbauten")]
        public int? NTaraEinbauten { get; set; }
        [Column("c_konstr_opt_name")]
        [StringLength(30)]
        public string CKonstrOptName { get; set; }
        /// <summary>
        /// kat_grp = 150
        /// </summary>
        [Column("n_kuerzel_id")]
        public int? NKuerzelId { get; set; }
        /// <summary>
        /// laenge nicht zusammengebaut
        /// </summary>
        [Column("n_laenge_bausatz")]
        public ushort? NLaengeBausatz { get; set; }
        /// <summary>
        /// breite nicht zusammengebaut
        /// </summary>
        [Column("n_breite_bausatz")]
        public ushort? NBreiteBausatz { get; set; }
        /// <summary>
        /// hoehe nicht zusammengebaut
        /// </summary>
        [Column("n_hoehe_bausatz")]
        public ushort? NHoeheBausatz { get; set; }
        [Column("n_collo_laenge")]
        public int? NColloLaenge { get; set; }
        [Column("n_collo_breite")]
        public int? NColloBreite { get; set; }
        [Column("n_collo_hoehe")]
        public int? NColloHoehe { get; set; }
        [Column("n_collo_tara")]
        public int? NColloTara { get; set; }
        [Column("n_user_id_created")]
        public int? NUserIdCreated { get; set; }
        [Column("n_user_id_updated")]
        public int? NUserIdUpdated { get; set; }
        [Column("n_user_id_printed")]
        public int? NUserIdPrinted { get; set; }
        [Column("dl_anzahl_nicht_verrechenbar")]
        public int DlAnzahlNichtVerrechenbar { get; set; }
    }
}