// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Dokumente die importiert wurden. Aktuell wird es nur bei Projekten genutzt.
    /// </summary>
    [Table("t_dokumente")]
    [Index("CParent", "NParentId", Name = "IDX_PARENT_ID")]
    public partial class TDokumente
    {
        [Key]
        [Column("n_id")]
        public int NId { get; set; }
        [Column("c_parent")]
        [StringLength(50)]
        public string CParent { get; set; }
        /// <summary>
        /// ID des eigentlichen Objekte t_projekt.prj_id
        /// </summary>
        [Column("n_parent_id")]
        public int NParentId { get; set; }
        [Column("c_file_name")]
        [StringLength(100)]
        public string CFileName { get; set; }
        [Column("n_file_length")]
        public int NFileLength { get; set; }
        [Column("c_file_type")]
        [StringLength(20)]
        public string CFileType { get; set; }
        [Column("c_kurzbemerkung")]
        [StringLength(100)]
        public string CKurzbemerkung { get; set; }
        [Column("d_created")]
        public DateOnly DCreated { get; set; }
        [Column("m_data")]
        public byte[] MData { get; set; }
        [Column("n_zipped")]
        public short NZipped { get; set; }
    }
}