// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Protkolliert die Einlagerung von Posten
    /// </summary>
    [Table("t_einlagerung")]
    [Index("NArtikelId", Name = "idx_n_artikel_id")]
    [Index("NKundeId", Name = "idx_n_kunde_id")]
    [Index("NLagerId", Name = "idx_n_lager_id")]
    [Index("NWareneingangArtikelId", Name = "idx_n_wareneingang_artikel_id")]
    public partial class TEinlagerung
    {
        [Key]
        [Column("n_id")]
        public long NId { get; set; }
        [Column("n_lager_id")]
        public int NLagerId { get; set; }
        [Column("n_lagerort_id")]
        public int NLagerortId { get; set; }
        [Column("n_kunde_id")]
        public int NKundeId { get; set; }
        [Column("n_lieferant_id")]
        public int? NLieferantId { get; set; }
        [Column("n_artikel_id")]
        public int NArtikelId { get; set; }
        [Column("n_einheit_id")]
        public int NEinheitId { get; set; }
        [Column("n_wareneingang_artikel_id")]
        public int? NWareneingangArtikelId { get; set; }
        [Column("n_wareneingang_verp_id")]
        public int? NWareneingangVerpId { get; set; }
        [Column("c_verp_id")]
        [StringLength(45)]
        public string CVerpId { get; set; }
        [Column("n_auslagerung_verp_id")]
        public int? NAuslagerungVerpId { get; set; }
        /// <summary>
        /// id von t_packmittel_gebraucht_nr
        /// </summary>
        [Column("n_gebraucht_verp_id")]
        public int? NGebrauchtVerpId { get; set; }
        [Column("n_auftrag_id")]
        public int? NAuftragId { get; set; }
        [Column("n_posten_id")]
        public int? NPostenId { get; set; }
        [Column("c_posten_nr")]
        [StringLength(15)]
        public string CPostenNr { get; set; }
        [Column("n_posten_typ_id")]
        public int? NPostenTypId { get; set; }
        [Column("n_laenge")]
        public int? NLaenge { get; set; }
        [Column("n_breite")]
        public int? NBreite { get; set; }
        [Column("n_hoehe")]
        public int? NHoehe { get; set; }
        [Column("n_brutto_gewicht")]
        [Precision(12, 3)]
        public decimal? NBruttoGewicht { get; set; }
        [Column("c_bestell_nr")]
        [StringLength(100)]
        public string CBestellNr { get; set; }
        [Column("n_bestell_pos")]
        public int? NBestellPos { get; set; }
        [Column("n_anzahl")]
        public float NAnzahl { get; set; }
        [Column("c_kommisions_nr")]
        [StringLength(50)]
        public string CKommisionsNr { get; set; }
        [Column("d_einlagerung")]
        public DateOnly? DEinlagerung { get; set; }
        [Column("m_bemerkung", TypeName = "mediumtext")]
        public string MBemerkung { get; set; }
        [Column("d_auslagerung")]
        public DateOnly? DAuslagerung { get; set; }
        /// <summary>
        /// 1=Einlagerung durch Umgern 0=normale Einlagerung
        /// </summary>
        [Column("n_umlagerung")]
        public bool NUmlagerung { get; set; }
        /// <summary>
        /// t_einlagerung.n_id wenn umgelagert wurde ist der Wert ungleich NULL
        /// </summary>
        [Column("n_old_einlagerung_id")]
        public long? NOldEinlagerungId { get; set; }
    }
}