// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Wird für die FEM Berechnung genutzt. Speichert die Lasten die auf dem Boden einwirken.
    /// </summary>
    [Table("t_fem_colli_lastflaeche")]
    public partial class TFemColliLastflaeche
    {
        [Key]
        [Column("c_id")]
        [StringLength(45)]
        public string CId { get; set; }
        [Key]
        [Column("n_id")]
        public int NId { get; set; }
        [Column("c_name")]
        [StringLength(45)]
        public string CName { get; set; }
        /// <summary>
        /// Position X-Koordinate
        /// </summary>
        [Column("n_x")]
        public int NX { get; set; }
        /// <summary>
        /// Position Y-Koordinate
        /// </summary>
        [Column("n_y")]
        public int NY { get; set; }
        /// <summary>
        /// Position Z-Koordinate
        /// </summary>
        [Column("n_z")]
        public int NZ { get; set; }
        /// <summary>
        /// Ausdehnung in X-Richtung
        /// </summary>
        [Column("n_x_delta")]
        public int NXDelta { get; set; }
        /// <summary>
        /// Ausdehnung in Y-Richtung
        /// </summary>
        [Column("n_y_delta")]
        public int NYDelta { get; set; }
        /// <summary>
        /// Einwirkende Last in Newton an der Position mit der Ausdehnung
        /// </summary>
        [Column("n_last_newton")]
        public int NLastNewton { get; set; }
    }
}