// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Rechnungsanschrift zu einer Firma
    /// </summary>
    [Table("t_firma_rechnungsanschrift")]
    public partial class TFirmaRechnungsanschrift
    {
        [Key]
        [Column("n_firma_id")]
        public int NFirmaId { get; set; }
        [Column("c_firma")]
        [StringLength(70)]
        public string CFirma { get; set; }
        [Column("c_firma_zusatz")]
        [StringLength(45)]
        public string CFirmaZusatz { get; set; }
        [Column("c_plz")]
        [StringLength(15)]
        public string CPlz { get; set; }
        [Column("c_strasse")]
        [StringLength(40)]
        public string CStrasse { get; set; }
        [Column("c_strasse_nr")]
        [StringLength(20)]
        public string CStrasseNr { get; set; }
        [Column("c_ort")]
        [StringLength(40)]
        public string COrt { get; set; }
        [Column("n_land_id")]
        public int? NLandId { get; set; }
        [Column("c_postfach_plz")]
        [StringLength(15)]
        public string CPostfachPlz { get; set; }
        [Column("c_postfach")]
        [StringLength(40)]
        public string CPostfach { get; set; }
        [Column("c_abteilung")]
        [StringLength(100)]
        public string CAbteilung { get; set; }
    }
}