// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Bilder zum Material einer Firma
    /// </summary>
    [Table("t_firma_materialbilder")]
    public partial class TFirmaMaterialbilder
    {
        [Key]
        [Column("n_firma_id")]
        public int NFirmaId { get; set; }
        [Key]
        [Column("n_material_id")]
        public int NMaterialId { get; set; }
        [Key]
        [Column("n_id")]
        public int NId { get; set; }
        [Required]
        [Column("b_bild")]
        public byte[] BBild { get; set; }
        [Column("m_bemerkung", TypeName = "mediumtext")]
        public string MBemerkung { get; set; }
        [Column("n_zipped")]
        public bool NZipped { get; set; }
        [Column("d_created", TypeName = "timestamp")]
        public DateTime DCreated { get; set; }
    }
}