// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Zweigstellen zu einer Firma. Diese Zweigstellen können z.B. beim Lieferschein ausgewählt werden.
    /// </summary>
    [Table("t_firmazweigstelle")]
    [Index("NFirmaId", Name = "idx_n_firma_id")]
    public partial class TFirmazweigstelle
    {
        [Key]
        [Column("n_id")]
        public int NId { get; set; }
        [Column("n_firma_id")]
        public int? NFirmaId { get; set; }
        [Column("c_bezeichnung")]
        [StringLength(200)]
        public string CBezeichnung { get; set; }
        [Column("c_plz")]
        [StringLength(20)]
        public string CPlz { get; set; }
        [Column("c_ort")]
        [StringLength(70)]
        public string COrt { get; set; }
        [Column("c_postfach_plz")]
        [StringLength(20)]
        public string CPostfachPlz { get; set; }
        [Column("c_postfach")]
        [StringLength(70)]
        public string CPostfach { get; set; }
        [Column("c_strasse")]
        [StringLength(70)]
        public string CStrasse { get; set; }
        [Column("c_haus_nr")]
        [StringLength(20)]
        public string CHausNr { get; set; }
        [Column("c_land")]
        [StringLength(40)]
        public string CLand { get; set; }
        [Column("n_staat_id")]
        public int? NStaatId { get; set; }
        [Column("m_bemerkung", TypeName = "mediumtext")]
        public string MBemerkung { get; set; }
        [Column("n_typ")]
        public int? NTyp { get; set; }
        [Column("c_telefon")]
        [StringLength(50)]
        public string CTelefon { get; set; }
        [Column("c_fax")]
        [StringLength(50)]
        public string CFax { get; set; }
        [Column("c_email")]
        [StringLength(100)]
        public string CEmail { get; set; }
        [Column("c_url")]
        [StringLength(100)]
        public string CUrl { get; set; }
        [Column("c_namen_zusatz")]
        [StringLength(45)]
        public string CNamenZusatz { get; set; }
        [Column("n_niederlassung_id")]
        public int? NNiederlassungId { get; set; }
    }
}