// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Firmentypen wie Verppackungkunde, Lagerkunde, Transportuer, .. die in Gruppen wie Kunde, Lieferant,.. unterteilt sind.
    /// </summary>
    [Table("t_firma_typ")]
    [Index("NGruppenTypId", Name = "IDX_GRUPPEN_TYP")]
    public partial class TFirmaTyp
    {
        [Key]
        [Column("n_id")]
        public int NId { get; set; }
        /// <summary>
        /// t_firma_gruppentyp
        /// </summary>
        [Column("n_gruppen_typ_id")]
        public int NGruppenTypId { get; set; }
        [Column("c_bezeichnung")]
        [StringLength(45)]
        public string CBezeichnung { get; set; }
        [Column("n_icon")]
        public int NIcon { get; set; }
    }
}