// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Kopfdaten für die Fertigmeldung, welche die finalen Verpckungsdaten beinhaltet
    /// </summary>
    [Table("t_freigabe")]
    public partial class TFreigabe
    {
        [Key]
        [Column("n_id")]
        public int NId { get; set; }
        [Column("n_kunde_id")]
        public int NKundeId { get; set; }
        [Column("c_nr")]
        [StringLength(20)]
        public string CNr { get; set; }
        [Column("c_adr_firma")]
        [StringLength(50)]
        public string CAdrFirma { get; set; }
        [Column("c_adr_firma_zusatz")]
        [StringLength(45)]
        public string CAdrFirmaZusatz { get; set; }
        [Column("c_adr_feld_1")]
        [StringLength(45)]
        public string CAdrFeld1 { get; set; }
        [Column("c_adr_feld_2")]
        [StringLength(45)]
        public string CAdrFeld2 { get; set; }
        [Column("c_adr_plz_ort")]
        [StringLength(45)]
        public string CAdrPlzOrt { get; set; }
        [Column("c_adr_zu_haenden")]
        [StringLength(40)]
        public string CAdrZuHaenden { get; set; }
        [Column("d_datum")]
        public DateOnly? DDatum { get; set; }
        [Column("c_adr_lief_firma")]
        [StringLength(45)]
        public string CAdrLiefFirma { get; set; }
        [Column("c_adr_lief_feld_1")]
        [StringLength(45)]
        public string CAdrLiefFeld1 { get; set; }
        [Column("c_adr_lief_feld_2")]
        [StringLength(45)]
        public string CAdrLiefFeld2 { get; set; }
        [Column("n_andere_lief_anschrift")]
        public bool NAndereLiefAnschrift { get; set; }
        [Column("c_adr_lief_plz_ort")]
        [StringLength(45)]
        public string CAdrLiefPlzOrt { get; set; }
        [Column("m_bemerkung", TypeName = "mediumtext")]
        public string MBemerkung { get; set; }
        [Column("m_einleitung", TypeName = "mediumtext")]
        public string MEinleitung { get; set; }
        [Column("m_nachsatz", TypeName = "mediumtext")]
        public string MNachsatz { get; set; }
        [Column("m_betreff", TypeName = "mediumtext")]
        public string MBetreff { get; set; }
        [Column("n_ohne_netto_gewichte")]
        public bool? NOhneNettoGewichte { get; set; }
        /// <summary>
        /// Zeit wann Dokument gedruckt wurde
        /// </summary>
        [Column("d_gedruckt", TypeName = "datetime")]
        public DateTime? DGedruckt { get; set; }
        [Column("d_created", TypeName = "datetime")]
        public DateTime? DCreated { get; set; }
        [Column("n_user_id")]
        public int? NUserId { get; set; }
        /// <summary>
        /// ID des Benutzers der den Datensatz erstellt hat.
        /// </summary>
        [Column("n_user_id_erstellt")]
        public int? NUserIdErstellt { get; set; }
        /// <summary>
        /// ID des Benutzers der den Datensatz geändert hat.
        /// </summary>
        [Column("n_user_id_geaendert")]
        public int? NUserIdGeaendert { get; set; }
        /// <summary>
        /// Datum wann der Datensatz geändert wurde
        /// </summary>
        [Column("d_geaendert_am", TypeName = "datetime")]
        public DateTime? DGeaendertAm { get; set; }
    }
}