// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Fremdböden die bei der Stülpkiste eingesetzt werden können
    /// </summary>
    [Table("t_fremdboden")]
    public partial class TFremdboden
    {
        [Key]
        [Column("bd_id")]
        public int BdId { get; set; }
        [Column("bd_name")]
        [StringLength(75)]
        public string BdName { get; set; }
        [Column("bd_laenge")]
        public float? BdLaenge { get; set; }
        [Column("bd_breite")]
        public float? BdBreite { get; set; }
        [Column("bd_hoehe")]
        public float? BdHoehe { get; set; }
        [Column("bd_kg")]
        public float? BdKg { get; set; }
        [Column("bd_stuelpmass")]
        public float? BdStuelpmass { get; set; }
        [Column("bd_vd_gleich_check")]
        public int? BdVdGleichCheck { get; set; }
        [Column("bd_vd_gleich")]
        public float? BdVdGleich { get; set; }
        /// <summary>
        /// Bodenlagestärke
        /// </summary>
        [Column("bd_vd_bl_st")]
        public float? BdVdBlSt { get; set; }
        [Column("bd_vd_bl_check")]
        public int? BdVdBlCheck { get; set; }
        [Column("bd_vd_bl_mat")]
        public int? BdVdBlMat { get; set; }
        [Column("bd_vd_bl_art")]
        public int? BdVdBlArt { get; set; }
        [Column("bd_vd_zl_check")]
        public int? BdVdZlCheck { get; set; }
        /// <summary>
        /// Zwischenlagestärke
        /// </summary>
        [Column("bd_vd_zl_st")]
        public float? BdVdZlSt { get; set; }
        [Column("bd_vd_zl_mat")]
        public int? BdVdZlMat { get; set; }
        [Column("bd_vd_zl_art")]
        public int? BdVdZlArt { get; set; }
        [Column("bd_vd_dl_check")]
        public int? BdVdDlCheck { get; set; }
        /// <summary>
        /// Decklagenstärke
        /// </summary>
        [Column("bd_vd_dl_st")]
        public float? BdVdDlSt { get; set; }
        [Column("bd_vd_dl_mat")]
        public int? BdVdDlMat { get; set; }
        [Column("bd_vd_dl_art")]
        public int? BdVdDlArt { get; set; }
        [Column("bd_vd_dl_dd_check")]
        public int? BdVdDlDdCheck { get; set; }
        /// <summary>
        /// Kantholzlage
        /// </summary>
        [Column("bd_vd_kh_check")]
        public int? BdVdKhCheck { get; set; }
        [Column("bd_vd_kh_mat")]
        public int? BdVdKhMat { get; set; }
        [Column("bd_vd_kh_art")]
        public int? BdVdKhArt { get; set; }
    }
}