// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// FTP Server Konfiguration für den Upload der Fotodokumentation
    /// </summary>
    [Table("t_ftp_server_config")]
    public partial class TFtpServerConfig
    {
        [Key]
        [Column("n_id")]
        public int NId { get; set; }
        [Column("c_server")]
        [StringLength(100)]
        public string CServer { get; set; }
        [Column("c_user")]
        [StringLength(100)]
        public string CUser { get; set; }
        [Column("c_password")]
        [StringLength(100)]
        public string CPassword { get; set; }
        [Column("c_uploadir")]
        [StringLength(100)]
        public string CUploadir { get; set; }
        [Column("n_port")]
        public int NPort { get; set; }
        /// <summary>
        /// 1=no, 2=implizit, 3=erfordert, 4=explizit
        /// </summary>
        [Column("n_tls_type")]
        public int NTlsType { get; set; }
        /// <summary>
        /// 1=ftp, 2=sftp
        /// </summary>
        [Column("n_protokoll")]
        public int NProtokoll { get; set; }
        [Column("c_server_download")]
        [StringLength(100)]
        public string CServerDownload { get; set; }
        [Column("c_downloadir")]
        [StringLength(100)]
        public string CDownloadir { get; set; }
    }
}