// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Liste des Gefahrguts
    /// </summary>
    [Table("t_gefahrgut")]
    [Index("GgHerstellerId", Name = "idx_gg_hersteller_id")]
    [Index("GgHerstellerId", "GgUnnr", Name = "idx_gg_hersteller_id_gg_bez")]
    public partial class TGefahrgut
    {
        [Key]
        [Column("gg_id")]
        public int GgId { get; set; }
        [Column("gg_hersteller_id")]
        public int? GgHerstellerId { get; set; }
        [Column("gg_bez")]
        [StringLength(255)]
        public string GgBez { get; set; }
        [Column("gg_unnr")]
        [StringLength(15)]
        public string GgUnnr { get; set; }
        [Column("gg_flammpkt")]
        [StringLength(10)]
        public string GgFlammpkt { get; set; }
        [Column("gg_bild1_id")]
        public int? GgBild1Id { get; set; }
        [Column("gg_bild2_id")]
        public int? GgBild2Id { get; set; }
        [Column("gg_klasse_l")]
        [StringLength(5)]
        public string GgKlasseL { get; set; }
        [Column("gg_ziffer_l")]
        [StringLength(5)]
        public string GgZifferL { get; set; }
        [Column("gg_bez_l")]
        [StringLength(255)]
        public string GgBezL { get; set; }
        [Column("gg_nr_l")]
        [StringLength(5)]
        public string GgNrL { get; set; }
        [Column("gg_bem_l", TypeName = "mediumtext")]
        public string GgBemL { get; set; }
        [Column("gg_klasse_s")]
        [StringLength(5)]
        public string GgKlasseS { get; set; }
        [Column("gg_name_s")]
        [StringLength(255)]
        public string GgNameS { get; set; }
        [Column("gg_emsnr_s")]
        [StringLength(8)]
        public string GgEmsnrS { get; set; }
        [Column("gg_pollutant_s")]
        public bool? GgPollutantS { get; set; }
        [Column("gg_bem_s", TypeName = "mediumtext")]
        public string GgBemS { get; set; }
        [Column("gg_klasse_a")]
        [StringLength(5)]
        public string GgKlasseA { get; set; }
        [Column("gg_name_a")]
        [StringLength(255)]
        public string GgNameA { get; set; }
        [Column("gg_verpgrp_a")]
        [StringLength(5)]
        public string GgVerpgrpA { get; set; }
        [Column("gg_bem_a", TypeName = "mediumtext")]
        public string GgBemA { get; set; }
        [Column("gg_verpgrp_s")]
        [StringLength(5)]
        public string GgVerpgrpS { get; set; }
        [Column("gg_flugpass_a")]
        [StringLength(6)]
        public string GgFlugpassA { get; set; }
        [Column("gg_flugfracht_a")]
        [StringLength(20)]
        public string GgFlugfrachtA { get; set; }
        [Column("gg_gefahrenzahl")]
        [StringLength(10)]
        public string GgGefahrenzahl { get; set; }
        [Column("gg_verp_kennzeichnung")]
        [StringLength(45)]
        public string GgVerpKennzeichnung { get; set; }
    }
}