// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Gesamtpreis eines Auftrags. Wird genutzt für Nachverhandlungen mit dem Kunde, damit die eigentlichen Preise sichtbar sind und bleiben.
    /// </summary>
    [Table("t_gesamtpreis_detail")]
    public partial class TGesamtpreisDetail
    {
        [Key]
        [Column("n_auftrag_id")]
        public int NAuftragId { get; set; }
        [Key]
        [Column("n_posten_id")]
        public int NPostenId { get; set; }
        [Key]
        [Column("n_id")]
        public int NId { get; set; }
        /// <summary>
        /// kat_grp = 61
        /// </summary>
        [Column("n_typ_id")]
        public int NTypId { get; set; }
        [Column("c_bez")]
        [StringLength(50)]
        public string CBez { get; set; }
        [Column("n_betrag")]
        [Precision(19, 2)]
        public decimal NBetrag { get; set; }
    }
}