// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Liste der gesetzlichen Feiertage
    /// </summary>
    [Table("t_holidays")]
    public partial class THoliday
    {
        [Key]
        [Column("n_id")]
        public int NId { get; set; }
        [Column("c_location")]
        [StringLength(35)]
        public string CLocation { get; set; }
        [Column("c_name")]
        [StringLength(35)]
        public string CName { get; set; }
        [Column("d_date")]
        public DateOnly DDate { get; set; }
        [Column("n_yearly")]
        public bool? NYearly { get; set; }
    }
}