// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Posten zur IMO Erklärung
    /// </summary>
    [Table("t_imo_details")]
    public partial class TImoDetail
    {
        [Key]
        [Column("n_imo_id")]
        public int NImoId { get; set; }
        [Key]
        [Column("n_id")]
        public int NId { get; set; }
        [Column("n_gefahrgut_id")]
        public int? NGefahrgutId { get; set; }
        [Column("c_unnr")]
        [StringLength(15)]
        public string CUnnr { get; set; }
        [Column("c_techname")]
        [StringLength(255)]
        public string CTechname { get; set; }
        [Column("c_klasse")]
        [StringLength(5)]
        public string CKlasse { get; set; }
        [Column("c_verpackungsgrp")]
        [StringLength(20)]
        public string CVerpackungsgrp { get; set; }
        [Column("c_markierung")]
        [StringLength(45)]
        public string CMarkierung { get; set; }
        [Column("n_anzahl")]
        [Precision(10, 3)]
        public decimal? NAnzahl { get; set; }
        [Column("c_verp_art")]
        [StringLength(40)]
        public string CVerpArt { get; set; }
        [Column("c_verp_zusatz")]
        [StringLength(50)]
        public string CVerpZusatz { get; set; }
        [Column("n_brutto_gewicht")]
        [Precision(10, 3)]
        public decimal? NBruttoGewicht { get; set; }
        [Column("n_netto_gewicht")]
        [Precision(10, 3)]
        public decimal? NNettoGewicht { get; set; }
        [Column("c_ems_nr")]
        [StringLength(10)]
        public string CEmsNr { get; set; }
        [Column("c_flammpunkt")]
        [StringLength(10)]
        public string CFlammpunkt { get; set; }
        [Column("c_eigenschaften")]
        [StringLength(50)]
        public string CEigenschaften { get; set; }
        [Column("n_marine_pollutant")]
        public bool? NMarinePollutant { get; set; }
        [Column("c_kontroll_temp")]
        [StringLength(10)]
        public string CKontrollTemp { get; set; }
        [Column("c_notfall_temp")]
        [StringLength(10)]
        public string CNotfallTemp { get; set; }
    }
}