// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Prozentuale Belegung der Verschalung inkl. Boden für Verschläge in Abhängigkeit vom Materialtyp
    /// </summary>
    [Table("t_initbelegungvalue")]
    public partial class TInitbelegungvalue
    {
        [Key]
        [Column("n_verp_typ")]
        public int NVerpTyp { get; set; }
        /// <summary>
        /// kat_grp=1
        /// </summary>
        [Key]
        [Column("n_mat_typ")]
        public int NMatTyp { get; set; }
        [Column("n_alle")]
        public float? NAlle { get; set; }
        [Column("n_kopf")]
        public float? NKopf { get; set; }
        [Column("n_seite")]
        public float? NSeite { get; set; }
        [Column("n_deckel")]
        public float? NDeckel { get; set; }
        [Column("n_boden")]
        public float? NBoden { get; set; }
    }
}