// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// content of package
    /// </summary>
    [Table("t_interf_auftrag_posten_inhalt")]
    [Index("NAuftragId", "NVerpId", "NVerpTypId", Name = "IDX_VERP")]
    public partial class TInterfAuftragPostenInhalt
    {
        [Key]
        [Column("n_auftrag_id")]
        public int NAuftragId { get; set; }
        [Key]
        [Column("n_id")]
        public int NId { get; set; }
        [Column("n_verp_id")]
        public int? NVerpId { get; set; }
        [Column("n_verp_typ_id")]
        public int? NVerpTypId { get; set; }
        [Column("c_nr")]
        [StringLength(20)]
        public string CNr { get; set; }
        [Column("c_pos")]
        [StringLength(20)]
        public string CPos { get; set; }
        [Column("c_bez")]
        [StringLength(40)]
        public string CBez { get; set; }
        [Column("c_serien_nr")]
        [StringLength(25)]
        public string CSerienNr { get; set; }
        [Column("n_anzahl")]
        public double? NAnzahl { get; set; }
        [Column("n_gewicht_gesamt")]
        [Precision(8, 2)]
        public decimal? NGewichtGesamt { get; set; }
        [Column("c_einheit")]
        [StringLength(20)]
        public string CEinheit { get; set; }
    }
}