// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Standardwerte zur Kalkulation der Gruppe Personal
    /// </summary>
    [Table("t_kalkulation_stdwerte_personal")]
    public partial class TKalkulationStdwertePersonal
    {
        [Key]
        [Column("n_id")]
        public int NId { get; set; }
        /// <summary>
        /// Boden-Montage Minuten pro  Quadratmeter
        /// </summary>
        [Column("n_mon_boden_m2_min")]
        public int NMonBodenM2Min { get; set; }
        /// <summary>
        /// Kopf-Montage Minuten pro  Quadratmeter
        /// </summary>
        [Column("n_mon_kopf_m2_min")]
        public int NMonKopfM2Min { get; set; }
        /// <summary>
        /// Seiten-Montage Minuten pro  Quadratmeter
        /// </summary>
        [Column("n_mon_seite_m2_min")]
        public int NMonSeiteM2Min { get; set; }
        /// <summary>
        /// Deckel-Montage Minuten pro  Quadratmeter
        /// </summary>
        [Column("n_mon_deckel_m2_min")]
        public int NMonDeckelM2Min { get; set; }
        /// <summary>
        /// Boden-Montage Minuten pro  Qubiktmeter
        /// </summary>
        [Column("n_mon_boden_m3_min")]
        public int NMonBodenM3Min { get; set; }
        /// <summary>
        /// Kopf-Montage Minuten pro  Qubiktmeter
        /// </summary>
        [Column("n_mon_kopf_m3_min")]
        public int NMonKopfM3Min { get; set; }
        /// <summary>
        /// Seite-Montage Minuten pro  Qubiktmeter
        /// </summary>
        [Column("n_mon_seite_m3_min")]
        public int NMonSeiteM3Min { get; set; }
        /// <summary>
        /// Deckel-Montage Minuten pro  Qubiktmeter
        /// </summary>
        [Column("n_mon_deckel_m3_min")]
        public int NMonDeckelM3Min { get; set; }
        /// <summary>
        /// Paletten-Montage Minuten pro  Qubiktmeter
        /// </summary>
        [Column("n_mon_palette_m3_min")]
        public int NMonPaletteM3Min { get; set; }
        /// <summary>
        /// 1=Berechnung nach Quadratmeter; 2=Berechnung nach Qubikmeter
        /// </summary>
        [Column("n_mon_berech_boden")]
        public int NMonBerechBoden { get; set; }
        /// <summary>
        /// 1=Berechnung nach Quadratmeter; 2=Berechnung nach Qubikmeter
        /// </summary>
        [Column("n_mon_berech_kopf")]
        public int NMonBerechKopf { get; set; }
        /// <summary>
        /// 1=Berechnung nach Quadratmeter; 2=Berechnung nach Qubikmeter
        /// </summary>
        [Column("n_mon_berech_seite")]
        public int NMonBerechSeite { get; set; }
        /// <summary>
        /// 1=Berechnung nach Quadratmeter; 2=Berechnung nach Qubikmeter
        /// </summary>
        [Column("n_mon_berech_deckel")]
        public int NMonBerechDeckel { get; set; }
        /// <summary>
        /// Minuten  fuer Zuschnitt pro Quadratmeterware
        /// </summary>
        [Column("n_zuschnitt_m2_min")]
        public int NZuschnittM2Min { get; set; }
        /// <summary>
        /// Minuten  fuer Zuschnitt pro Qubiktmeterware
        /// </summary>
        [Column("n_zuschnitt_m3_min")]
        public int NZuschnittM3Min { get; set; }
        /// <summary>
        /// 1=Berechnung nach Quadratmeter; 2=Berechnung nach Qubikmeter
        /// </summary>
        [Column("n_zuschnitt_berech")]
        public int NZuschnittBerech { get; set; }
        /// <summary>
        /// Stundepreis der Mannstunde
        /// </summary>
        [Column("n_stundenpreis")]
        [Precision(10, 2)]
        public decimal NStundenpreis { get; set; }
        /// <summary>
        /// Zuschlagkalkulations pro Kupplung
        /// </summary>
        [Column("n_zk_kupplung")]
        public int NZkKupplung { get; set; }
        /// <summary>
        /// Zuschlagkalkulations pro genageltes Bohrholz
        /// </summary>
        [Column("n_zk_bh_genagelt")]
        public int NZkBhGenagelt { get; set; }
        /// <summary>
        /// Zuschlagkalkulations pro gebohrtes Bohrholz
        /// </summary>
        [Column("n_zk_bh_gebohrt")]
        public int NZkBhGebohrt { get; set; }
        /// <summary>
        /// Zuschlagkalkulations pro U-Stahl
        /// </summary>
        [Column("n_zk_ustahl")]
        public int NZkUstahl { get; set; }
        /// <summary>
        /// Zuschlagkalkulations pro Markierungsbuchstabe
        /// </summary>
        [Column("n_zk_markierung_buchstabe")]
        public int NZkMarkierungBuchstabe { get; set; }
        /// <summary>
        /// Aussenqmpreis
        /// </summary>
        [Column("n_vp_verpackt_pal")]
        [Precision(10, 2)]
        public decimal NVpVerpacktPal { get; set; }
        /// <summary>
        /// Aussenqmpreis
        /// </summary>
        [Column("n_vp_seem_pal")]
        [Precision(10, 2)]
        public decimal NVpSeemPal { get; set; }
        /// <summary>
        /// Aussenqmpreis
        /// </summary>
        [Column("n_vp_verpackt_kiste")]
        [Precision(10, 2)]
        public decimal NVpVerpacktKiste { get; set; }
        /// <summary>
        /// Aussenqmpreis
        /// </summary>
        [Column("n_vp_seem_kiste")]
        [Precision(10, 2)]
        public decimal NVpSeemKiste { get; set; }
    }
}