// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Standardwerte für Holz bei der Kalkulation
    /// </summary>
    [Table("t_kalkulation_stdwerte_holz")]
    public partial class TKalkulationStdwerteHolz
    {
        [Key]
        [Column("n_lieferant_id")]
        public int NLieferantId { get; set; }
        [Key]
        [Column("n_artikel_id")]
        public int NArtikelId { get; set; }
        [Column("c_bezeichnung")]
        [StringLength(45)]
        public string CBezeichnung { get; set; }
    }
}