// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    [Table("t_kalkulation_fertigung")]
    public partial class TKalkulationFertigung
    {
        [Key]
        [Column("n_id")]
        public long NId { get; set; }
        /// <summary>
        /// Anzahl Minuten pro Qubik pro Mannstunde Schnittkiste
        /// </summary>
        [Column("n_m3_schnittholz_kiste")]
        [Precision(10, 3)]
        public decimal? NM3SchnittholzKiste { get; set; }
        /// <summary>
        /// Anzahl Minuten Qubik pro Mannstunde Plattenwerkstoffkiste
        /// </summary>
        [Column("n_m3_plattenholz_kiste")]
        [Precision(10, 3)]
        public decimal? NM3PlattenholzKiste { get; set; }
        /// <summary>
        /// Anzahl Minuten Qubik pro Mannstunde Verschlag
        /// </summary>
        [Column("n_m3_verschlag")]
        [Precision(10, 3)]
        public decimal? NM3Verschlag { get; set; }
        /// <summary>
        /// Anzahl Minuten pro Qubik Palette
        /// </summary>
        [Column("n_m3_palette")]
        [Precision(10, 3)]
        public decimal? NM3Palette { get; set; }
        /// <summary>
        /// Anzahl Minuten pro Qubik Beipack/Zuschnitt
        /// </summary>
        [Column("n_m3_beipack_holz")]
        [Precision(10, 3)]
        public decimal? NM3BeipackHolz { get; set; }
        /// <summary>
        /// Anzahl Minuten Qubik pro Mannstunde Beipack/Konstruktionsholz
        /// </summary>
        [Column("n_m3_konstruktions_holz")]
        [Precision(10, 3)]
        public decimal? NM3KonstruktionsHolz { get; set; }
        /// <summary>
        /// Anzahl Minuten pro Aussenqm Schnittkiste
        /// </summary>
        [Column("n_m2_schnittholz_kiste")]
        [Precision(10, 3)]
        public decimal? NM2SchnittholzKiste { get; set; }
        /// <summary>
        /// Anzahl Minuten pro Aussenqm Plattenwerkstoffkiste
        /// </summary>
        [Column("n_m2_plattenholz_kiste")]
        [Precision(10, 3)]
        public decimal? NM2PlattenholzKiste { get; set; }
        /// <summary>
        /// Anzahl Minuten pro Aussenqm Verschlag
        /// </summary>
        [Column("n_m2_verschlag")]
        [Precision(10, 3)]
        public decimal? NM2Verschlag { get; set; }
    }
}