// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Standardwerte zur Kalkulation
    /// </summary>
    [Table("t_kalkulation_stdwerte_sonstiges")]
    public partial class TKalkulationStdwerteSonstige
    {
        [Key]
        [Column("n_id")]
        public int NId { get; set; }
        [Column("c_bezeichnung")]
        [StringLength(45)]
        public string CBezeichnung { get; set; }
        [Column("n_kosten")]
        [Precision(10, 2)]
        public decimal NKosten { get; set; }
        [Column("m_bemerkung", TypeName = "mediumtext")]
        public string MBemerkung { get; set; }
    }
}