// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    [Table("t_kalkulation_holz")]
    public partial class TKalkulationHolz
    {
        [Key]
        [Column("n_verp_id")]
        public int NVerpId { get; set; }
        [Key]
        [Column("n_verptyp_id")]
        public int NVerptypId { get; set; }
        [Key]
        [Column("n_parent_id")]
        public int NParentId { get; set; }
        [Key]
        [Column("n_id")]
        public int NId { get; set; }
        [Column("c_name")]
        [StringLength(45)]
        public string CName { get; set; }
        [Column("c_bezeichnung")]
        [StringLength(50)]
        public string CBezeichnung { get; set; }
        [Column("n_anzahl")]
        [Precision(12, 2)]
        public decimal NAnzahl { get; set; }
        [Column("n_laenge")]
        [Precision(12, 2)]
        public decimal NLaenge { get; set; }
        [Column("n_breite")]
        [Precision(12, 2)]
        public decimal NBreite { get; set; }
        [Column("n_brett_breite")]
        [Precision(6, 2)]
        public decimal? NBrettBreite { get; set; }
        [Column("n_hoehe")]
        [Precision(12, 2)]
        public decimal NHoehe { get; set; }
        [Column("n_belegung")]
        [Precision(5, 2)]
        public decimal NBelegung { get; set; }
        [Column("n_verschnitt")]
        [Precision(5, 2)]
        public decimal NVerschnitt { get; set; }
        [Column("n_typ_id")]
        public int NTypId { get; set; }
        [Column("n_lieferant_id")]
        public int NLieferantId { get; set; }
        [Column("n_artikel_id")]
        public int NArtikelId { get; set; }
        /// <summary>
        /// FichteTanne=1, Eiche, Buche, Sperrholz=10, OSB3, Spanplatte
        /// </summary>
        [Column("n_mattyp_id")]
        public int NMattypId { get; set; }
        [Column("n_behandlungsart_id")]
        public int NBehandlungsartId { get; set; }
        [Column("n_holzmasse")]
        [Precision(25, 8)]
        public decimal NHolzmasse { get; set; }
        /// <summary>
        /// Qubikmeter
        /// </summary>
        [Column("n_qm_3")]
        [Precision(25, 8)]
        public decimal NQm3 { get; set; }
        /// <summary>
        /// Quadratmeter
        /// </summary>
        [Column("n_qm_2")]
        [Precision(25, 8)]
        public decimal NQm2 { get; set; }
        [Column("n_preis")]
        [Precision(25, 4)]
        public decimal NPreis { get; set; }
        /// <summary>
        /// 1=Standardwert,
        /// 2=Allgemein, 4=Manuell
        /// </summary>
        [Column("n_preis_source")]
        public int? NPreisSource { get; set; }
        [Column("n_preis_pro")]
        [Precision(10, 2)]
        public decimal? NPreisPro { get; set; }
        [Column("n_preis_pro_einheit_id")]
        public int? NPreisProEinheitId { get; set; }
        [Column("m_bemerkung", TypeName = "mediumtext")]
        public string MBemerkung { get; set; }
        [Column("d_created", TypeName = "timestamp")]
        public DateTime DCreated { get; set; }
    }
}