// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    [Table("t_katalog_cs")]
    [Index("KatId", Name = "idx_kat_id")]
    [Index("KatText", "KatId", Name = "idx_kat_text_kat_id")]
    public partial class TKatalogC
    {
        [Key]
        [Column("kat_grp")]
        public int KatGrp { get; set; }
        [Key]
        [Column("kat_id")]
        public int KatId { get; set; }
        [Column("kat_text")]
        [StringLength(80)]
        public string KatText { get; set; }
        [Column("kat_kurz_text")]
        [StringLength(20)]
        public string KatKurzText { get; set; }
        [Column("d_geloescht")]
        public DateOnly? DGeloescht { get; set; }
        [Column("kat_image_1")]
        public byte[] KatImage1 { get; set; }
        [Column("n_internal")]
        public bool? NInternal { get; set; }
        [Column("n_zipped")]
        public bool NZipped { get; set; }
    }
}