// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Liste der Lagerknathölzer. Wird gelöstcht, wenn die Materialwirtschaft existiert.
    /// </summary>
    [Table("t_khlager")]
    [Index("KhlBehandlsart", Name = "idx_khl_behandlsart")]
    public partial class TKhlager
    {
        [Key]
        [Column("khl_id")]
        public int KhlId { get; set; }
        [Column("khl_h")]
        public int KhlH { get; set; }
        [Column("khl_b")]
        public int KhlB { get; set; }
        [Column("khl_l")]
        public int KhlL { get; set; }
        /// <summary>
        /// kat_grp=5
        /// </summary>
        [Column("khl_behandlsart")]
        public int KhlBehandlsart { get; set; }
    }
}