// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Liste der Kanthölzer die zugekauft werden können und dem Flag in welcher Liste das Kantholz angezeigt wird.
    /// </summary>
    [Table("t_khzukauf")]
    [Index("KhzBh", Name = "IDX_BH")]
    [Index("KhzDh", Name = "IDX_DH")]
    [Index("KhzGk", Name = "IDX_GK")]
    [Index("KhzLk", Name = "IDX_LK")]
    [Index("KhzQk", Name = "IDX_QK")]
    [Index("KhzRh", Name = "IDX_RH")]
    [Index("KhzSb", Name = "IDX_SB")]
    [Index("KhzSt", Name = "IDX_ST")]
    public partial class TKhzukauf
    {
        [Key]
        [Column("khz_id")]
        public int KhzId { get; set; }
        [Column("khz_h")]
        public int KhzH { get; set; }
        [Column("khz_b")]
        public int KhzB { get; set; }
        /// <summary>
        /// 1=wird in der Liste de Längskufen angezeigt
        /// </summary>
        [Column("khz_lk")]
        public int? KhzLk { get; set; }
        /// <summary>
        /// 1=wird in der Liste de Querkufen angezeigt
        /// </summary>
        [Column("khz_qk")]
        public int? KhzQk { get; set; }
        /// <summary>
        /// 1=wird in der Liste deGleitkufen angezeigt
        /// </summary>
        [Column("khz_gk")]
        public int? KhzGk { get; set; }
        /// <summary>
        /// 1=wird in der Liste der Bohrhölzer angezeigt
        /// </summary>
        [Column("khz_bh")]
        public int? KhzBh { get; set; }
        /// <summary>
        /// 1=wird in der Liste der Steher angezeigt
        /// </summary>
        [Column("khz_st")]
        public int? KhzSt { get; set; }
        /// <summary>
        /// 1=wird in der Liste der Deckelhölzer angezeigt
        /// </summary>
        [Column("khz_dh")]
        public int? KhzDh { get; set; }
        /// <summary>
        /// 1=wird in der Liste der Rahmen angezeigt
        /// </summary>
        [Column("khz_rh")]
        public int? KhzRh { get; set; }
        /// <summary>
        /// Schiebebretter
        /// </summary>
        [Column("khz_sb")]
        public int? KhzSb { get; set; }
        [Column("khz_bp")]
        public bool? KhzBp { get; set; }
        /// <summary>
        /// Zeigt an, ob die Lk standardmäßig flach statt hochkant vorbelegt werden
        /// </summary>
        [Column("khz_lk_flach")]
        public bool? KhzLkFlach { get; set; }
    }
}