// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// KnowHow Datenbank. Beschreibung von speziellen Prozessen die mit Suchbegriffen und Verweisen auf andere Objekte hinterlegt werden.
    /// </summary>
    [Table("t_know_how")]
    public partial class TKnowHow
    {
        [Key]
        [Column("n_id")]
        public int NId { get; set; }
        [Column("c_bezeichnung")]
        [StringLength(80)]
        public string CBezeichnung { get; set; }
        [Column("m_beschreibung", TypeName = "mediumtext")]
        public string MBeschreibung { get; set; }
        [Column("d_created", TypeName = "datetime")]
        public DateTime DCreated { get; set; }
        [Column("n_user_id")]
        public int NUserId { get; set; }
    }
}