// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Details zur Artikel-Kunden Beziehung
    /// </summary>
    [Table("t_kundeartikel")]
    [Index("NArtikelId", Name = "idx_n_artikel_id")]
    [Index("NKundeId", Name = "idx_n_kunde_id")]
    public partial class TKundeartikel
    {
        [Key]
        [Column("n_id")]
        public int NId { get; set; }
        [Column("n_kunde_id")]
        public int NKundeId { get; set; }
        [Column("n_artikel_id")]
        public int NArtikelId { get; set; }
        [Column("c_k_artikel_name")]
        [StringLength(150)]
        public string CKArtikelName { get; set; }
        [Column("c_artikel_nr")]
        [StringLength(30)]
        public string CArtikelNr { get; set; }
        [Column("n_mindest_bestand")]
        public float? NMindestBestand { get; set; }
        [Column("n_maximal_bestand")]
        public float? NMaximalBestand { get; set; }
        [Column("m_bemerkung", TypeName = "mediumtext")]
        public string MBemerkung { get; set; }
        [Column("n_verkaufs_preis")]
        [Precision(19, 2)]
        public decimal? NVerkaufsPreis { get; set; }
        [Column("n_einheit")]
        public int NEinheit { get; set; }
        [Column("n_gesperrt")]
        public bool? NGesperrt { get; set; }
        [Column("n_preisanpassung_inc")]
        public bool? NPreisanpassungInc { get; set; }
        [Column("d_geloescht", TypeName = "datetime")]
        public DateTime? DGeloescht { get; set; }
    }
}