// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Kundenabhängige Abstand der Längskufen mit Angabe der Anzahl
    /// </summary>
    [Table("t_kunde_lk_abstand")]
    public partial class TKundeLkAbstand
    {
        [Key]
        [Column("n_kunde_id")]
        public int NKundeId { get; set; }
        [Key]
        [Column("n_id")]
        public int NId { get; set; }
        [Column("n_ab")]
        public int NAb { get; set; }
        [Column("n_anzahl")]
        public int NAnzahl { get; set; }
    }
}