// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Kunden- und gewichtsabhängige Längskufendimension 
    /// </summary>
    [Table("t_kunde_kg_dim")]
    public partial class TKundeKgDim
    {
        [Key]
        [Column("n_kunde_id")]
        public int NKundeId { get; set; }
        [Key]
        [Column("n_id")]
        public int NId { get; set; }
        [Column("n_ab_kg")]
        public int NAbKg { get; set; }
        [Column("c_lk_dim")]
        [StringLength(10)]
        public string CLkDim { get; set; }
        [Required]
        [Column("n_lk_hochkant")]
        public bool? NLkHochkant { get; set; }
    }
}