// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Kunden-Preisdefinition für bestimmtes Material. Der Preis definiert sich über verschiedene Eigenschaften.
    /// </summary>
    [Table("t_kunde_maschine_rasterpreis")]
    public partial class TKundeMaschineRasterprei
    {
        [Key]
        [Column("n_id")]
        public long NId { get; set; }
        [Column("n_kunde_id")]
        public int NKundeId { get; set; }
        [Column("n_zoll")]
        public int? NZoll { get; set; }
        [Column("n_laenge")]
        public int? NLaenge { get; set; }
        [Column("n_breite")]
        public int? NBreite { get; set; }
        [Column("n_hoehe")]
        public int? NHoehe { get; set; }
        [Column("n_gewicht")]
        public int? NGewicht { get; set; }
        [Column("n_vp_see_preis")]
        public float? NVpSeePreis { get; set; }
        [Column("n_vp_bahn_preis")]
        public float? NVpBahnPreis { get; set; }
        [Column("n_vp_zuschlag_korrosionsschutz_preis")]
        public float? NVpZuschlagKorrosionsschutzPreis { get; set; }
    }
}