// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Lade und Entladestellen die im Lieferschein oder Transportauftrag ausgewählt werden können
    /// </summary>
    [Table("t_ladeentladestellen")]
    public partial class TLadeentladestellen
    {
        [Key]
        [Column("n_id")]
        public int NId { get; set; }
        [Column("c_firma")]
        [StringLength(50)]
        public string CFirma { get; set; }
        [Column("c_adr_zusatz_1")]
        [StringLength(45)]
        public string CAdrZusatz1 { get; set; }
        [Column("c_strasse")]
        [StringLength(40)]
        public string CStrasse { get; set; }
        [Column("c_strassenr")]
        [StringLength(20)]
        public string CStrassenr { get; set; }
        [Column("c_plz")]
        [StringLength(15)]
        public string CPlz { get; set; }
        [Column("c_ort")]
        [StringLength(40)]
        public string COrt { get; set; }
        [Column("n_staat_id")]
        public int? NStaatId { get; set; }
        /// <summary>
        /// Ist nur gfuellt wenn Kundenbeziehung
        /// </summary>
        [Column("n_firma_id")]
        public int? NFirmaId { get; set; }
        [Required]
        [Column("n_entladestelle")]
        public bool? NEntladestelle { get; set; }
        [Required]
        [Column("n_ladestelle")]
        public bool? NLadestelle { get; set; }
        [Column("d_created", TypeName = "datetime")]
        public DateTime DCreated { get; set; }
        [Column("n_user_id")]
        public int NUserId { get; set; }
    }
}