// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Kunden-Wareneingangskosten in Abhängigkeit vom Typ wie Europalette, Karton, Kiste
    /// </summary>
    [Table("t_lager_kunde_preise_wareneingang")]
    [Index("NKundeId", Name = "IDX_KUNDE_ID")]
    public partial class TLagerKundePreiseWareneingang
    {
        [Key]
        [Column("n_id")]
        public int NId { get; set; }
        [Column("n_kunde_id")]
        public int NKundeId { get; set; }
        /// <summary>
        /// kat_grp=10
        /// </summary>
        [Column("n_typ_id")]
        public int NTypId { get; set; }
        [Column("n_preis")]
        [Precision(19, 2)]
        public decimal NPreis { get; set; }
        [Column("c_preis_text")]
        [StringLength(45)]
        public string CPreisText { get; set; }
    }
}