// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Vorhandene Lageplätze, welche dem t_lager untergeordnet sind.
    /// </summary>
    [Table("t_lagerplatz")]
    [Index("NLagerId", "CName", Name = "IDX_UNIQUE_LAGER_NAME", IsUnique = true)]
    [Index("CName", Name = "idx_c_name")]
    [Index("NLagerId", Name = "idx_n_lager_id")]
    public partial class TLagerplatz
    {
        [Key]
        [Column("n_id")]
        public int NId { get; set; }
        [Column("n_lager_id")]
        public int? NLagerId { get; set; }
        [Column("c_name")]
        [StringLength(50)]
        public string CName { get; set; }
        [Column("c_beschreibung")]
        [StringLength(150)]
        public string CBeschreibung { get; set; }
        [Column("n_laenge")]
        public int? NLaenge { get; set; }
        [Column("n_breite")]
        public int? NBreite { get; set; }
        [Column("n_hoehe")]
        public int? NHoehe { get; set; }
        [Column("n_max_belastung")]
        public int? NMaxBelastung { get; set; }
        [Column("m_bemerkung", TypeName = "mediumtext")]
        public string MBemerkung { get; set; }
        [Column("d_geloescht", TypeName = "datetime")]
        public DateTime? DGeloescht { get; set; }
        [Column("n_sperrlager")]
        public bool NSperrlager { get; set; }
    }
}