// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Berechnete Lagerkosten für einen  Kunden in einem Zeitraum. Die Einzelpositionen sind in der Tabelle t_lager_kosten_posten
    /// </summary>
    [Table("t_lager_kosten")]
    [Index("NKundeId", Name = "IDX_KUNDE")]
    public partial class TLagerKosten
    {
        [Key]
        [Column("n_id")]
        public int NId { get; set; }
        [Column("n_kunde_id")]
        public int NKundeId { get; set; }
        [Column("d_von", TypeName = "datetime")]
        public DateTime DVon { get; set; }
        [Column("d_bis", TypeName = "datetime")]
        public DateTime DBis { get; set; }
        [Column("c_titel")]
        [StringLength(45)]
        public string CTitel { get; set; }
    }
}