// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Lagerkosteberechnung der einzelnen Positionen im Lager
    /// </summary>
    [Table("t_lager_kosten_posten")]
    public partial class TLagerKostenPosten
    {
        [Key]
        [Column("n_main_id")]
        public int NMainId { get; set; }
        [Key]
        [Column("n_id")]
        public int NId { get; set; }
        [Column("n_lager_id")]
        public int NLagerId { get; set; }
        [Column("n_lagerort_id")]
        public int NLagerortId { get; set; }
        /// <summary>
        /// kat_grp=63
        /// </summary>
        [Column("n_berechnung_nach_id")]
        public int NBerechnungNachId { get; set; }
        [Column("n_wert")]
        [Precision(19, 4)]
        public decimal NWert { get; set; }
        [Column("n_zuwegung")]
        [Precision(19, 4)]
        public decimal? NZuwegung { get; set; }
        [Column("n_einzelpreis")]
        [Precision(19, 4)]
        public decimal NEinzelpreis { get; set; }
        [Column("n_kosten")]
        [Precision(19, 2)]
        public decimal NKosten { get; set; }
        [Column("n_kosten_zuwegung")]
        [Precision(19, 2)]
        public decimal? NKostenZuwegung { get; set; }
        [Column("c_kommisions_nr")]
        [StringLength(50)]
        public string CKommisionsNr { get; set; }
        [Column("c_bestell_nr")]
        [StringLength(100)]
        public string CBestellNr { get; set; }
        [Column("c_weingangs_nr")]
        [StringLength(20)]
        public string CWeingangsNr { get; set; }
        [Column("c_artikel_nr")]
        [StringLength(25)]
        public string CArtikelNr { get; set; }
        [Column("c_verpackungs_typ")]
        [StringLength(30)]
        public string CVerpackungsTyp { get; set; }
        [Column("c_packstueck_nr")]
        [StringLength(15)]
        public string CPackstueckNr { get; set; }
        [Column("d_eingelagert")]
        public DateOnly? DEingelagert { get; set; }
        [Column("c_auftrag_nr")]
        [StringLength(50)]
        public string CAuftragNr { get; set; }
        [Column("n_auftrag_id")]
        public long? NAuftragId { get; set; }
        [Column("d_ausgelagert")]
        public DateOnly? DAusgelagert { get; set; }
    }
}