// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Eigenes Lager. Unter derm Lager gibt es noch die Lagerplätze.
    /// </summary>
    [Table("t_lager")]
    [Index("CName", Name = "idx_c_name", IsUnique = true)]
    public partial class TLager
    {
        [Key]
        [Column("n_id")]
        public int NId { get; set; }
        [Column("c_name")]
        [StringLength(50)]
        public string CName { get; set; }
        [Column("c_beschreibung")]
        [StringLength(150)]
        public string CBeschreibung { get; set; }
        [Column("m_bemerkung", TypeName = "mediumtext")]
        public string MBemerkung { get; set; }
        [Column("d_geloescht", TypeName = "datetime")]
        public DateTime? DGeloescht { get; set; }
    }
}