// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Lagerplatzpreise pro Kunde
    /// </summary>
    [Table("t_lager_kunde_preise_lagerplatz")]
    public partial class TLagerKundePreiseLagerplatz
    {
        [Key]
        [Column("n_kunde_id")]
        public int NKundeId { get; set; }
        [Key]
        [Column("n_lager_id")]
        public int NLagerId { get; set; }
        [Key]
        [Column("n_lagerplatz_id")]
        public int NLagerplatzId { get; set; }
        [Column("n_preis")]
        [Precision(19, 2)]
        public decimal NPreis { get; set; }
        [Column("n_berechnungs_einheit_id")]
        public int NBerechnungsEinheitId { get; set; }
        [Column("c_rechnungs_text")]
        [StringLength(30)]
        public string CRechnungsText { get; set; }
    }
}