// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Kopfdaten des Lieferscheins
    /// </summary>
    [Table("t_lieferschein")]
    [Index("NLieferscheinId", "DLieferTermin", Name = "IDX_UNIQUE_AUFTAG_LIEFERSCHEIN_TERMIN")]
    public partial class TLieferschein
    {
        [Key]
        [Column("n_id")]
        public int NId { get; set; }
        [Column("n_kunde_id")]
        public int NKundeId { get; set; }
        [Column("n_lieferschein_id")]
        public int NLieferscheinId { get; set; }
        [Column("c_nr")]
        [StringLength(20)]
        public string CNr { get; set; }
        /// <summary>
        /// Eindeutig mit lieferschein Id
        /// </summary>
        [Column("d_liefer_termin")]
        public DateOnly DLieferTermin { get; set; }
        /// <summary>
        /// Lieferschein Ausstellungsdatum
        /// </summary>
        [Column("d_lieferschein_datum")]
        public DateOnly? DLieferscheinDatum { get; set; }
        [Column("c_adr_firma")]
        [StringLength(50)]
        public string CAdrFirma { get; set; }
        [Column("c_adr_firma_zusatz")]
        [StringLength(45)]
        public string CAdrFirmaZusatz { get; set; }
        [Column("c_adr_feld_1")]
        [StringLength(45)]
        public string CAdrFeld1 { get; set; }
        [Column("c_adr_feld_2")]
        [StringLength(45)]
        public string CAdrFeld2 { get; set; }
        [Column("c_adr_plz_ort")]
        [StringLength(45)]
        public string CAdrPlzOrt { get; set; }
        [Column("n_adr_lief_stast_id")]
        public int? NAdrLiefStastId { get; set; }
        [Column("d_abhol_datum")]
        public DateOnly? DAbholDatum { get; set; }
        [Column("c_abhol_lkw_kennz")]
        [StringLength(25)]
        public string CAbholLkwKennz { get; set; }
        [Column("c_abhol_fahrer")]
        [StringLength(50)]
        public string CAbholFahrer { get; set; }
        [Column("c_abhol_spedition")]
        [StringLength(75)]
        public string CAbholSpedition { get; set; }
        [Column("m_bemerkung", TypeName = "mediumtext")]
        public string MBemerkung { get; set; }
        [Column("c_adr_lief_firma")]
        [StringLength(45)]
        public string CAdrLiefFirma { get; set; }
        [Column("c_adr_lief_firma_zusatz")]
        [StringLength(40)]
        public string CAdrLiefFirmaZusatz { get; set; }
        [Column("c_adr_lief_feld_1")]
        [StringLength(45)]
        public string CAdrLiefFeld1 { get; set; }
        [Column("c_adr_lief_feld_2")]
        [StringLength(45)]
        public string CAdrLiefFeld2 { get; set; }
        [Column("n_andere_lief_anschrift")]
        public bool NAndereLiefAnschrift { get; set; }
        [Column("c_adr_lief_plz_ort")]
        [StringLength(45)]
        public string CAdrLiefPlzOrt { get; set; }
        /// <summary>
        /// Zeit wann Lieferschein gedruckt wurde
        /// </summary>
        [Column("d_gedruckt", TypeName = "datetime")]
        public DateTime? DGedruckt { get; set; }
        [Column("n_ab_werk")]
        public bool? NAbWerk { get; set; }
        [Column("d_created", TypeName = "datetime")]
        public DateTime? DCreated { get; set; }
        [Column("n_user_id")]
        public int? NUserId { get; set; }
        /// <summary>
        /// ID des Benutzers der den Datensatz erstellt hat.
        /// </summary>
        [Column("n_user_id_erstellt")]
        public int? NUserIdErstellt { get; set; }
        /// <summary>
        /// ID des Benutzers der den Datensatz geändert hat.
        /// </summary>
        [Column("n_user_id_geaendert")]
        public int? NUserIdGeaendert { get; set; }
        /// <summary>
        /// Datum wann der Datensatz geändert wurde
        /// </summary>
        [Column("d_geaendert_am", TypeName = "datetime")]
        public DateTime? DGeaendertAm { get; set; }
    }
}