// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Mahnliste. Die Mahnungen der Liste sind in Tabelle t_mahnungen
    /// </summary>
    [Table("t_mahnung")]
    public partial class TMahnung
    {
        [Key]
        [Column("n_id")]
        public int NId { get; set; }
        [Column("d_created", TypeName = "datetime")]
        public DateTime DCreated { get; set; }
    }
}