// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Die Liste der Mahnungen zu der Mahnliste und der entsprechenden Rechnung und der entsprechenden Massnahme, wie z.B. Mahnstufe erhöht.
    /// </summary>
    [Table("t_mahnungen")]
    public partial class TMahnungen
    {
        /// <summary>
        /// t_mahnung.n_id
        /// </summary>
        [Key]
        [Column("n_mahnung_id")]
        public int NMahnungId { get; set; }
        /// <summary>
        /// t_rechnung.n_id
        /// </summary>
        [Key]
        [Column("n_rechnung_id")]
        public int NRechnungId { get; set; }
        [Column("n_mahnstufe")]
        public int NMahnstufe { get; set; }
        /// <summary>
        /// telefonische Mahnstufe
        /// </summary>
        [Column("n_mahnstufe_tel")]
        public int NMahnstufeTel { get; set; }
        [Column("d_zahlungsziel")]
        public DateOnly? DZahlungsziel { get; set; }
        [Column("n_rechnungs_mahnstufe")]
        public int NRechnungsMahnstufe { get; set; }
        [Column("n_rechnungs_mahnstufe_tel")]
        public int NRechnungsMahnstufeTel { get; set; }
        [Column("n_mahngebuehr")]
        [Precision(19, 2)]
        public decimal? NMahngebuehr { get; set; }
        [Column("d_rechnungs_zahlungsziel")]
        public DateOnly DRechnungsZahlungsziel { get; set; }
        /// <summary>
        /// Rechnung liegt beim Rechtsanwalt
        /// </summary>
        [Column("n_rechnungs_rechtsanwalt")]
        public bool NRechnungsRechtsanwalt { get; set; }
        [Column("d_rechnungs_rechtsanwalt_uebergeben", TypeName = "datetime")]
        public DateTime? DRechnungsRechtsanwaltUebergeben { get; set; }
        [Column("m_bemerkung", TypeName = "mediumtext")]
        public string MBemerkung { get; set; }
        [Column("d_gedruckt", TypeName = "datetime")]
        public DateTime? DGedruckt { get; set; }
        [Column("n_kunde_id")]
        public int NKundeId { get; set; }
        [Column("n_user_id")]
        public int NUserId { get; set; }
        [Column("n_rechtsanwalt")]
        public bool NRechtsanwalt { get; set; }
        [Column("d_rechtsanwalt_uebergeben", TypeName = "datetime")]
        public DateTime? DRechtsanwaltUebergeben { get; set; }
        [Column("n_adr_land_id")]
        public int? NAdrLandId { get; set; }
        [Column("c_adr_firma")]
        [StringLength(60)]
        public string CAdrFirma { get; set; }
        [Column("c_adr_feld_1")]
        [StringLength(45)]
        public string CAdrFeld1 { get; set; }
        [Column("c_adr_feld_2")]
        [StringLength(45)]
        public string CAdrFeld2 { get; set; }
        [Column("c_adr_plz_ort")]
        [StringLength(45)]
        public string CAdrPlzOrt { get; set; }
    }
}