// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    [Table("t_material_lager_history")]
    [MySqlCharSet("utf8mb3")]
    [MySqlCollation("utf8_general_ci")]
    public partial class TMaterialLagerHistory
    {
        [Key]
        [Column("c_id")]
        [StringLength(45)]
        public string CId { get; set; }
        [Column("n_lagerplatz_id")]
        public int NLagerplatzId { get; set; }
        [Column("n_artikel_id")]
        public int NArtikelId { get; set; }
        [Column("n_einheit_id")]
        public int NEinheitId { get; set; }
        [Column("d_date", TypeName = "datetime")]
        public DateTime DDate { get; set; }
        /// <summary>
        /// 1=Eingang-WE, 2=Ausgang, 3=Korrektur-WE, 4=Korrektur, 5=Korrektur-LS
        /// </summary>
        [Column("n_action_id")]
        public int NActionId { get; set; }
        [Column("n_anzahl")]
        [Precision(19, 2)]
        public decimal NAnzahl { get; set; }
        [Column("n_preis")]
        [Precision(19, 4)]
        public decimal NPreis { get; set; }
        /// <summary>
        /// user which die the update
        /// </summary>
        [Column("n_user_id")]
        public long? NUserId { get; set; }
    }
}