// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Material welcehs aus dem Lager zur Kostenstelle gebucht wurde
    /// </summary>
    [Table("t_material_kostenstelle")]
    [Index("DZuweisung", Name = "IDX_MATERIAL_DATUM")]
    public partial class TMaterialKostenstelle
    {
        [Key]
        [Column("c_id")]
        [StringLength(45)]
        public string CId { get; set; }
        [Column("n_lagerplatz_id")]
        public int NLagerplatzId { get; set; }
        [Column("n_artikel_id")]
        public int NArtikelId { get; set; }
        [Column("n_einheit_id")]
        public int NEinheitId { get; set; }
        [Column("n_preis")]
        [Precision(19, 3)]
        public decimal? NPreis { get; set; }
        [Column("n_anzahl")]
        [Precision(25, 3)]
        public decimal NAnzahl { get; set; }
        [Column("d_zuweisung", TypeName = "datetime")]
        public DateTime DZuweisung { get; set; }
        [Column("n_kostenstelle_id")]
        public int NKostenstelleId { get; set; }
    }
}