// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Lager der Materialwirtschaft
    /// </summary>
    [Table("t_material_lager")]
    public partial class TMaterialLager
    {
        [Key]
        [Column("c_id")]
        [StringLength(45)]
        public string CId { get; set; }
        [Column("n_lagerplatz_id")]
        public int NLagerplatzId { get; set; }
        /// <summary>
        /// t_wareneingangartikel.n_id
        /// </summary>
        [Column("n_we_artikel_id")]
        public int? NWeArtikelId { get; set; }
        [Column("n_artikel_id")]
        public int NArtikelId { get; set; }
        [Column("n_pack_einheit_id")]
        public int NPackEinheitId { get; set; }
        [Column("n_pack_faktor_einheit_preiseinheit")]
        [Precision(25, 3)]
        public decimal NPackFaktorEinheitPreiseinheit { get; set; }
        [Column("n_pack_anzahl")]
        [Precision(25, 3)]
        public decimal NPackAnzahl { get; set; }
        [Column("n_preis_einheit_id")]
        public int NPreisEinheitId { get; set; }
        [Column("n_preis")]
        [Precision(19, 3)]
        public decimal? NPreis { get; set; }
        [Column("d_created", TypeName = "timestamp")]
        public DateTime? DCreated { get; set; }
        [Column("d_updated", TypeName = "timestamp")]
        public DateTime? DUpdated { get; set; }
    }
}