// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Logpuch für die Akquise von Neukunden
    /// </summary>
    [Table("t_neukunde_logbuch")]
    [Index("NFirmaId", Name = "IDX_FIRMA_ID")]
    public partial class TNeukundeLogbuch
    {
        [Key]
        [Column("n_firma_id")]
        public int NFirmaId { get; set; }
        [Key]
        [Column("n_id")]
        public int NId { get; set; }
        [Column("d_date", TypeName = "datetime")]
        public DateTime DDate { get; set; }
        [Column("c_subject")]
        [StringLength(30)]
        public string CSubject { get; set; }
        [Column("m_bem", TypeName = "mediumtext")]
        public string MBem { get; set; }
        [Column("n_user_id")]
        public int? NUserId { get; set; }
    }
}