// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Niederlassungen die im Cratemaker Admin konfiguriert werden
    /// </summary>
    [Table("t_niederlassung")]
    public partial class TNiederlassung
    {
        [Key]
        [Column("n_id")]
        public int NId { get; set; }
        [Column("c_kurz_name")]
        [StringLength(10)]
        public string CKurzName { get; set; }
        [Column("c_name")]
        [StringLength(25)]
        public string CName { get; set; }
        [Column("c_plz")]
        [StringLength(15)]
        public string CPlz { get; set; }
        [Column("c_strassennr")]
        [StringLength(20)]
        public string CStrassennr { get; set; }
        [Column("c_strasse")]
        [StringLength(40)]
        public string CStrasse { get; set; }
        [Column("c_ort")]
        [StringLength(40)]
        public string COrt { get; set; }
        [Column("d_geloescht", TypeName = "datetime")]
        public DateTime? DGeloescht { get; set; }
    }
}