// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Wird für die Generierung einer nächsten Nr benötigt
    /// </summary>
    [Table("t_nr")]
    public partial class TNr
    {
        [Key]
        [Column("n_typ_id")]
        public int NTypId { get; set; }
        [Key]
        [Column("c_group")]
        [StringLength(45)]
        public string CGroup { get; set; }
        [Key]
        [Column("n_id")]
        public int NId { get; set; }
    }
}