// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Verwaltung der fortlaufenden Nummer der gebraucht Packmittel
    /// </summary>
    [Table("t_packmittel_gebraucht_details")]
    [Index("NId", "VerpTyp", "VerpNr", "VerpKundeId", "VerpPrjId", "VerpAuftragId", "VerpAktiv", "VerpSeem", "VerpVerpacken", "VerpGedruckt", "VerpAnfragePreis", "VerpAnzahl", "VerpMattypId", Name = "IDX_GVERP_NO_REF")]
    [Index("NId", "NTypId", "VerpPrjId", "VerpLandId", "VerpKundeId", "VerpNr", "VerpAuftragId", Name = "IDX_GVERP_TYP")]
    public partial class TPackmittelGebrauchtDetail
    {
        [Key]
        [Column("n_id")]
        public int NId { get; set; }
        [Column("n_typ_id")]
        public int? NTypId { get; set; }
        [Column("verp_nr")]
        [StringLength(50)]
        public string VerpNr { get; set; }
        [Column("verp_typ")]
        public int? VerpTyp { get; set; }
        [Column("verp_anzahl")]
        public int? VerpAnzahl { get; set; }
        [Column("verp_termin")]
        public DateOnly? VerpTermin { get; set; }
        [Column("verp_gedruckt", TypeName = "datetime")]
        public DateTime? VerpGedruckt { get; set; }
        [Column("verp_baufeld")]
        [StringLength(50)]
        public string VerpBaufeld { get; set; }
        [Column("verp_land_id")]
        public int? VerpLandId { get; set; }
        [Column("verp_kalender_id")]
        [StringLength(45)]
        public string VerpKalenderId { get; set; }
        [Column("verp_auftrag_id")]
        public int? VerpAuftragId { get; set; }
        [Column("verp_position")]
        [StringLength(25)]
        public string VerpPosition { get; set; }
        [Column("verp_kunden_auftragsnr")]
        [StringLength(25)]
        public string VerpKundenAuftragsnr { get; set; }
        [Column("verp_info", TypeName = "mediumtext")]
        public string VerpInfo { get; set; }
        [Column("verp_datum")]
        public DateOnly? VerpDatum { get; set; }
        [Column("verp_prj_id")]
        public int? VerpPrjId { get; set; }
        [Column("verp_mattyp_id")]
        public int? VerpMattypId { get; set; }
        [Column("verp_kunde_id")]
        public int? VerpKundeId { get; set; }
        [Column("verp_verpacken")]
        public bool? VerpVerpacken { get; set; }
        [Column("verp_seem")]
        public bool? VerpSeem { get; set; }
        [Column("verp_schutzzeit")]
        public int? VerpSchutzzeit { get; set; }
        [Column("verp_folie_pe")]
        public bool? VerpFoliePe { get; set; }
        [Column("verp_folie_al")]
        public bool? VerpFolieAl { get; set; }
        [Column("verp_beipack_kg")]
        public int? VerpBeipackKg { get; set; }
        [Column("verp_folie_qm")]
        public int? VerpFolieQm { get; set; }
        [Column("verp_vci_hersteller_id")]
        public int? VerpVciHerstellerId { get; set; }
        [Column("verp_vci_produkt_id")]
        public int? VerpVciProduktId { get; set; }
        [Column("verp_vci_material_id")]
        public int? VerpVciMaterialId { get; set; }
        [Column("verp_vci_folie_pe")]
        public bool? VerpVciFoliePe { get; set; }
        [Column("verp_vci_folie_al")]
        public bool? VerpVciFolieAl { get; set; }
        [Column("verp_vci_folie_einwickeln")]
        public bool? VerpVciFolieEinwickeln { get; set; }
        [Column("verp_vci_folie_keine")]
        public bool? VerpVciFolieKeine { get; set; }
        [Column("verp_schrumpfhaube")]
        public bool? VerpSchrumpfhaube { get; set; }
        [Column("verp_anfrage_preis")]
        [Precision(19, 4)]
        public decimal? VerpAnfragePreis { get; set; }
        [Column("verp_anzahl_geliefert")]
        public int VerpAnzahlGeliefert { get; set; }
        [Column("verp_anzahl_verrechnet")]
        public int VerpAnzahlVerrechnet { get; set; }
        [Column("verp_anzahl_nicht_verrechenbar")]
        public int VerpAnzahlNichtVerrechenbar { get; set; }
        [Column("verp_anzahl_transportiert")]
        public int VerpAnzahlTransportiert { get; set; }
        [Column("verp_anzahl_auftragbestaet")]
        public int VerpAnzahlAuftragbestaet { get; set; }
        [Column("verp_anzahl_angeboten")]
        public int VerpAnzahlAngeboten { get; set; }
        [Column("verp_anzahl_verplant")]
        public int VerpAnzahlVerplant { get; set; }
        [Required]
        [Column("verp_aktiv")]
        public bool? VerpAktiv { get; set; }
        [Column("n_packmittel_gebraucht_eingang_id")]
        public int NPackmittelGebrauchtEingangId { get; set; }
        [Column("d_eingelagert")]
        public DateOnly? DEingelagert { get; set; }
        [Column("d_ausgelagert")]
        public DateOnly? DAusgelagert { get; set; }
        [Column("verp_lk_qk_verschrauben")]
        public bool? VerpLkQkVerschrauben { get; set; }
    }
}