// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Gebrauchte Packmittel zur Weiterverarbeitug - aktuell nicht mehr in Benutzung
    /// </summary>
    [Table("t_packmittel_gebraucht")]
    [Index("NPackmittelEingangId", Name = "IDX_EINGANG")]
    public partial class TPackmittelGebraucht
    {
        [Key]
        [Column("n_id")]
        public int NId { get; set; }
        [Column("n_packmittel_eingang_id")]
        public int NPackmittelEingangId { get; set; }
        [Column("n_material_id")]
        public int NMaterialId { get; set; }
        [Column("n_ispm")]
        public bool NIspm { get; set; }
        [Column("c_regestriernr")]
        [StringLength(30)]
        public string CRegestriernr { get; set; }
        [Column("n_laenge_i")]
        public int? NLaengeI { get; set; }
        [Column("n_laenge_a")]
        public int? NLaengeA { get; set; }
        [Column("n_breite_i")]
        public int? NBreiteI { get; set; }
        [Column("n_breite_a")]
        public int? NBreiteA { get; set; }
        [Column("n_hoehe_i")]
        public int? NHoeheI { get; set; }
        [Column("n_hoehe_a")]
        public int? NHoeheA { get; set; }
        [Column("n_gewicht_tara")]
        public int? NGewichtTara { get; set; }
        [Column("m_zustand_bemerkung", TypeName = "mediumtext")]
        public string MZustandBemerkung { get; set; }
        [Column("n_zustand_bewertung_id")]
        public int NZustandBewertungId { get; set; }
        [Column("c_lk_dim")]
        [StringLength(10)]
        public string CLkDim { get; set; }
        [Column("c_qk_dim")]
        [StringLength(10)]
        public string CQkDim { get; set; }
        [Column("c_gk_dim")]
        [StringLength(10)]
        public string CGkDim { get; set; }
        [Column("n_schnittholzboden")]
        public bool? NSchnittholzboden { get; set; }
        [Column("n_ohne_deckel")]
        public bool? NOhneDeckel { get; set; }
        [Column("n_decklagen_staerke")]
        public short? NDecklagenStaerke { get; set; }
        [Column("n_zwischenlage_staerke")]
        public short? NZwischenlageStaerke { get; set; }
        [Column("n_bodenlage_staerke")]
        public short? NBodenlageStaerke { get; set; }
        [Column("n_netto_gewicht")]
        public int? NNettoGewicht { get; set; }
    }
}