// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Werte zur Palette die vorbesetzt sind in Abhängigkeit vom Palettentyp
    /// </summary>
    [Table("t_paletteinitval")]
    public partial class TPaletteinitval
    {
        [Key]
        [Column("pa_typ")]
        public int PaTyp { get; set; }
        [Column("pa_alle_cb")]
        public int? PaAlleCb { get; set; }
        [Column("pa_alle_st")]
        public int? PaAlleSt { get; set; }
        [Column("pa_b_cb")]
        public int? PaBCb { get; set; }
        [Column("pa_b_st")]
        public int? PaBSt { get; set; }
        [Column("pa_b_mat")]
        public int? PaBMat { get; set; }
        [Column("pa_b_bart")]
        public int? PaBBart { get; set; }
        [Column("pa_kh_cb")]
        public int? PaKhCb { get; set; }
        [Column("pa_kh_mat")]
        public int? PaKhMat { get; set; }
        [Column("pa_kh_bart")]
        public int? PaKhBart { get; set; }
        [Column("pa_d_cb")]
        public int? PaDCb { get; set; }
        [Column("pa_d_st")]
        public int? PaDSt { get; set; }
        [Column("pa_d_mat")]
        public int? PaDMat { get; set; }
        [Column("pa_d_bart")]
        public int? PaDBart { get; set; }
        [Column("pa_d_d_cb")]
        public int? PaDDCb { get; set; }
        [Column("pa_z_cb")]
        public int? PaZCb { get; set; }
        [Column("pa_z_st")]
        public int? PaZSt { get; set; }
        [Column("pa_z_mat")]
        public int? PaZMat { get; set; }
        [Column("pa_z_bart")]
        public int? PaZBart { get; set; }
        [Column("pa_bl_b_fallende_cb")]
        public bool? PaBlBFallendeCb { get; set; }
        [Column("pa_bl_b_fallende_proz")]
        public int? PaBlBFallendeProz { get; set; }
        [Column("pa_bl_b_prismierte_cb")]
        public bool? PaBlBPrismierteCb { get; set; }
        [Column("pa_bl_b_brettbreite")]
        public int? PaBlBBrettbreite { get; set; }
        [Column("pa_bl_b_lueckenb_cb")]
        public bool? PaBlBLueckenbCb { get; set; }
        [Column("pa_bl_b_brettanzahl_cb")]
        public bool? PaBlBBrettanzahlCb { get; set; }
        [Column("pa_bl_b_lueckenb")]
        public int? PaBlBLueckenb { get; set; }
        [Column("pa_bl_b_brettanzahl")]
        public int? PaBlBBrettanzahl { get; set; }
        [Column("pa_bl_d_fallende_cb")]
        public bool? PaBlDFallendeCb { get; set; }
        [Column("pa_bl_d_fallende_proz")]
        public int? PaBlDFallendeProz { get; set; }
        [Column("pa_bl_d_prismierte_cb")]
        public bool? PaBlDPrismierteCb { get; set; }
        [Column("pa_bl_d_brettbreite")]
        public int? PaBlDBrettbreite { get; set; }
        [Column("pa_bl_d_lueckenb_cb")]
        public bool? PaBlDLueckenbCb { get; set; }
        [Column("pa_bl_d_brettanzahl_cb")]
        public bool? PaBlDBrettanzahlCb { get; set; }
        [Column("pa_bl_d_lueckenb")]
        public int? PaBlDLueckenb { get; set; }
        [Column("pa_bl_d_brettanzahl")]
        public int? PaBlDBrettanzahl { get; set; }
        [Column("pa_bl_z_brettbreite")]
        public int? PaBlZBrettbreite { get; set; }
        [Column("pa_bl_z_brettanzahl")]
        public int? PaBlZBrettanzahl { get; set; }
    }
}