// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Verbindung von Baufeld zum Kunden
    /// </summary>
    [Table("t_pbaufeldkunden")]
    [Index("PbaukKundeId", Name = "idx_pbauk_kunde_id")]
    public partial class TPbaufeldkunden
    {
        [Key]
        [Column("pbauk_pbau_id")]
        public int PbaukPbauId { get; set; }
        [Key]
        [Column("pbauk_kunde_id")]
        public int PbaukKundeId { get; set; }
    }
}