// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Kundenabhängie Phrasen für Dokumente wie Angebot, Ab, ..
    /// </summary>
    [Table("t_phrasen")]
    public partial class TPhrasen
    {
        [Key]
        [Column("n_kunde_id")]
        public int NKundeId { get; set; }
        [Key]
        [Column("n_id")]
        public int NId { get; set; }
        /// <summary>
        /// 1=Angebot, 2=Auftragsbestaetigung, 3=Fertigmeldung
        /// </summary>
        [Column("n_typ_id")]
        public int NTypId { get; set; }
        [Column("n_subtyp_id")]
        public int NSubtypId { get; set; }
        [Column("c_title")]
        [StringLength(30)]
        public string CTitle { get; set; }
        [Column("m_phrase", TypeName = "mediumtext")]
        public string MPhrase { get; set; }
    }
}