// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Plattenwerkstoffe mit Dim. Können bei den Kisten ausgewählt werden.
    /// </summary>
    [Table("t_plattenwerkstoffe")]
    public partial class TPlattenwerkstoffe
    {
        [Key]
        [Column("n_id")]
        public int NId { get; set; }
        /// <summary>
        /// kat_grp=1
        /// </summary>
        [Column("n_material_id")]
        public int NMaterialId { get; set; }
        [Column("c_bez")]
        [StringLength(15)]
        public string CBez { get; set; }
        [Column("n_laenge")]
        public int NLaenge { get; set; }
        [Column("n_breite")]
        public int NBreite { get; set; }
        [Column("n_staerke")]
        public int NStaerke { get; set; }
        /// <summary>
        /// is used for some cutting stations
        /// </summary>
        [Column("c_material_code")]
        [StringLength(15)]
        public string CMaterialCode { get; set; }
        /// <summary>
        /// is used for some cutting stations
        /// </summary>
        [Column("c_platten_code")]
        [StringLength(15)]
        public string CPlattenCode { get; set; }
    }
}