// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Zeigt pro Packstueck den Status. Das Mapping der status_x Spalte ist in der Tabelle t_proces_item definiert
    /// </summary>
    [Table("t_process_item_packaging")]
    public partial class TProcessItemPackaging
    {
        [Key]
        [Column("c_package_id")]
        [StringLength(45)]
        public string CPackageId { get; set; }
        [Column("c_process_status_1")]
        [StringLength(15)]
        public string CProcessStatus1 { get; set; }
        [Column("c_process_status_2")]
        [StringLength(15)]
        public string CProcessStatus2 { get; set; }
        [Column("c_process_status_3")]
        [StringLength(15)]
        public string CProcessStatus3 { get; set; }
        [Column("c_process_status_4")]
        [StringLength(15)]
        public string CProcessStatus4 { get; set; }
        [Column("c_process_status_5")]
        [StringLength(15)]
        public string CProcessStatus5 { get; set; }
        [Column("c_process_status_6")]
        [StringLength(15)]
        public string CProcessStatus6 { get; set; }
        [Column("c_process_status_7")]
        [StringLength(15)]
        public string CProcessStatus7 { get; set; }
        [Column("c_process_status_8")]
        [StringLength(15)]
        public string CProcessStatus8 { get; set; }
        [Column("c_process_status_9")]
        [StringLength(15)]
        public string CProcessStatus9 { get; set; }
        [Column("c_process_status_10")]
        [StringLength(15)]
        public string CProcessStatus10 { get; set; }
    }
}