// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Der übergeordnete Prozess der t_prozess_item wie z.B. Fertigung, Verpackung, ...
    /// </summary>
    [Table("t_process_type")]
    public partial class TProcessType
    {
        [Key]
        [Column("n_id")]
        public int NId { get; set; }
        [Required]
        [Column("c_name")]
        [StringLength(30)]
        [MySqlCharSet("utf8mb3")]
        [MySqlCollation("utf8_general_ci")]
        public string CName { get; set; }
        [Column("m_bem", TypeName = "mediumtext")]
        [MySqlCharSet("utf8mb3")]
        [MySqlCollation("utf8_general_ci")]
        public string MBem { get; set; }
    }
}