// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Allgemeine Eigenschaften von Cratemaker, die für alle MA gelten.
    /// </summary>
    [Table("t_properties_common")]
    public partial class TPropertiesCommon
    {
        [Key]
        [Column("c_property")]
        [StringLength(25)]
        public string CProperty { get; set; }
        [Column("c_value")]
        [StringLength(45)]
        public string CValue { get; set; }
    }
}