// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Planung einer Verladung
    /// </summary>
    [Table("t_raumstau_planung")]
    public partial class TRaumstauPlanung
    {
        [Key]
        [Column("n_id")]
        public int NId { get; set; }
        [Column("n_kunde_id")]
        public int NKundeId { get; set; }
        [Column("c_nr")]
        [StringLength(25)]
        public string CNr { get; set; }
        [Column("c_bezeichnung")]
        [StringLength(25)]
        public string CBezeichnung { get; set; }
        [Column("m_bemerkung", TypeName = "mediumtext")]
        public string MBemerkung { get; set; }
        [Column("m_bemerkung_intern", TypeName = "mediumtext")]
        public string MBemerkungIntern { get; set; }
        [Column("d_created", TypeName = "datetime")]
        public DateTime DCreated { get; set; }
        [Column("n_user_id")]
        public int NUserId { get; set; }
    }
}