// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Aufträge/Anfragen die bei eine Planung berücksichtigt werden
    /// </summary>
    [Table("t_raumstau_planung_auftrag")]
    public partial class TRaumstauPlanungAuftrag
    {
        [Key]
        [Column("n_planung_id")]
        public int NPlanungId { get; set; }
        [Key]
        [Column("n_auftrag_id")]
        public int NAuftragId { get; set; }
    }
}