// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Verknüpfung von Räumen und Projekten
    /// </summary>
    [Table("t_raumstau_rel_raume_objekte")]
    public partial class TRaumstauRelRaumeObjekte
    {
        [Key]
        [Column("n_objekt_planung_id")]
        public int NObjektPlanungId { get; set; }
        [Key]
        [Column("n_objekt_id")]
        public int NObjektId { get; set; }
        [Column("n_raum_planung_id")]
        public int NRaumPlanungId { get; set; }
        [Column("n_raum_id")]
        public int NRaumId { get; set; }
        /// <summary>
        /// X-Position innerhalb des Raums
        /// </summary>
        [Column("n_x")]
        public int NX { get; set; }
        /// <summary>
        /// Y-Position innerhalb des Raums
        /// </summary>
        [Column("n_y")]
        public int NY { get; set; }
        /// <summary>
        /// Z-Position innerhalb des Raums
        /// </summary>
        [Column("n_z")]
        public int NZ { get; set; }
        [Column("n_gedreht")]
        public bool NGedreht { get; set; }
    }
}