// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Eingangsrechnung mit Aufträgen verbinden, damit die Kosten bei der Nachkalkulation berücksichigt werden.
    /// </summary>
    [Table("t_rechnung_eingang_auftrag")]
    [Index("NAuftragId", Name = "IDX_RECHE_AUFTAG_ID")]
    [Index("NRechnungEingangId", Name = "IDX_RECHNUNG_EING_ID")]
    public partial class TRechnungEingangAuftrag
    {
        [Key]
        [Column("n_rechnung_eingang_id")]
        public int NRechnungEingangId { get; set; }
        [Key]
        [Column("n_id")]
        public int NId { get; set; }
        [Column("n_kunde_id")]
        public int NKundeId { get; set; }
        [Column("n_auftrag_id")]
        public int NAuftragId { get; set; }
        /// <summary>
        /// kat_grp = 61
        /// </summary>
        [Column("n_typ_id")]
        public int NTypId { get; set; }
        [Column("n_betrag")]
        [Precision(19, 2)]
        public decimal NBetrag { get; set; }
        [Column("c_bez")]
        [StringLength(45)]
        public string CBez { get; set; }
    }
}