// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Enthält Zahlungen zu einer Eingangsrechnung, sofern es für die Rechnung mehrere Zahlungen gibt.
    /// </summary>
    [Table("t_rechnung_eingang_zahlung")]
    [Index("NRechnungId", Name = "IDX_KUNDE_ID")]
    public partial class TRechnungEingangZahlung
    {
        [Key]
        [Column("n_rechnung_id")]
        public int NRechnungId { get; set; }
        [Key]
        [Column("n_id")]
        public int NId { get; set; }
        [Column("d_bezahlt_am", TypeName = "datetime")]
        public DateTime? DBezahltAm { get; set; }
        [Column("n_bezahlt_betrag")]
        [Precision(19, 2)]
        public decimal? NBezahltBetrag { get; set; }
        /// <summary>
        /// kat_grp=29
        /// </summary>
        [Column("n_bezahlt_art_id")]
        public int? NBezahltArtId { get; set; }
        [Column("n_bezahlt_skonto")]
        [Precision(7, 2)]
        public decimal? NBezahltSkonto { get; set; }
        [Column("m_bezahlt_bem", TypeName = "mediumtext")]
        public string MBezahltBem { get; set; }
    }
}