// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Verbindung von Kunden zum Cratemaker-Benutzer. Optional
    /// </summary>
    [Table("t_rel_firma_betreuer")]
    public partial class TRelFirmaBetreuer
    {
        [Key]
        [Column("n_firma_id")]
        public int NFirmaId { get; set; }
        [Key]
        [Column("n_user_id")]
        public int NUserId { get; set; }
    }
}