// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Verbindung von Firma zu Firma die auf die selbe Materialstruktur zugreifen.
    /// </summary>
    [Table("t_rel_firma_firma_material")]
    [Index("NFirmaIdDest", Name = "IDX_ID_DEST")]
    [Index("NFirmaIdSrc", Name = "IDX_ID_SRC")]
    public partial class TRelFirmaFirmaMaterial
    {
        [Key]
        [Column("n_firma_id_src")]
        public int NFirmaIdSrc { get; set; }
        [Key]
        [Column("n_firma_id_dest")]
        public int NFirmaIdDest { get; set; }
    }
}