// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// coordinates for robot when putting the items on nailing table
    /// </summary>
    [Table("t_robo_package_item_moving_data")]
    public partial class TRoboPackageItemMovingDatum
    {
        [Key]
        [Column("c_process_id")]
        [StringLength(45)]
        public string CProcessId { get; set; }
        [Key]
        [Column("n_id")]
        public int NId { get; set; }
        /// <summary>
        /// x position of corner wich is nearest to zero point in x direction
        /// </summary>
        [Column("n_x")]
        public int NX { get; set; }
        /// <summary>
        /// y position of corner wich is nearest to zero point in y direction
        /// </summary>
        [Column("n_y")]
        public int NY { get; set; }
        /// <summary>
        /// z position of corner wich is nearest to zero point in z direction
        /// </summary>
        [Column("n_z")]
        public int NZ { get; set; }
        /// <summary>
        /// order of items
        /// </summary>
        [Column("n_order")]
        public int NOrder { get; set; }
        /// <summary>
        /// length of item in x direction
        /// </summary>
        [Column("n_x_length")]
        public int NXLength { get; set; }
        /// <summary>
        /// length of item in y direction
        /// </summary>
        [Column("n_y_length")]
        public int NYLength { get; set; }
        /// <summary>
        /// length of item in z direction
        /// </summary>
        [Column("n_z_length")]
        public int NZLength { get; set; }
    }
}