// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Schnellkalkulation - Konfigurierte Berechnungsmethoden für die Verpackung
    /// </summary>
    [Table("t_schnell_kalk_initval_verpackung")]
    public partial class TSchnellKalkInitvalVerpackung
    {
        [Key]
        [Column("n_id")]
        public int NId { get; set; }
        [Column("n_kunde_id")]
        public int NKundeId { get; set; }
        [Column("n_is_standard")]
        public bool? NIsStandard { get; set; }
        [Column("c_name")]
        [StringLength(15)]
        public string CName { get; set; }
        [Column("n_verp_mat_pe_folie_ek")]
        [Precision(12, 5)]
        public decimal? NVerpMatPeFolieEk { get; set; }
        [Column("n_verp_mat_pe_folie_vk")]
        [Precision(12, 5)]
        public decimal? NVerpMatPeFolieVk { get; set; }
        [Column("n_verp_mat_pe_folie_verschnitt")]
        [Precision(7, 3)]
        public decimal? NVerpMatPeFolieVerschnitt { get; set; }
        [Column("n_verp_mat_al_folie_ek")]
        [Precision(12, 5)]
        public decimal? NVerpMatAlFolieEk { get; set; }
        [Column("n_verp_mat_al_folie_vk")]
        [Precision(12, 5)]
        public decimal? NVerpMatAlFolieVk { get; set; }
        [Column("n_verp_mat_al_folie_verschnitt")]
        [Precision(12, 5)]
        public decimal? NVerpMatAlFolieVerschnitt { get; set; }
        [Column("n_verp_mat_vci_pe_folie_ek")]
        [Precision(12, 5)]
        public decimal? NVerpMatVciPeFolieEk { get; set; }
        [Column("n_verp_mat_vci_pe_folie_vk")]
        [Precision(12, 5)]
        public decimal? NVerpMatVciPeFolieVk { get; set; }
        [Column("n_verp_mat_vci_pe_folie_verschnitt")]
        [Precision(12, 5)]
        public decimal? NVerpMatVciPeFolieVerschnitt { get; set; }
        [Column("n_verp_mat_vci_al_folie_ek")]
        [Precision(12, 5)]
        public decimal? NVerpMatVciAlFolieEk { get; set; }
        [Column("n_verp_mat_vci_al_folie_vk")]
        [Precision(12, 5)]
        public decimal? NVerpMatVciAlFolieVk { get; set; }
        [Column("n_verp_mat_vci_al_folie_verschnitt")]
        [Precision(12, 5)]
        public decimal? NVerpMatVciAlFolieVerschnitt { get; set; }
        [Column("n_verp_mat_vci_produkt_ek")]
        [Precision(12, 5)]
        public decimal? NVerpMatVciProduktEk { get; set; }
        [Column("n_verp_mat_vci_produkt_vk")]
        [Precision(12, 5)]
        public decimal? NVerpMatVciProduktVk { get; set; }
        [Column("n_verp_mat_schrumpfh_ek")]
        [Precision(12, 5)]
        public decimal? NVerpMatSchrumpfhEk { get; set; }
        [Column("n_verp_mat_schrumpfh_vk")]
        [Precision(12, 5)]
        public decimal? NVerpMatSchrumpfhVk { get; set; }
        [Column("n_verp_mat_schrumpfh_verschhnitt")]
        [Precision(7, 3)]
        public decimal? NVerpMatSchrumpfhVerschhnitt { get; set; }
        [Column("n_verp_mat_trockenbeutel_ek")]
        [Precision(12, 5)]
        public decimal? NVerpMatTrockenbeutelEk { get; set; }
        [Column("n_verp_mat_trockenbeutel_vk")]
        [Precision(12, 5)]
        public decimal? NVerpMatTrockenbeutelVk { get; set; }
        [Column("n_verp_pers_std_pro_afl_m2")]
        [Precision(7, 3)]
        public decimal? NVerpPersStdProAflM2 { get; set; }
        [Column("n_verp_pers_std_ek_kosten")]
        [Precision(7, 3)]
        public decimal? NVerpPersStdEkKosten { get; set; }
        [Column("n_verp_pers_std_vk_kosten")]
        [Precision(7, 3)]
        public decimal? NVerpPersStdVkKosten { get; set; }
        [Column("n_verp_pers_std_fahrzeit")]
        [Precision(5, 2)]
        public decimal? NVerpPersStdFahrzeit { get; set; }
        [Column("n_verp_user_id_created")]
        public int? NVerpUserIdCreated { get; set; }
        [Column("d_verp_created", TypeName = "datetime")]
        public DateTime? DVerpCreated { get; set; }
        [Column("n_verp_user_id_updated")]
        public int? NVerpUserIdUpdated { get; set; }
        [Column("d_verp_updated", TypeName = "datetime")]
        public DateTime? DVerpUpdated { get; set; }
    }
}