// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Templates von Sonderzeichen die zu einem Verpackungstypen oder ggf. Kunden konfiguriert werden könne.
    /// </summary>
    [Table("t_sonderzeichen")]
    public partial class TSonderzeichen
    {
        [Key]
        [Column("c_name")]
        [StringLength(50)]
        public string CName { get; set; }
        [Key]
        [Column("n_verptyp")]
        public int NVerptyp { get; set; }
        [Key]
        [Column("n_sonderz_id")]
        public int NSonderzId { get; set; }
        [Column("n_farbe_id")]
        public int? NFarbeId { get; set; }
        [Column("n_standard")]
        public bool? NStandard { get; set; }
    }
}