// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Statische Belastungstypen mit entsprechenden Kennwerten
    /// </summary>
    [Table("t_statik_belastungstyp")]
    [Index("CBez", Name = "IDX_BEZ")]
    public partial class TStatikBelastungstyp
    {
        [Key]
        [Column("n_id")]
        public int NId { get; set; }
        [Column("c_bez")]
        [StringLength(45)]
        public string CBez { get; set; }
        /// <summary>
        /// kat_grp=130
        /// </summary>
        [Column("n_weg_id")]
        public int NWegId { get; set; }
        /// <summary>
        /// Teilsicherheitsbeiwert Gamma F
        /// </summary>
        [Column("n_gamma_f")]
        [Precision(10, 3)]
        public decimal NGammaF { get; set; }
        /// <summary>
        /// Teilsicherheitsbeiwert Gamma Q
        /// </summary>
        [Column("n_gamma_q")]
        [Precision(10, 3)]
        public decimal NGammaQ { get; set; }
        /// <summary>
        /// Teilsicherheitsbeiwert Gamma M
        /// </summary>
        [Column("n_gamma_m")]
        [Precision(10, 3)]
        public decimal NGammaM { get; set; }
        /// <summary>
        /// Querdruckbeiwert bei Schwellendruck für Nadelholz
        /// </summary>
        [Column("n_schwellendruck_k_90")]
        [Precision(10, 3)]
        public decimal NSchwellendruckK90 { get; set; }
        /// <summary>
        /// Querdruckbeiwert bei Auflagendruck für Nadelholz
        /// </summary>
        [Column("n_auflagedruck_k_90")]
        [Precision(10, 3)]
        public decimal NAuflagedruckK90 { get; set; }
        /// <summary>
        /// Modifikationsbeiwert
        /// </summary>
        [Column("n_k_mod")]
        [Precision(10, 3)]
        public decimal NKMod { get; set; }
    }
}