// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Materiel wie z.B. U-Stahl und die benötigten statischen Werte
    /// </summary>
    [Table("t_statik_material")]
    public partial class TStatikMaterial
    {
        [Key]
        [Column("n_id")]
        public int NId { get; set; }
        [Column("c_bez")]
        [StringLength(45)]
        public string CBez { get; set; }
        /// <summary>
        /// Biegung nach DIN1052
        /// </summary>
        [Column("n_biegung_din1052")]
        [Precision(10, 2)]
        public decimal NBiegungDin1052 { get; set; }
        /// <summary>
        /// Tabelle 4
        /// </summary>
        [Column("n_biegung_kennwert")]
        [Precision(10, 2)]
        public decimal NBiegungKennwert { get; set; }
        [Column("n_laengsdruck")]
        [Precision(10, 2)]
        public decimal NLaengsdruck { get; set; }
        [Column("n_querdruck")]
        [Precision(10, 2)]
        public decimal NQuerdruck { get; set; }
        [Column("n_rohdichte")]
        [Precision(10, 2)]
        public decimal NRohdichte { get; set; }
        [Column("d_geloescht", TypeName = "datetime")]
        public DateTime? DGeloescht { get; set; }
        [Column("n_elastizitaetsmodul")]
        [Precision(15, 2)]
        public decimal? NElastizitaetsmodul { get; set; }
        /// <summary>
        /// 1=wood, 2=steel
        /// </summary>
        [Column("n_type_id")]
        public int? NTypeId { get; set; }
        [Column("n_breite")]
        public int? NBreite { get; set; }
        [Column("n_hoehe")]
        public int? NHoehe { get; set; }
        [Column("n_staerke")]
        public int? NStaerke { get; set; }
        [Column("n_iy")]
        public float? NIy { get; set; }
        [Column("n_wy")]
        public float? NWy { get; set; }
        [Column("n_ey")]
        public float? NEy { get; set; }
        [Column("n_gewicht_pro_meter")]
        public float? NGewichtProMeter { get; set; }
        /// <summary>
        /// Flaeche
        /// </summary>
        [Column("n_a")]
        public float? NA { get; set; }
        /// <summary>
        /// 1=T, 2=U
        /// </summary>
        [Column("n_steel_type_id")]
        public int? NSteelTypeId { get; set; }
    }
}