// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Steuerparagraphen die bei der Rechnung ausgewählt werden könnnen
    /// </summary>
    [Table("t_steuerparagraphen")]
    public partial class TSteuerparagraphen
    {
        [Key]
        [Column("n_id")]
        public int NId { get; set; }
        [Required]
        [Column("c_text")]
        [StringLength(45)]
        public string CText { get; set; }
        /// <summary>
        /// 0=Nicht gesetzt sonst, wird bei Auswahl in der Rechnung das Gegenkonto gesetzt
        /// </summary>
        [Column("n_gegenkonto")]
        public int NGegenkonto { get; set; }
    }
}