// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Erfassten Stützflächen einer Verpackung zu statischen Berechnung. Alte statische Berechnung.
    /// </summary>
    [Table("t_stuetzflaechen")]
    public partial class TStuetzflaechen
    {
        [Key]
        [Column("st_verp_id")]
        public int StVerpId { get; set; }
        [Key]
        [Column("st_verp_typ")]
        public int StVerpTyp { get; set; }
        [Key]
        [Column("st_id")]
        public int StId { get; set; }
        [Column("st_xpos")]
        public int? StXpos { get; set; }
        [Column("st_ypos")]
        public int? StYpos { get; set; }
        [Column("st_laenge")]
        public int? StLaenge { get; set; }
        [Column("st_breite")]
        public int? StBreite { get; set; }
        [Column("st_hoehe")]
        public int? StHoehe { get; set; }
        [Column("st_schwer_x")]
        public int? StSchwerX { get; set; }
        [Column("st_schwer_y")]
        public int? StSchwerY { get; set; }
        [Column("st_schwer_z")]
        public int? StSchwerZ { get; set; }
        [Column("st_caption")]
        [StringLength(45)]
        public string StCaption { get; set; }
        [Column("st_belastung")]
        public int? StBelastung { get; set; }
        [Column("st_form")]
        public int? StForm { get; set; }
        [Column("st_bez")]
        [StringLength(25)]
        public string StBez { get; set; }
    }
}