// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Text-Template für die Bemerkungen der Verpackung
    /// </summary>
    [Table("t_text_template")]
    public partial class TTextTemplate
    {
        /// <summary>
        /// 1=Kopf, 2=Seite, 3=Deckel, 5=Boden, 6=Kantholzlage, 7=Bodenlage, 8=Zwischenlage, 9=Decklage
        /// </summary>
        [Key]
        [Column("n_typ_id")]
        public int NTypId { get; set; }
        [Key]
        [Column("n_id")]
        public int NId { get; set; }
        [Column("m_text", TypeName = "mediumtext")]
        public string MText { get; set; }
    }
}