// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// App schreibt Packstuecke mit neuem Lagerort
    /// </summary>
    [Table("t_umlagerung_packstueck_app_interface")]
    [Index("CPackstueckId", Name = "IDX_PACKSTUECK_ID")]
    [Index("CProcessId", Name = "IDX_PROCESS_ID")]
    public partial class TUmlagerungPackstueckAppInterface
    {
        [Key]
        [Column("n_id")]
        public long NId { get; set; }
        [Column("c_process_id")]
        [StringLength(45)]
        public string CProcessId { get; set; }
        [Column("c_packstueck_id")]
        [StringLength(45)]
        public string CPackstueckId { get; set; }
        /// <summary>
        /// t_lager.n_id
        /// </summary>
        [Column("n_lager_id")]
        public int NLagerId { get; set; }
        /// <summary>
        /// t_wareneingangpackstueck.n_id
        /// </summary>
        [Column("n_lagerort_id")]
        public int NLagerortId { get; set; }
        [Column("n_einlagerung_id")]
        public long? NEinlagerungId { get; set; }
    }
}