// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Abteilung wo sich der Benutzer von Cratemaker Worker zuletzt eingeloogt war
    /// </summary>
    [Table("t_user_properties")]
    public partial class TUserProperty
    {
        [Key]
        [Column("n_firma_id")]
        public int NFirmaId { get; set; }
        [Key]
        [Column("n_user_id")]
        public int NUserId { get; set; }
        [Column("n_last_login_dept_id")]
        public int? NLastLoginDeptId { get; set; }
    }
}