// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Benutzerdefinierte Farben um ini der Auftrgasverwaltung den Status farblich darzustellen
    /// </summary>
    [Table("t_user_grid_color")]
    public partial class TUserGridColor
    {
        [Key]
        [Column("c_type")]
        [StringLength(15)]
        public string CType { get; set; }
        [Key]
        [Column("n_user_id")]
        public int NUserId { get; set; }
        [Key]
        [Column("n_id")]
        [StringLength(10)]
        public string NId { get; set; }
        [Column("n_color")]
        public int? NColor { get; set; }
        [Column("c_description")]
        [StringLength(35)]
        public string CDescription { get; set; }
    }
}