// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Speichert die Rollen eines Benutzers.
    /// </summary>
    [Table("t_user_account_roles")]
    public partial class TUserAccountRole
    {
        [Key]
        [Column("n_user_id")]
        public int NUserId { get; set; }
        [Key]
        [Column("n_role_id")]
        public int NRoleId { get; set; }
    }
}