// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// VCI Produkte des Herstellers
    /// </summary>
    [Table("t_vci_produkt")]
    [Index("NHerstellerId", Name = "IDX_HERSTELLER_ID")]
    public partial class TVciProdukt
    {
        [Key]
        [Column("n_id")]
        public int NId { get; set; }
        [Column("n_hersteller_id")]
        public int NHerstellerId { get; set; }
        [Column("c_name")]
        [StringLength(45)]
        public string CName { get; set; }
    }
}