// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Losteilsystem - Zuteilung der Losteile zu den Wareneingangspackstücken
    /// </summary>
    [Table("t_versand_artikel_wareneing")]
    [Index("NAuftragId", "NVersandArtikelId", Name = "IDX_AUFTRAG_ARTIKEL")]
    public partial class TVersandArtikelWareneing
    {
        [Key]
        [Column("n_wareneingang_id")]
        public int NWareneingangId { get; set; }
        [Key]
        [Column("n_id")]
        public int NId { get; set; }
        [Column("n_packstueck_id")]
        public int? NPackstueckId { get; set; }
        [Column("n_kunde_id")]
        public int NKundeId { get; set; }
        [Column("n_auftrag_id")]
        public int NAuftragId { get; set; }
        [Column("n_versand_artikel_id")]
        public int NVersandArtikelId { get; set; }
        [Column("n_anzahl")]
        [Precision(20, 5)]
        public decimal NAnzahl { get; set; }
        [Column("d_created", TypeName = "datetime")]
        public DateTime DCreated { get; set; }
        [Column("n_abweichung")]
        public bool? NAbweichung { get; set; }
        [Column("c_gemeldet_an")]
        [StringLength(100)]
        public string CGemeldetAn { get; set; }
        [Column("c_gemeldet_durch")]
        [StringLength(100)]
        public string CGemeldetDurch { get; set; }
        [Column("d_gemeldet_am")]
        public DateOnly? DGemeldetAm { get; set; }
        [Column("n_abweich_grund")]
        public int? NAbweichGrund { get; set; }
        [Column("m_bem_abweichung", TypeName = "mediumtext")]
        public string MBemAbweichung { get; set; }
    }
}