// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Auswahl der Sonderzeichen für ein Beiblatt einer Verpackung
    /// </summary>
    [Table("t_verpackung_beiblatt_sonderz")]
    public partial class TVerpackungBeiblattSonderz
    {
        [Key]
        [Column("n_verp_beiblatt_id")]
        public int NVerpBeiblattId { get; set; }
        [Key]
        [Column("n_pos")]
        public int NPos { get; set; }
        [Column("n_sonderzeichen_id")]
        public int NSonderzeichenId { get; set; }
        [Column("n_farbe_id")]
        public int NFarbeId { get; set; }
    }
}