// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Staffelpreise in Abhängigkeit der Anzahl und Kunden
    /// </summary>
    [Table("t_verpackung_staffelpreis")]
    [Index("NKundeId", Name = "IDX_KUNDE_ID")]
    public partial class TVerpackungStaffelprei
    {
        [Key]
        [Column("c_id")]
        [StringLength(45)]
        public string CId { get; set; }
        [Key]
        [Column("n_kunde_id")]
        public int NKundeId { get; set; }
        /// <summary>
        /// Preis gilt ab dieser Anzahl
        /// </summary>
        [Key]
        [Column("n_ab_anzahl")]
        public int NAbAnzahl { get; set; }
        [Column("n_preis")]
        [Precision(19, 4)]
        public decimal NPreis { get; set; }
    }
}