// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Losteilsystem - Aktuell deaktiviert
    /// </summary>
    [Table("t_versand_container")]
    public partial class TVersandContainer
    {
        [Key]
        [Column("n_id")]
        public int NId { get; set; }
        [Column("n_kunde_id")]
        public int NKundeId { get; set; }
        [Column("c_nr")]
        [StringLength(45)]
        public string CNr { get; set; }
        [Column("n_typ_id")]
        public int NTypId { get; set; }
        [Column("d_created", TypeName = "datetime")]
        public DateTime DCreated { get; set; }
        [Column("c_nr_kunde")]
        [StringLength(45)]
        public string CNrKunde { get; set; }
        [Column("n_auftrag_id")]
        public int NAuftragId { get; set; }
        [Column("c_tuersiegel")]
        [StringLength(25)]
        public string CTuersiegel { get; set; }
        [Column("c_dachsiegel")]
        [StringLength(25)]
        public string CDachsiegel { get; set; }
        [Column("d_geloescht", TypeName = "datetime")]
        public DateTime? DGeloescht { get; set; }
        [Column("n_versand_lkw_id")]
        public int? NVersandLkwId { get; set; }
        [Column("d_ladedatum")]
        public DateOnly? DLadedatum { get; set; }
        [Column("n_tara")]
        public int? NTara { get; set; }
    }
}