// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Kantholzkonstruktion für die Einpauten der Verpackung
    /// </summary>
    [Table("t_verp_konstruktion")]
    public partial class TVerpKonstruktion
    {
        [Key]
        [Column("n_verp_id")]
        public int NVerpId { get; set; }
        [Key]
        [Column("n_verp_typ_id")]
        public int NVerpTypId { get; set; }
        [Key]
        [Column("n_verp_sub_id")]
        public int NVerpSubId { get; set; }
        [Key]
        [Column("n_id")]
        public int NId { get; set; }
        [Column("n_lage")]
        public int NLage { get; set; }
        [Column("n_anzahl")]
        public int NAnzahl { get; set; }
        [Column("n_laenge")]
        public int NLaenge { get; set; }
        [Column("n_breite")]
        public int NBreite { get; set; }
        [Column("n_hoehe")]
        public int NHoehe { get; set; }
        [Column("n_material_id")]
        public int NMaterialId { get; set; }
        [Column("c_bezeichnung")]
        [StringLength(20)]
        public string CBezeichnung { get; set; }
    }
}