// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Wird für die Generierung der Verpackungs-Nr. innerhalb eines Auftrags benötigt.
    /// </summary>
    [Table("t_verpackungs_nr")]
    [Index("NAuftragId", "NKundeId", Name = "IDX_AUFTRAG_KUNDE")]
    public partial class TVerpackungsNr
    {
        [Key]
        [Column("n_id")]
        public int NId { get; set; }
        [Column("c_nr")]
        [StringLength(50)]
        public string CNr { get; set; }
        [Column("n_year_nr")]
        public int NYearNr { get; set; }
        [Column("n_year")]
        public int NYear { get; set; }
        [Column("c_modus")]
        [StringLength(15)]
        public string CModus { get; set; }
        [Column("n_kunde_id")]
        public int? NKundeId { get; set; }
        [Column("n_prj_id")]
        public int? NPrjId { get; set; }
        [Column("n_auftrag_id")]
        public int? NAuftragId { get; set; }
        [Column("d_created", TypeName = "datetime")]
        public DateTime DCreated { get; set; }
    }
}