// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Leiharbeiterfirmen die Verpackungen zugeordnet werden. Dient der Rechnungsstellung welche Firma / MA wieviel verpackt hat.
    /// </summary>
    [Table("t_verpackung_fremd_main")]
    public partial class TVerpackungFremdMain
    {
        [Key]
        [Column("n_id")]
        public int NId { get; set; }
        [Column("n_user_id")]
        public int? NUserId { get; set; }
        [Column("d_created", TypeName = "datetime")]
        public DateTime? DCreated { get; set; }
    }
}