// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Verpackungsassistens der in Abhängigkeit des Nettogewichts bestimmte Werte vorbesetzt
    /// </summary>
    [Table("t_verp_assistent")]
    public partial class TVerpAssistent
    {
        [Key]
        [Column("n_typ_id")]
        public int NTypId { get; set; }
        [Key]
        [Column("n_netto_gewicht")]
        public int NNettoGewicht { get; set; }
        [Column("n_lk_abstand")]
        public int NLkAbstand { get; set; }
        [Column("c_lk")]
        [StringLength(10)]
        public string CLk { get; set; }
        [Column("n_lk_hochkant")]
        public bool? NLkHochkant { get; set; }
        [Column("n_boden_staerke")]
        public int NBodenStaerke { get; set; }
        [Column("n_dh_nutzen_ab")]
        public int NDhNutzenAb { get; set; }
        [Column("n_akylux")]
        public bool? NAkylux { get; set; }
        [Column("n_zn")]
        public bool? NZn { get; set; }
        [Column("n_kstr_bbretter_unter_k")]
        public bool? NKstrBbretterUnterK { get; set; }
        /// <summary>
        /// Bodenbretter bis unter KL
        /// </summary>
        [Column("n_kstr_bbretter_unter_kl")]
        public bool? NKstrBbretterUnterKl { get; set; }
        /// <summary>
        /// Bodenbretter bis unter Bh
        /// </summary>
        [Column("n_kstr_bbretter_unter_bh")]
        public bool? NKstrBbretterUnterBh { get; set; }
        [Column("n_kstr_qklaenge_aussenbreite")]
        public bool? NKstrQklaengeAussenbreite { get; set; }
        [Column("n_kstr_k_s_zfuge")]
        public bool? NKstrKSZfuge { get; set; }
        [Column("c_kopf_bem")]
        [StringLength(100)]
        public string CKopfBem { get; set; }
        [Column("c_seite_bem")]
        [StringLength(100)]
        public string CSeiteBem { get; set; }
        [Column("c_deckel_bem")]
        [StringLength(100)]
        public string CDeckelBem { get; set; }
        [Column("c_boden_bem")]
        [StringLength(100)]
        public string CBodenBem { get; set; }
        /// <summary>
        /// Innenbreite zwischen Wand zu Wand
        /// </summary>
        [Column("n_kstr_ibreite_wand_zu_wand")]
        public bool? NKstrIbreiteWandZuWand { get; set; }
    }
}