// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Haupdatensatz der Verpackungen Kiste, Palette und Verschlag mit Eigenschaften.
    /// </summary>
    [Table("t_verpackung_main")]
    [Index("NAuftragId", "NAktiv", "NGedruckt", "DDeleted", Name = "IDX_AUFTRAG_EXT")]
    [Index("CId", Name = "IDX_CID")]
    [Index("NId", "NTypId", "NKundeId", Name = "IDX_ID_KUNDE")]
    [Index("NKundeId", "NAktiv", "DDeleted", "NAuftragId", Name = "IDX_OHNE_GEDRCUKT")]
    [Index("NParentVerpId", "NParentVerpTypId", "NAuftragId", "DDeleted", Name = "IDX_PARENT")]
    [Index("NKundeId", Name = "IDX_VERP_KUNDE")]
    public partial class TVerpackungMain
    {
        [Key]
        [Column("n_id")]
        public int NId { get; set; }
        [Key]
        [Column("n_typ_id")]
        public int NTypId { get; set; }
        [Column("n_parent_auftrag_id")]
        public int? NParentAuftragId { get; set; }
        [Column("n_parent_verp_typ_id")]
        public int? NParentVerpTypId { get; set; }
        [Column("n_parent_verp_id")]
        public int? NParentVerpId { get; set; }
        /// <summary>
        /// eingegeben laenge
        /// </summary>
        [Column("n_laenge")]
        public int? NLaenge { get; set; }
        [Column("n_laenge_bausatz")]
        public ushort? NLaengeBausatz { get; set; }
        /// <summary>
        /// eingegeben breite
        /// </summary>
        [Column("n_breite")]
        public int? NBreite { get; set; }
        [Column("n_breite_bausatz")]
        public ushort? NBreiteBausatz { get; set; }
        /// <summary>
        /// eingegeben hoehe
        /// </summary>
        [Column("n_hoehe")]
        public int? NHoehe { get; set; }
        [Column("n_hoehe_bausatz")]
        public ushort? NHoeheBausatz { get; set; }
        [Column("n_collo_laenge")]
        public int? NColloLaenge { get; set; }
        [Column("n_collo_breite")]
        public int? NColloBreite { get; set; }
        [Column("n_collo_hoehe")]
        public int? NColloHoehe { get; set; }
        [Column("n_collo_tara")]
        public int? NColloTara { get; set; }
        [Column("n_auftrag_id")]
        public int? NAuftragId { get; set; }
        [Column("n_kunde_id")]
        public int NKundeId { get; set; }
        [Column("n_aktiv")]
        public bool NAktiv { get; set; }
        [Column("n_anzahl")]
        public int? NAnzahl { get; set; }
        [Column("n_gedruckt")]
        public bool NGedruckt { get; set; }
        [Column("n_land_id")]
        public int? NLandId { get; set; }
        [Column("n_mattyp_id")]
        public int? NMattypId { get; set; }
        [Column("n_seem")]
        public bool? NSeem { get; set; }
        [Column("n_vp")]
        public bool? NVp { get; set; }
        [Column("n_zn")]
        public bool? NZn { get; set; }
        /// <summary>
        /// Kistentyp-Steckkiste für VTT Verbinder
        /// </summary>
        [Column("n_kstr_is_steckkiste")]
        public bool? NKstrIsSteckkiste { get; set; }
        [Column("n_holzbehandlung_id")]
        public int? NHolzbehandlungId { get; set; }
        [Column("d_deleted", TypeName = "datetime")]
        public DateTime? DDeleted { get; set; }
        [Column("n_anfrage_preis")]
        [Precision(19, 4)]
        public decimal? NAnfragePreis { get; set; }
        [Column("n_rabatt")]
        public float? NRabatt { get; set; }
        [Column("c_nr")]
        [StringLength(50)]
        [MySqlCharSet("utf8mb3")]
        [MySqlCollation("utf8_general_ci")]
        public string CNr { get; set; }
        [Column("m_info", TypeName = "mediumtext")]
        [MySqlCharSet("utf8mb3")]
        [MySqlCollation("utf8_general_ci")]
        public string MInfo { get; set; }
        [Column("n_baufeld_id")]
        public int? NBaufeldId { get; set; }
        [Column("n_baufeld_fert_id")]
        public int? NBaufeldFertId { get; set; }
        [Column("c_position")]
        [StringLength(60)]
        [MySqlCharSet("utf8mb3")]
        [MySqlCollation("utf8_general_ci")]
        public string CPosition { get; set; }
        [Column("n_ohne_boden_fertigen")]
        public bool? NOhneBodenFertigen { get; set; }
        [Column("n_ohne_koepfe_fertigen")]
        public bool? NOhneKoepfeFertigen { get; set; }
        [Column("n_ohne_seiten_fertigen")]
        public bool? NOhneSeitenFertigen { get; set; }
        [Column("n_ohne_deckel_fertigen")]
        public bool? NOhneDeckelFertigen { get; set; }
        [Column("c_kunden_artikel_nr")]
        [StringLength(30)]
        [MySqlCharSet("utf8mb3")]
        [MySqlCollation("utf8_general_ci")]
        public string CKundenArtikelNr { get; set; }
        [Column("n_lieferant_id")]
        public int? NLieferantId { get; set; }
        /// <summary>
        /// Preiskategorie über die, die Fremdfirmen berechnet werden
        /// </summary>
        [Column("n_verp_preiskat_id")]
        public int? NVerpPreiskatId { get; set; }
        /// <summary>
        /// t_verpackung_fremd_main.n_id
        /// </summary>
        [Column("n_fremd_verpfirma_id")]
        public int? NFremdVerpfirmaId { get; set; }
        [Column("d_erstellt", TypeName = "datetime")]
        public DateTime? DErstellt { get; set; }
        [Column("n_quadratmeter")]
        [Precision(13, 4)]
        public decimal? NQuadratmeter { get; set; }
        /// <summary>
        /// Taragewicht Einbauten
        /// </summary>
        [Column("n_tara_einbauten")]
        public int? NTaraEinbauten { get; set; }
        /// <summary>
        /// Eindeutige ID der Verpackung
        /// </summary>
        [Column("c_id")]
        [StringLength(45)]
        [MySqlCharSet("utf8mb3")]
        [MySqlCollation("utf8_general_ci")]
        public string CId { get; set; }
        [Column("c_rahmen_id")]
        [StringLength(45)]
        [MySqlCharSet("utf8mb3")]
        [MySqlCollation("utf8_general_ci")]
        public string CRahmenId { get; set; }
        [Column("n_waehrung_id")]
        public int? NWaehrungId { get; set; }
        [Column("c_artikel_nr")]
        [StringLength(25)]
        [MySqlCharSet("utf8mb3")]
        [MySqlCollation("utf8_general_ci")]
        public string CArtikelNr { get; set; }
        [Column("c_artikel_name")]
        [StringLength(25)]
        [MySqlCharSet("utf8mb3")]
        [MySqlCollation("utf8_general_ci")]
        public string CArtikelName { get; set; }
        [Column("d_ausgelagert")]
        public DateOnly? DAusgelagert { get; set; }
        /// <summary>
        /// kat_grp=150
        /// </summary>
        [Column("n_kuerzel_id")]
        public int? NKuerzelId { get; set; }
        [Column("n_user_id_created")]
        public int? NUserIdCreated { get; set; }
        [Column("n_user_id_updated")]
        public int? NUserIdUpdated { get; set; }
        [Column("n_user_id_printed")]
        public int? NUserIdPrinted { get; set; }
        [Column("c_info_short_1")]
        [StringLength(15)]
        public string CInfoShort1 { get; set; }
        [Column("c_info_short_2")]
        [StringLength(15)]
        public string CInfoShort2 { get; set; }
        /// <summary>
        /// t_kostenstelle
        /// </summary>
        [Column("n_kostenstelle_id")]
        public int? NKostenstelleId { get; set; }
    }
}