// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Zuordnung der Losteile zu den Verpackungen
    /// </summary>
    [Table("t_versand_artikel_verpackung")]
    [Index("NVersandArtikelId", "NAuftragId", "NAnzahl", Name = "IDX_AUFTRAG_ARTIKEL")]
    [Index("NKundeId", Name = "IDX_KUNDE_ID")]
    public partial class TVersandArtikelVerpackung
    {
        [Key]
        [Column("n_kunde_id")]
        public int NKundeId { get; set; }
        [Key]
        [Column("n_auftrag_id")]
        public int NAuftragId { get; set; }
        /// <summary>
        /// FK t_versand_artikel.n_id
        /// </summary>
        [Key]
        [Column("n_versand_artikel_id")]
        public int NVersandArtikelId { get; set; }
        [Key]
        [Column("n_versand_artikel_auftrag_id")]
        public int NVersandArtikelAuftragId { get; set; }
        [Key]
        [Column("n_id")]
        public int NId { get; set; }
        [Column("n_anzahl")]
        [Precision(20, 5)]
        public decimal NAnzahl { get; set; }
        [Column("d_created", TypeName = "datetime")]
        public DateTime DCreated { get; set; }
        [Column("c_packstueck_nr")]
        [StringLength(25)]
        public string CPackstueckNr { get; set; }
    }
}