// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Eine Einzelauflistung der Verpnummern 1+3 -&gt; 3 Datensaetze
    /// </summary>
    [Table("t_verpackung_nr_list_small")]
    [Index("NVerptypId", "NVerpId", Name = "IDX_BEWERTUNG")]
    [Index("NVerpId", "NVerptypId", "NVerpSubId", Name = "IDX_GELIEFERT")]
    [Index("NVerpSubId", Name = "IDX_SUB_ID")]
    [Index("NVerpId", "NVerptypId", "NVerpSubId", "CNr", Name = "IDX_VERRECHNET")]
    [Index("NStatus", Name = "IDX_VERRECHNET_STATUS")]
    [Index("NStatus", "DFertig", Name = "fertig")]
    [MySqlCharSet("utf8mb3")]
    [MySqlCollation("utf8_general_ci")]
    public partial class TVerpackungNrListSmall
    {
        [Key]
        [Column("n_verptyp_id")]
        public int NVerptypId { get; set; }
        [Key]
        [Column("n_verp_id")]
        public int NVerpId { get; set; }
        /// <summary>
        /// wird fuer Holzprodukte genutzt
        /// </summary>
        [Key]
        [Column("n_verp_sub_id")]
        public int NVerpSubId { get; set; }
        [Key]
        [Column("c_nr")]
        [StringLength(15)]
        public string CNr { get; set; }
        [Column("n_wir_liefern")]
        public bool NWirLiefern { get; set; }
        /// <summary>
        /// kat_grp=81
        /// </summary>
        [Column("n_status")]
        public int NStatus { get; set; }
        [Column("d_fertig", TypeName = "datetime")]
        public DateTime? DFertig { get; set; }
    }
}