// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Alle Werte einer Verpackung die errechnet wurden
    /// </summary>
    [Table("t_verpackung_berech")]
    public partial class TVerpackungBerech
    {
        [Key]
        [Column("n_verp_id")]
        public int NVerpId { get; set; }
        [Key]
        [Column("n_verp_typ_id")]
        public int NVerpTypId { get; set; }
        [Column("n_laenge_i")]
        public int NLaengeI { get; set; }
        [Column("n_breite_i")]
        public int NBreiteI { get; set; }
        [Column("n_hoehe_i")]
        public int NHoeheI { get; set; }
        [Column("n_laenge_a")]
        public int NLaengeA { get; set; }
        [Column("n_breite_a")]
        public int NBreiteA { get; set; }
        [Column("n_hoehe_a")]
        public int NHoeheA { get; set; }
        /// <summary>
        /// Eigengewicht der Verpackung
        /// </summary>
        [Column("n_eigengewicht")]
        public int NEigengewicht { get; set; }
        /// <summary>
        /// Gesamtgewicht der VErpackung mit Stuetzflaechen
        /// </summary>
        [Column("n_gesamtgewicht")]
        public int NGesamtgewicht { get; set; }
        [Column("n_k_breite")]
        public int? NKBreite { get; set; }
        /// <summary>
        /// Kopfbrettlaenge
        /// </summary>
        [Column("n_k_brett_laenge")]
        public int? NKBrettLaenge { get; set; }
        /// <summary>
        /// Kopfbrettbreite
        /// </summary>
        [Column("n_k_brett_breite")]
        public int? NKBrettBreite { get; set; }
        /// <summary>
        /// Aufgelegtmass fuer Kopf
        /// </summary>
        [Column("n_k_brett_aufgelegt")]
        public int? NKBrettAufgelegt { get; set; }
        /// <summary>
        /// Kopfbrettanzahl
        /// </summary>
        [Column("n_k_brett_anzahl")]
        public int? NKBrettAnzahl { get; set; }
        [Column("n_k_hoehe")]
        public int? NKHoehe { get; set; }
        [Column("n_k_anzahl")]
        public int? NKAnzahl { get; set; }
        [Column("n_kl_laenge")]
        public int? NKlLaenge { get; set; }
        [Column("n_kl_anzahl")]
        public int? NKlAnzahl { get; set; }
        [Column("n_kl_material_id")]
        public int? NKlMaterialId { get; set; }
        [Column("n_zl_laenge")]
        public int? NZlLaenge { get; set; }
        [Column("n_zl_breite")]
        public int? NZlBreite { get; set; }
        [Column("n_zl_hoehe")]
        public int? NZlHoehe { get; set; }
        [Column("n_zl_anzahl")]
        public int? NZlAnzahl { get; set; }
        [Column("n_s_breite")]
        public int? NSBreite { get; set; }
        /// <summary>
        /// Seitenbrettlaenge
        /// </summary>
        [Column("n_s_brett_laenge")]
        public int? NSBrettLaenge { get; set; }
        /// <summary>
        /// Seitenbrettbreite
        /// </summary>
        [Column("n_s_brett_breite")]
        public int? NSBrettBreite { get; set; }
        /// <summary>
        /// Aufgelegtmass fuer Seite
        /// </summary>
        [Column("n_s_brett_aufgelegt")]
        public int? NSBrettAufgelegt { get; set; }
        /// <summary>
        /// Seitenbrettanzahl
        /// </summary>
        [Column("n_s_brett_anzahl")]
        public int? NSBrettAnzahl { get; set; }
        [Column("n_s_hoehe")]
        public int? NSHoehe { get; set; }
        [Column("n_s_anzahl")]
        public int? NSAnzahl { get; set; }
        [Column("n_sl_laenge")]
        public int? NSlLaenge { get; set; }
        [Column("n_sl_anzahl")]
        public int? NSlAnzahl { get; set; }
        [Column("n_sl_material_id")]
        public int? NSlMaterialId { get; set; }
        /// <summary>
        /// seitl. Distanzbretter
        /// </summary>
        [Column("n_sdistanz_laenge")]
        public int? NSdistanzLaenge { get; set; }
        [Column("n_fl_laenge")]
        public int? NFlLaenge { get; set; }
        [Column("n_fl_breite")]
        public int? NFlBreite { get; set; }
        [Column("n_fl_hoehe")]
        public int? NFlHoehe { get; set; }
        [Column("n_fl_anzahl")]
        public int? NFlAnzahl { get; set; }
        [Column("n_s_kpl_laenge")]
        public int? NSKplLaenge { get; set; }
        /// <summary>
        /// Kupplungsbreite der Seite (aufegelegt Mass)
        /// </summary>
        [Column("n_s_kpl_breite")]
        public int? NSKplBreite { get; set; }
        /// <summary>
        /// Kupplungsstaerke der Seite
        /// </summary>
        [Column("n_s_kpl_hoehe")]
        public int? NSKplHoehe { get; set; }
        /// <summary>
        /// Kupplungsanzahl der Seite
        /// </summary>
        [Column("n_s_kpl_anzahl")]
        public int? NSKplAnzahl { get; set; }
        /// <summary>
        /// Kupplungsbrett Laenge der Seite
        /// </summary>
        [Column("n_s_kb_laenge")]
        public int? NSKbLaenge { get; set; }
        /// <summary>
        /// Kupplungsbrett Breite der Seite
        /// </summary>
        [Column("n_s_kb_breite")]
        public int? NSKbBreite { get; set; }
        /// <summary>
        /// Kupplungsbrett Hoehe der Seite
        /// </summary>
        [Column("n_s_kb_hoehe")]
        public int? NSKbHoehe { get; set; }
        /// <summary>
        /// Kupplungsanzahl der Seite
        /// </summary>
        [Column("n_s_kb_anzahl")]
        public int? NSKbAnzahl { get; set; }
        [Column("n_d_laenge")]
        public int? NDLaenge { get; set; }
        [Column("n_d_breite")]
        public int? NDBreite { get; set; }
        /// <summary>
        /// Kopfbrettlaenge
        /// </summary>
        [Column("n_d_brett_laenge")]
        public int? NDBrettLaenge { get; set; }
        /// <summary>
        /// Kopfbrettbreite
        /// </summary>
        [Column("n_d_brett_breite")]
        public int? NDBrettBreite { get; set; }
        /// <summary>
        /// Aufgelegtmass fuer Deckel
        /// </summary>
        [Column("n_d_brett_aufgelegt")]
        public int? NDBrettAufgelegt { get; set; }
        /// <summary>
        /// Bodenbrettanzahl
        /// </summary>
        [Column("n_d_brett_anzahl")]
        public int? NDBrettAnzahl { get; set; }
        [Column("n_d_anzahl")]
        public int? NDAnzahl { get; set; }
        [Column("n_dls_laenge")]
        public int? NDlsLaenge { get; set; }
        [Column("n_dls_anzahl")]
        public int? NDlsAnzahl { get; set; }
        [Column("n_dlk_laenge")]
        public int? NDlkLaenge { get; set; }
        [Column("n_dlk_anzahl")]
        public int? NDlkAnzahl { get; set; }
        /// <summary>
        /// Kupplungslaenge des Deckels
        /// </summary>
        [Column("n_d_kpl_laenge")]
        public int? NDKplLaenge { get; set; }
        /// <summary>
        /// Kupplungsbreite des Deckels (aufegelegt Mass)
        /// </summary>
        [Column("n_d_kpl_breite")]
        public int? NDKplBreite { get; set; }
        /// <summary>
        /// Kupplungsstaerke des Deckels
        /// </summary>
        [Column("n_d_kpl_hoehe")]
        public int? NDKplHoehe { get; set; }
        /// <summary>
        /// Kupplungsanzahl des Deckels
        /// </summary>
        [Column("n_d_kpl_anzahl")]
        public int? NDKplAnzahl { get; set; }
        /// <summary>
        /// Kupplungsbrett Laenge des Deckels
        /// </summary>
        [Column("n_d_kb_laenge")]
        public int? NDKbLaenge { get; set; }
        /// <summary>
        /// Kupplungsbrett Breite des Deckels
        /// </summary>
        [Column("n_d_kb_breite")]
        public int? NDKbBreite { get; set; }
        /// <summary>
        /// Kupplungsbrett Hoehe des Deckels
        /// </summary>
        [Column("n_d_kb_hoehe")]
        public int? NDKbHoehe { get; set; }
        /// <summary>
        /// Kupplungsanzahl des Deckels
        /// </summary>
        [Column("n_d_kb_anzahl")]
        public int? NDKbAnzahl { get; set; }
        /// <summary>
        /// Kupplungslaenge des Deckels (Sperrholz)
        /// </summary>
        [Column("n_d_dichtkpl1_laenge")]
        public int? NDDichtkpl1Laenge { get; set; }
        /// <summary>
        /// Kupplungsbreite des Deckels (Sperrholz)
        /// </summary>
        [Column("n_d_dichtkpl1_breite")]
        public int? NDDichtkpl1Breite { get; set; }
        /// <summary>
        /// Kupplungshoehe des Deckels (Sperrholz)
        /// </summary>
        [Column("n_d_dichtkpl1_hoehe")]
        public int? NDDichtkpl1Hoehe { get; set; }
        /// <summary>
        /// Kupplungsanzahl des Deckels (Sperrholz)
        /// </summary>
        [Column("n_d_dichtkpl1_anzahl")]
        public int? NDDichtkpl1Anzahl { get; set; }
        /// <summary>
        /// Kupplungslaenge des Deckels (Sperrholz)
        /// </summary>
        [Column("n_d_dichtkpl2_laenge")]
        public int? NDDichtkpl2Laenge { get; set; }
        /// <summary>
        /// Kupplungsbreite des Deckels (Sperrholz)
        /// </summary>
        [Column("n_d_dichtkpl2_breite")]
        public int? NDDichtkpl2Breite { get; set; }
        /// <summary>
        /// Kupplungshoehe des Deckels (Sperrholz)
        /// </summary>
        [Column("n_d_dichtkpl2_hoehe")]
        public int? NDDichtkpl2Hoehe { get; set; }
        /// <summary>
        /// Kupplungsanzahl des Deckels (Sperrholz)
        /// </summary>
        [Column("n_d_dichtkpl2_anzahl")]
        public int? NDDichtkpl2Anzahl { get; set; }
        [Column("n_dh_laenge")]
        public int? NDhLaenge { get; set; }
        [Column("n_st_laenge")]
        public int? NStLaenge { get; set; }
        [Column("n_str_laenge")]
        public int? NStrLaenge { get; set; }
        [Column("n_str_anzahl")]
        public int? NStrAnzahl { get; set; }
        /// <summary>
        /// Boden Laenge
        /// </summary>
        [Column("n_b_laenge")]
        public int NBLaenge { get; set; }
        /// <summary>
        /// Boden Breite
        /// </summary>
        [Column("n_b_breite")]
        public int NBBreite { get; set; }
        /// <summary>
        /// Bodenkupplungsanzahl
        /// </summary>
        [Column("n_b_anzahl")]
        public int? NBAnzahl { get; set; }
        /// <summary>
        /// Bodenkupplungsanzahl
        /// </summary>
        [Column("n_b_kpl_anzahl")]
        public int? NBKplAnzahl { get; set; }
        /// <summary>
        /// Bodenkupplungsanzahl
        /// </summary>
        [Column("n_b_kpl_laenge")]
        public int? NBKplLaenge { get; set; }
        /// <summary>
        /// Bodenkupplungsanzahl
        /// </summary>
        [Column("n_b_kpl_breite")]
        public int? NBKplBreite { get; set; }
        /// <summary>
        /// Bodenkupplungsanzahl
        /// </summary>
        [Column("n_b_kpl_hoehe")]
        public int? NBKplHoehe { get; set; }
        /// <summary>
        /// Bodenbrettlaenge
        /// </summary>
        [Column("n_b_brett_laenge")]
        public int? NBBrettLaenge { get; set; }
        /// <summary>
        /// Bodenbrettbreite
        /// </summary>
        [Column("n_b_brett_breite")]
        public int? NBBrettBreite { get; set; }
        /// <summary>
        /// Aufgelegtmass fuer Boden
        /// </summary>
        [Column("n_b_brett_aufgelegt")]
        public int? NBBrettAufgelegt { get; set; }
        /// <summary>
        /// Bodenbrettanzahl
        /// </summary>
        [Column("n_b_brett_anzahl")]
        public int? NBBrettAnzahl { get; set; }
        [Column("n_lk_laenge")]
        public int? NLkLaenge { get; set; }
        [Column("n_sb_laenge")]
        public int? NSbLaenge { get; set; }
        [Column("n_qk_laenge")]
        public int? NQkLaenge { get; set; }
        [Column("n_bh_laenge")]
        public int? NBhLaenge { get; set; }
        [Column("n_mrl_laenge")]
        public int? NMrlLaenge { get; set; }
        [Column("n_mrl_breite")]
        public int? NMrlBreite { get; set; }
        [Column("n_mrl_hoehe")]
        public int? NMrlHoehe { get; set; }
        [Column("n_mrl_anzahl")]
        public int? NMrlAnzahl { get; set; }
        /// <summary>
        /// Minirahmenquerholz Laenge
        /// </summary>
        [Column("n_mrq_laenge")]
        public int? NMrqLaenge { get; set; }
        /// <summary>
        /// Minirahmenquerholz Breite
        /// </summary>
        [Column("n_mrq_breite")]
        public int? NMrqBreite { get; set; }
        /// <summary>
        /// Minirahmenquerholz Hoehe
        /// </summary>
        [Column("n_mrq_hoehe")]
        public int? NMrqHoehe { get; set; }
        /// <summary>
        /// Minirahmenquerholz Anzahl
        /// </summary>
        [Column("n_mrq_anzahl")]
        public int? NMrqAnzahl { get; set; }
        /// <summary>
        /// Rahmenholz Laenge
        /// </summary>
        [Column("n_rh_laenge")]
        public int? NRhLaenge { get; set; }
        /// <summary>
        /// Rahmenholz Anzahl
        /// </summary>
        [Column("n_rh_anzahl")]
        public int? NRhAnzahl { get; set; }
        /// <summary>
        /// Rahmenquerholz Laenge
        /// </summary>
        [Column("n_rq_laenge")]
        public int? NRqLaenge { get; set; }
        /// <summary>
        /// Rahmenquerholz Anzahl
        /// </summary>
        [Column("n_rq_anzahl")]
        public int? NRqAnzahl { get; set; }
        /// <summary>
        /// Aussenquadratmeter
        /// </summary>
        [Column("n_quadratmeter")]
        [Precision(13, 4)]
        public decimal NQuadratmeter { get; set; }
        [Column("n_umstellung_qm")]
        [Precision(13, 4)]
        public decimal? NUmstellungQm { get; set; }
        /// <summary>
        /// Qubikmeter
        /// </summary>
        [Column("n_qubikmeter")]
        [Precision(13, 4)]
        public decimal NQubikmeter { get; set; }
        /// <summary>
        /// Qubikmeter aller Schnitthoelzer
        /// </summary>
        [Column("n_schnittholz_m3")]
        [Precision(13, 4)]
        public decimal NSchnittholzM3 { get; set; }
        /// <summary>
        /// Qubikmeter aller Plattenwerkstoffe
        /// </summary>
        [Column("n_platten_m3")]
        [Precision(13, 4)]
        public decimal NPlattenM3 { get; set; }
        /// <summary>
        /// Quadratmeter aller Plattenwerkstoffe
        /// </summary>
        [Column("n_platten_m2")]
        [Precision(13, 4)]
        public decimal NPlattenM2 { get; set; }
        [Column("n_trockenmittel_einheiten")]
        public int NTrockenmittelEinheiten { get; set; }
        /// <summary>
        /// Effektive Hoehe des Boden bis Bodebelag
        /// </summary>
        [Column("n_boden_hoehe")]
        public int? NBodenHoehe { get; set; }
        /// <summary>
        /// Qubikmeter aller Beipack Schnitthoelzer
        /// </summary>
        [Column("n_schnittholz_beipack_m3")]
        [Precision(19, 4)]
        public decimal NSchnittholzBeipackM3 { get; set; }
        /// <summary>
        /// Qubikmeter aller BeipackKonstruktionshoelzer
        /// </summary>
        [Column("n_schnittholz_beipack_konstr_m3")]
        [Precision(19, 4)]
        public decimal NSchnittholzBeipackKonstrM3 { get; set; }
        /// <summary>
        /// Quadratemeter aller Beipack Sperrholzplatten
        /// </summary>
        [Column("n_sperrholz_beipack_m2")]
        [Precision(19, 4)]
        public decimal NSperrholzBeipackM2 { get; set; }
        /// <summary>
        /// Quadratemeter aller Beipack OSBplatten
        /// </summary>
        [Column("n_osb_beipack_m2")]
        [Precision(19, 4)]
        public decimal NOsbBeipackM2 { get; set; }
        /// <summary>
        /// Quadratemeter aller Beipack Siebdruckplatten
        /// </summary>
        [Column("n_siebdruck_beipack_m2")]
        [Precision(19, 4)]
        public decimal NSiebdruckBeipackM2 { get; set; }
        /// <summary>
        /// KVH was nur in Lk oder QK ist
        /// </summary>
        [Column("n_kvh_m3")]
        [Precision(19, 4)]
        public decimal NKvhM3 { get; set; }
    }
}