// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Beschreibung der Stützflächen die beim Ausdruck des Beiblatts gedruckt wird.
    /// </summary>
    [Table("t_verpackung_beiblatt_stuetz")]
    public partial class TVerpackungBeiblattStuetz
    {
        [Key]
        [Column("n_id")]
        public int NId { get; set; }
        [Column("n_verp_beiblatt_id")]
        public int NVerpBeiblattId { get; set; }
        [Column("n_pos")]
        public int NPos { get; set; }
        [Column("n_x")]
        public int? NX { get; set; }
        [Column("n_y")]
        public int? NY { get; set; }
        [Required]
        [Column("c_nr")]
        [StringLength(10)]
        [MySqlCharSet("utf8mb3")]
        [MySqlCollation("utf8_general_ci")]
        public string CNr { get; set; }
        [Column("c_bezeichnung")]
        [StringLength(50)]
        [MySqlCharSet("utf8mb3")]
        [MySqlCollation("utf8_general_ci")]
        public string CBezeichnung { get; set; }
    }
}