// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Mögliche Checkliste die vor dem Ausdruck geprüft werden
    /// </summary>
    [Table("t_verpackung_kunde_checker_std")]
    public partial class TVerpackungKundeCheckerStd
    {
        [Key]
        [Column("n_kunde_id")]
        public int NKundeId { get; set; }
        /// <summary>
        /// 1=Hinweis wenn keine Markeirung eingtragen wurde beim Drucken
        /// </summary>
        [Column("n_beiblatt_markierung_pruefen")]
        public bool? NBeiblattMarkierungPruefen { get; set; }
    }
}