// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Erfassung von mehreren Verpackungen aus denen die einzelnen Verpckungen t_verpackung und t_palette geneiert werden. Dient zur Massenerfassung bei Angeboten mit sehr vielen Verpackungen.
    /// </summary>
    [Table("t_verpackung_multi")]
    public partial class TVerpackungMulti
    {
        [Key]
        [Column("n_auftrag_id")]
        public int NAuftragId { get; set; }
        [Key]
        [Column("n_id")]
        public int NId { get; set; }
        [Required]
        [Column("c_nr")]
        [StringLength(15)]
        [MySqlCharSet("utf8mb3")]
        [MySqlCollation("utf8_general_ci")]
        public string CNr { get; set; }
        [Column("n_typ_id")]
        public int NTypId { get; set; }
        [Column("n_material_id")]
        public int NMaterialId { get; set; }
        [Column("n_anzahl")]
        public int NAnzahl { get; set; }
        [Column("n_laenge")]
        public int NLaenge { get; set; }
        /// <summary>
        /// Maschinenlaenge
        /// </summary>
        [Column("n_laenge_m")]
        public int? NLaengeM { get; set; }
        [Column("n_breite")]
        public int NBreite { get; set; }
        /// <summary>
        /// Maschinenbreite
        /// </summary>
        [Column("n_breite_m")]
        public int? NBreiteM { get; set; }
        [Column("n_hoehe")]
        public int? NHoehe { get; set; }
        /// <summary>
        /// Maschinenhoehe
        /// </summary>
        [Column("n_hoehe_m")]
        public int? NHoeheM { get; set; }
        /// <summary>
        /// kanhoelzer nach Gewicht berechnen
        /// </summary>
        [Column("n_kh_berechnen")]
        public bool? NKhBerechnen { get; set; }
        /// <summary>
        /// 1=Cratemaker-Typ, 2=Kiste, 3=Palette, 4=Verschlag
        /// </summary>
        [Column("n_verp_gruppen_typ")]
        public int? NVerpGruppenTyp { get; set; }
        /// <summary>
        /// 0=unverpackt, 1=vp, 2=seem
        /// </summary>
        [Column("n_verpacken")]
        public int? NVerpacken { get; set; }
        [Column("n_netto")]
        public int? NNetto { get; set; }
        [Column("c_material")]
        [StringLength(50)]
        [MySqlCharSet("utf8mb3")]
        [MySqlCollation("utf8_general_ci")]
        public string CMaterial { get; set; }
        [Column("c_material_anz")]
        [Precision(19, 3)]
        public decimal? CMaterialAnz { get; set; }
        [Column("c_material_einheit_id")]
        public int? CMaterialEinheitId { get; set; }
        [Column("c_lk")]
        [StringLength(10)]
        [MySqlCharSet("utf8mb3")]
        [MySqlCollation("utf8_general_ci")]
        public string CLk { get; set; }
        [Column("n_lk_hochkant")]
        public bool? NLkHochkant { get; set; }
        [Column("c_qk")]
        [StringLength(10)]
        [MySqlCharSet("utf8mb3")]
        [MySqlCollation("utf8_general_ci")]
        public string CQk { get; set; }
        [Column("n_qk_hochkant")]
        public bool? NQkHochkant { get; set; }
        [Column("c_bh")]
        [StringLength(10)]
        [MySqlCharSet("utf8mb3")]
        [MySqlCollation("utf8_general_ci")]
        public string CBh { get; set; }
        [Column("n_bh_hochkant")]
        public bool? NBhHochkant { get; set; }
        [Column("n_bh_dopp")]
        public bool NBhDopp { get; set; }
        [Column("n_is_container_verp")]
        public bool? NIsContainerVerp { get; set; }
    }
}