// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Preiskategorien für Fremdverpacker mit einem Standardpreis (Einkaufspreis)
    /// </summary>
    [Table("t_verpackung_preiskat")]
    public partial class TVerpackungPreiskat
    {
        [Key]
        [Column("n_id")]
        public int NId { get; set; }
        [Column("c_kurz")]
        [StringLength(25)]
        public string CKurz { get; set; }
        [Column("n_preis")]
        [Precision(15, 4)]
        public decimal? NPreis { get; set; }
        [Column("c_bem")]
        [StringLength(255)]
        public string CBem { get; set; }
    }
}