// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Liste der Losteile die vom Kunden deaktiviert wurden bzw. nicht mehr genutzt/verpackt werden dürfen.
    /// </summary>
    [Table("t_versand_artikel_blacklist")]
    public partial class TVersandArtikelBlacklist
    {
        [Key]
        [Column("n_kunde_id")]
        public int NKundeId { get; set; }
        [Key]
        [Column("n_auftrag_id")]
        public int NAuftragId { get; set; }
        [Key]
        [Column("c_fracht_teil_nr")]
        [StringLength(25)]
        public string CFrachtTeilNr { get; set; }
    }
}