// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Statikparameter für eine Verpackung die mit der Statik berechnet wird.
    /// </summary>
    [Table("t_verpackung_statik_param")]
    public partial class TVerpackungStatikParam
    {
        [Key]
        [Column("n_verp_id")]
        public int NVerpId { get; set; }
        [Key]
        [Column("n_verp_typ_id")]
        public int NVerpTypId { get; set; }
        /// <summary>
        /// t_holz_klassen.n_id
        /// </summary>
        [Column("n_holzklasse_id")]
        public int NHolzklasseId { get; set; }
        /// <summary>
        /// t_statik_belastungstyp.n_id
        /// </summary>
        [Column("n_belastungs_typ_id")]
        public int NBelastungsTypId { get; set; }
    }
}