// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Beipack Materialien die dem Beiblatt hinzugegeben werden. Sind Artikel mit der Kennzeichnung, dass der Artikel im Beipack zur Auswahl steht. Beieinflussen auch die Kalkulation.
    /// </summary>
    [Table("t_verpackung_beiblatt_beipack")]
    [Index("NVerpBeiblattId", Name = "IDX_BEIBLATT_ID")]
    public partial class TVerpackungBeiblattBeipack
    {
        [Key]
        [Column("n_id")]
        public int NId { get; set; }
        [Column("n_verp_beiblatt_id")]
        public int NVerpBeiblattId { get; set; }
        [Column("n_pos")]
        public int NPos { get; set; }
        /// <summary>
        /// t_artikel.n_id
        /// </summary>
        [Column("n_beipack_id")]
        public int NBeipackId { get; set; }
        [Required]
        [Column("c_bezeichnung")]
        [StringLength(150)]
        [MySqlCharSet("utf8mb3")]
        [MySqlCollation("utf8_general_ci")]
        public string CBezeichnung { get; set; }
        [Column("n_anzahl")]
        [Precision(10, 2)]
        public decimal NAnzahl { get; set; }
        [Column("n_einheit_id")]
        public int NEinheitId { get; set; }
    }
}