// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Daten wie Montage-Ende, Verpackungs-Ende und Geliefert zu einer Verpackung. Daten werden über das Einscannen der Statusblätter gesetzt.
    /// </summary>
    [Table("t_verpackung_status_zeiten")]
    public partial class TVerpackungStatusZeiten
    {
        [Key]
        [Column("n_verp_id")]
        public int NVerpId { get; set; }
        [Key]
        [Column("n_verp_sub_id")]
        public int NVerpSubId { get; set; }
        [Key]
        [Column("n_verp_typ_id")]
        public int NVerpTypId { get; set; }
        [Key]
        [Column("c_nr")]
        [StringLength(45)]
        public string CNr { get; set; }
        [Column("c_nr_org")]
        [StringLength(45)]
        public string CNrOrg { get; set; }
        [Column("d_montage_ende", TypeName = "datetime")]
        public DateTime? DMontageEnde { get; set; }
        [Column("d_verpackungs_ende", TypeName = "datetime")]
        public DateTime? DVerpackungsEnde { get; set; }
        [Column("d_geliefert", TypeName = "datetime")]
        public DateTime? DGeliefert { get; set; }
        [Column("n_user_id")]
        public int NUserId { get; set; }
    }
}