// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Losteilsystem - Speichert die Importkonfiguration. Mapping der Excelspalten auf die Datenbankfelder
    /// </summary>
    [Table("t_versand_import_conf")]
    public partial class TVersandImportConf
    {
        [Key]
        [Column("n_id")]
        public int NId { get; set; }
        [Column("n_auftrag_id")]
        public int? NAuftragId { get; set; }
        [Column("n_kunde_id")]
        public int? NKundeId { get; set; }
        [Column("c_name")]
        [StringLength(25)]
        public string CName { get; set; }
        [Column("m_bem", TypeName = "text")]
        public string MBem { get; set; }
        [Column("n_losteilnr")]
        public short NLosteilnr { get; set; }
        [Column("n_artikel_anzahl")]
        public short NArtikelAnzahl { get; set; }
        [Column("n_label_anzahl")]
        public short? NLabelAnzahl { get; set; }
        [Column("n_baugruppe")]
        public short? NBaugruppe { get; set; }
        [Column("n_baugruppen_abschnitt")]
        public short? NBaugruppenAbschnitt { get; set; }
        [Column("n_baugruppen_name")]
        public short? NBaugruppenName { get; set; }
        [Column("n_teile_nr_1")]
        public short? NTeileNr1 { get; set; }
        [Column("n_teile_nr_2")]
        public short? NTeileNr2 { get; set; }
        [Column("n_teile_nr_3")]
        public short? NTeileNr3 { get; set; }
        [Column("n_teile_nr_4")]
        public short? NTeileNr4 { get; set; }
        [Column("n_teile_nr_5")]
        public short? NTeileNr5 { get; set; }
        [Column("n_artikel_gruppe")]
        public short? NArtikelGruppe { get; set; }
        [Column("n_artikel_code")]
        public short? NArtikelCode { get; set; }
        [Column("n_artikel_name_1")]
        public short? NArtikelName1 { get; set; }
        [Column("n_artikel_name_2")]
        public short? NArtikelName2 { get; set; }
        [Column("n_artikel_name_1_en")]
        public short? NArtikelName1En { get; set; }
        [Column("n_artikel_name_2_en")]
        public short? NArtikelName2En { get; set; }
        [Column("n_laenge")]
        public short? NLaenge { get; set; }
        [Column("n_breite")]
        public short? NBreite { get; set; }
        [Column("n_hoehe")]
        public short? NHoehe { get; set; }
        [Column("n_gewicht")]
        public short? NGewicht { get; set; }
        [Column("n_label_notiz")]
        public short? NLabelNotiz { get; set; }
        [Column("n_din")]
        public short? NDin { get; set; }
        [Column("n_lieferant")]
        public short? NLieferant { get; set; }
        [Column("n_zeichnungs_name")]
        public short? NZeichnungsName { get; set; }
        [Column("n_zeichnungs_nr_1")]
        public short? NZeichnungsNr1 { get; set; }
        [Column("n_zeichnungs_nr_2")]
        public short? NZeichnungsNr2 { get; set; }
        [Column("n_zeichnungs_version")]
        public short? NZeichnungsVersion { get; set; }
        [Column("n_einheit")]
        public short? NEinheit { get; set; }
        [Column("n_lager_bedingung")]
        public short? NLagerBedingung { get; set; }
        [Column("n_vor_colli_nr")]
        public short? NVorColliNr { get; set; }
        [Column("n_vor_colli_barcode")]
        public short? NVorColliBarcode { get; set; }
        [Column("n_vor_colli_length")]
        public short? NVorColliLength { get; set; }
        [Column("n_vor_colli_width")]
        public short? NVorColliWidth { get; set; }
        [Column("n_vor_colli_heigth")]
        public short? NVorColliHeigth { get; set; }
        [Column("n_vor_colli_brutto")]
        public short? NVorColliBrutto { get; set; }
        [Column("n_vor_colli_netto")]
        public short? NVorColliNetto { get; set; }
        [Column("n_vor_colli_typ")]
        public short? NVorColliTyp { get; set; }
        [Column("n_lsp_barcode_extern")]
        public short? NLspBarcodeExtern { get; set; }
    }
}