// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Packstücke zum Wareneingang
    /// </summary>
    [Table("t_wareneingangpackstueck")]
    [Index("DGeliefertAm", "DRetoureDatum", Name = "IDX_GELIEFERT_RETOUR")]
    [Index("NVerpackungsTyp", "DRetoureDatum", Name = "IDX_VTYP_RETDAT")]
    [Index("NWareneingangId", Name = "idx_n_wareneingang_id")]
    public partial class TWareneingangpackstueck
    {
        [Key]
        [Column("n_id")]
        public int NId { get; set; }
        [Column("c_id")]
        [StringLength(45)]
        public string CId { get; set; }
        [Column("n_wareneingang_id")]
        public int? NWareneingangId { get; set; }
        [Column("c_packstueck")]
        [StringLength(20)]
        public string CPackstueck { get; set; }
        [Column("n_beschaedigt")]
        public bool? NBeschaedigt { get; set; }
        [Column("n_nicht_verrechenbar")]
        public bool? NNichtVerrechenbar { get; set; }
        [Column("m_beschaedigung", TypeName = "mediumtext")]
        public string MBeschaedigung { get; set; }
        [Column("n_laenge")]
        public int? NLaenge { get; set; }
        /// <summary>
        /// Länge des Bauteils auf dem Packstück
        /// </summary>
        [Column("n_laenge_bauteil")]
        public int? NLaengeBauteil { get; set; }
        [Column("n_breite")]
        public int? NBreite { get; set; }
        /// <summary>
        /// Breite des Bauteils auf dem Packstück
        /// </summary>
        [Column("n_breite_bauteil")]
        public int? NBreiteBauteil { get; set; }
        [Column("n_hoehe")]
        public int? NHoehe { get; set; }
        /// <summary>
        /// Höhe des Bauteils auf dem Packstück
        /// </summary>
        [Column("n_hoehe_bauteil")]
        public int? NHoeheBauteil { get; set; }
        [Column("n_bruttogewicht")]
        [Precision(12, 2)]
        public decimal? NBruttogewicht { get; set; }
        /// <summary>
        /// kat_grp=11
        /// </summary>
        [Column("n_verpackungs_typ")]
        public int? NVerpackungsTyp { get; set; }
        [Column("n_nettogewicht")]
        [Precision(12, 2)]
        public decimal? NNettogewicht { get; set; }
        [Column("n_anzahl")]
        public int NAnzahl { get; set; }
        [Column("c_position")]
        [StringLength(10)]
        public string CPosition { get; set; }
        [Column("m_bemerkung", TypeName = "mediumtext")]
        public string MBemerkung { get; set; }
        [Column("m_dokumentation", TypeName = "mediumtext")]
        public string MDokumentation { get; set; }
        [Column("n_zusatzpruefung")]
        public bool NZusatzpruefung { get; set; }
        [Column("n_kontrolle_der_kennz")]
        public int? NKontrolleDerKennz { get; set; }
        [Column("n_verrechnet")]
        public bool NVerrechnet { get; set; }
        [Column("n_getauscht")]
        public bool? NGetauscht { get; set; }
        [Column("n_packstueck_is_ippc")]
        public bool? NPackstueckIsIppc { get; set; }
        [Column("n_packstueck_aufgeteilt")]
        public bool? NPackstueckAufgeteilt { get; set; }
        [Column("n_packstueck_neu_vp")]
        public bool? NPackstueckNeuVp { get; set; }
        [Column("c_bezeichnung")]
        [StringLength(40)]
        public string CBezeichnung { get; set; }
        [Column("c_referenz_nr")]
        [StringLength(25)]
        public string CReferenzNr { get; set; }
        [Column("c_serien_nr")]
        [StringLength(25)]
        public string CSerienNr { get; set; }
        [Column("n_gefahgut")]
        public bool? NGefahgut { get; set; }
        [Column("c_gefahgut_bem")]
        [StringLength(100)]
        public string CGefahgutBem { get; set; }
        [Column("d_retoure_datum")]
        public DateOnly? DRetoureDatum { get; set; }
        [Column("d_eingegangen_am", TypeName = "datetime")]
        public DateTime? DEingegangenAm { get; set; }
        [Column("d_verpackt_am", TypeName = "datetime")]
        public DateTime? DVerpacktAm { get; set; }
        [Column("d_geliefert_am", TypeName = "datetime")]
        public DateTime? DGeliefertAm { get; set; }
        [Column("c_packstueck_barcode")]
        [StringLength(40)]
        public string CPackstueckBarcode { get; set; }
        [Column("c_packstueck_barcode_angeliefert")]
        [StringLength(45)]
        public string CPackstueckBarcodeAngeliefert { get; set; }
        [Column("m_retoure_grund", TypeName = "text")]
        public string MRetoureGrund { get; set; }
    }
}