// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Artikel die dem Wareneingangspackstück zugeordnet wurden.
    /// </summary>
    [Table("t_wareneingangartikel")]
    [Index("NWareneingangPackstkId", Name = "idx_n_wareneingang_packstk_id")]
    public partial class TWareneingangartikel
    {
        [Key]
        [Column("n_id")]
        public int NId { get; set; }
        [Column("n_wareneingang_packstk_id")]
        public int NWareneingangPackstkId { get; set; }
        [Column("n_bestell_artikel_id")]
        public int? NBestellArtikelId { get; set; }
        [Column("c_artikel_name")]
        [StringLength(150)]
        public string CArtikelName { get; set; }
        [Column("d_kunde_entschieden")]
        public DateOnly? DKundeEntschieden { get; set; }
        [Column("c_gemeldet_an")]
        [StringLength(100)]
        public string CGemeldetAn { get; set; }
        [Column("c_gemeldet_durch")]
        [StringLength(100)]
        public string CGemeldetDurch { get; set; }
        [Column("d_gemeldet_am")]
        public DateOnly? DGemeldetAm { get; set; }
        [Column("n_artikel_lieferant_id")]
        public int? NArtikelLieferantId { get; set; }
        /// <summary>
        /// Einheit der Einlagerung
        /// </summary>
        [Column("n_einheit_id")]
        public int? NEinheitId { get; set; }
        [Column("n_faktor_einheit_preiseinheit")]
        [Precision(10, 3)]
        public decimal? NFaktorEinheitPreiseinheit { get; set; }
        /// <summary>
        /// Anzahl der Einlagerung
        /// </summary>
        [Column("n_anzahl")]
        [Precision(15, 4)]
        public decimal NAnzahl { get; set; }
        [Column("n_lager_id")]
        public int? NLagerId { get; set; }
        [Column("n_lagerplatz_id")]
        public int? NLagerplatzId { get; set; }
        [Column("n_eingelagert")]
        public bool NEingelagert { get; set; }
        [Column("n_lief_anzahl")]
        [Precision(15, 4)]
        public decimal? NLiefAnzahl { get; set; }
        [Column("n_lief_einheit_id")]
        public int? NLiefEinheitId { get; set; }
        /// <summary>
        /// Wird genutzt fuer die Chargenverfolgung von Holz. Eingabe von Anzahl in der Einheit Stück. Dadurch können auch die Qubikmeter berechnet werden.
        /// </summary>
        [Column("n_lief_anzahl_stueck")]
        [Precision(15, 4)]
        public decimal? NLiefAnzahlStueck { get; set; }
        [Column("n_preis_einheit_id")]
        public int? NPreisEinheitId { get; set; }
        [Column("n_preis")]
        public float? NPreis { get; set; }
        [Column("c_kommissions_nr")]
        [StringLength(100)]
        public string CKommissionsNr { get; set; }
        [Column("n_bestellanteil")]
        public int? NBestellanteil { get; set; }
        [Column("m_bemerkung", TypeName = "mediumtext")]
        public string MBemerkung { get; set; }
        [Column("n_freigabe")]
        public bool? NFreigabe { get; set; }
        [Column("n_abweich_grund")]
        public bool? NAbweichGrund { get; set; }
        [Column("m_bem_abweichung", TypeName = "mediumtext")]
        public string MBemAbweichung { get; set; }
        [Column("c_barcode")]
        [StringLength(25)]
        public string CBarcode { get; set; }
        [Column("d_created", TypeName = "timestamp")]
        public DateTime DCreated { get; set; }
        [Column("d_eingelagert", TypeName = "datetime")]
        public DateTime? DEingelagert { get; set; }
        [Column("c_paket_nr")]
        [StringLength(15)]
        public string CPaketNr { get; set; }
        [Column("c_paket_nr_extern")]
        [StringLength(25)]
        public string CPaketNrExtern { get; set; }
        [Column("c_position")]
        [StringLength(10)]
        public string CPosition { get; set; }
        [Column("c_serien_nr")]
        [StringLength(25)]
        public string CSerienNr { get; set; }
        [Column("c_referenz_nr")]
        [StringLength(25)]
        public string CReferenzNr { get; set; }
        [Column("c_chargen_nr")]
        [StringLength(25)]
        public string CChargenNr { get; set; }
        [Column("n_einzeln_einlagern")]
        public bool? NEinzelnEinlagern { get; set; }
    }
}