// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Noch in Planung. MA die mit dem Worker arbeiten sollen Bestellung von Artikeln dem Büro mitteilen können.
    /// </summary>
    [Table("t_worker_bestellung")]
    public partial class TWorkerBestellung
    {
        [Key]
        [Column("n_id")]
        public int NId { get; set; }
        [Column("d_bestell_datum")]
        public DateOnly DBestellDatum { get; set; }
        [Column("m_bem", TypeName = "mediumtext")]
        public string MBem { get; set; }
        [Column("c_betreff")]
        [StringLength(100)]
        public string CBetreff { get; set; }
        [Column("c_besteller_org")]
        [StringLength(100)]
        public string CBestellerOrg { get; set; }
        [Column("n_status_id")]
        public int NStatusId { get; set; }
        [Column("n_user_id")]
        public int? NUserId { get; set; }
    }
}