// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Die aktuell unterstützen Schnittstellen der Zuschnittstationen wie Dimter, Hundegger, etc.
    /// </summary>
    [Table("t_zuschnitt_station")]
    public partial class TZuschnittStation
    {
        [Key]
        [Column("n_id")]
        public long NId { get; set; }
        [Column("c_bez")]
        [StringLength(50)]
        public string CBez { get; set; }
    }
}