// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pallet.ExternalDatabase.Models
{
    /// <summary>
    /// Die möglichen Holzarten (Schnittholz, Plattenwerkstoff) die von den Zuschnittstationen unterstützt werden.
    /// </summary>
    [Table("t_zuschnitt_station_holzart")]
    public partial class TZuschnittStationHolzart
    {
        [Key]
        [Column("n_id")]
        public int NId { get; set; }
        [Column("c_bez")]
        [StringLength(50)]
        public string CBez { get; set; }
    }
}